### ISSUE TITLE
Woocommerce "Save Settings" button hidden when in debug mode

### ISSUE THREAD

**Issue by Trebacz** [facebookincubator/facebook-for-woocommerce#1]
Not sure why the save settings button is hidden when in debug mode.

Unfortunately, this hides the save settings button for all Woocommerce applications until Facebook for Woocommerce is deactivated. If the intention is to hide only for Facebook for WooCommerce, it should probably be handled differently.

Current behavior hides the save settings in all WooCommerce admin and my payment gateways...

**Comment by aashay** [comment]
Hi David! Thanks for reporting this.  We thought we handled it so that it only hides the button for our tab, but if it's hiding it for all tabs, that's a problem.  Can you include screenshots/repro steps?

FWIW we're hiding the save button when _not_ in debug mode (you should see it when debug mode is on, along with text fields).  The reason for that is simple, if we show the save settings button but not the debug mode text fields, hitting "save" will send empty text to our backend and delete all of your IDs and API key! 

We opted to use AJAX instead.

**Comment by Trebacz** [comment]
No problem it's a fairly easy work around, but it had me scratching my head for awhile. Steps to reproduce:

1. Put Wordpress in debug mode (define('WP_DEBUG', true); set in wp-config.php)
2. Go to the Woocommerce "General" tab (or any tab under Woocommerce).
3. "Save Settings" button missing (also missing on other Woocommerce settings tabs).
4. Disable "Facebook for WooCommerce".
5. Return to WooCommerce "General" tab and the blue "Save Settings button is there.
6. Alternately take the site out of debug mode and the "Sve Settings" button returns.

Desired behavior is that the "Save Settings" button would be enabled for all Woocommerce tabs, except for Facebook for WooCommerce when in debug mode.

![facebook for woocommerce - debug mode](https://user-images.githubusercontent.com/19363347/28233729-b635191a-68ad-11e7-93ae-ccdca364da9e.png)
![facebook for woocommerce - no debug mode](https://user-images.githubusercontent.com/19363347/28233728-b633cfec-68ad-11e7-9776-29b85bd5fb05.png)

**Comment by dmitridr** [comment]
We've fixed this issue in (v1.6.0)[https://github.com/facebookincubator/facebook-for-woocommerce/releases/latest]. Please download the new version and re-open the issue if the problem re-occurs. The new version should be available on the WooCommerce site next week.

**Comment by Trebacz** [comment]
Thanks for the fix. It works great on 1.6.0 :)
