### ISSUE TITLE
2 pages on facebook

### ISSUE THREAD

**Issue by wooface** [facebookincubator/facebook-for-woocommerce#103]
Hi,  have two facebook pages. Installed your facebook for woocommerce on one site A  and everything ok. However on second site B when completing set up process  although it asks... choose a facebook page and gives a choice A or B, on  proceeding to the facebook pixel it only offers one A and not B, please can you  advise? ie should i click on A (pixel) even though it has nothing to do with B?  regards

**Comment by mengyingdu** [comment]
Hi wooface ,

In order to give your detailed advise, I need to ask some questions:

1. When you say ' site A and site B', do you mean: you have 2 Facebook pages, each one has associated with one website shop? Or, you have 2 website with 2 different pixels?

2. If you have access to multiple pixels (shared or whatever), you should can see and select them from pixel selector of 'Facebook Pixel' step.

Best,

**Comment by dmitridr** [comment]
Hello,

The "Facebook Page" and "Facebook Pixel" are distinct and unrelated objects in our system, but maybe you named them the same which is why the steps are confusing?

It's perfectly fine to use one same pixel on two different websites. However, when advertising be advised that if you are using the same pixel on both sides your traffic and audiences will be created using the all the visitors of both sites, and any retargetting ads will target visitors to both of those sites.

If you'd like to target each site's visitors individually with ads or using custom audiences, then we recommend using a different pixel for each one. In this case, you would have to create another pixel in a different ad account. Or use Business Manager to create one and attach it to another ad account.

Hope that Helps clarify the effects of using the same pixel on both setups. Feel free to re-open if you have follow up questions.
