### ISSUE TITLE
Facebook for woocommerce asks to complete configuration

### ISSUE THREAD

**Issue by otaviobps** [facebookincubator/facebook-for-woocommerce#108]
Every 2 to 4 days, facebook for woocommerce asks to complete the configuration. So if I go to the woocommerce integration page, the plugin is like it was never configured. So I have to delete the facebook pixel and start configuring the facebook pixel and the facebook for woocommerce again. 2 to 4 days later, the same thing happens again.

Does anybody know why facebook for woocommerce is losing its configuration?

**Comment by mengyingdu** [comment]
Hello,

We fix it from v1.4.3 and the latest version is 1.6.5 now. Can you try the new version?

Thanks.

**Comment by dmitridr** [comment]
Yep, this was a huge problem for us that we fixed in recent versions. Basically we were using the wrong hook for saving settings, so our save settings method was being called whenever any other plugin's settings were saved... and thus any time you would save any other plugin's settings, the settings for Facebook for WooCommerce would be erased.

See #43 and #31 for more discussion. Upgrading fixes the problem, this was fixed in 1.6.1.
