### ISSUE TITLE
Facebook Woocomerce Plugin Issues

### ISSUE THREAD

**Issue by yanickoff** [facebookincubator/facebook-for-woocommerce#1123]
My current facebook for woocommerce plugin is connected with another facebook page which account has been disabled. How do i change it to a new facebook page? I have tried alot of things but there is no way i can change it

In the plugin setting, it is showing: Your API key is no longer valid. Please click "Settings > Advanced Options > Update Token".

When i press on the setting, a Facebook pop up saying : Sorry, something went wrong.
We're working on getting this fixed as soon as we can.

**Comment by jeffsandoval014** [comment]
same here. :(

**Comment by DJSavill** [comment]
thousands of users of the plugin is having issues like this with it, from what I can read on forums since as far back as April at least, and Facebook isn't doing anything about it.

How are we supposed to spend money on Ads if we can't sync our products without any issues, blowing my mind!

Everything I open the plugin page in WooCommerce, I get an "unauthorised login attempt" from Facebook and it makes me create a new password every time (even when I've clicked YES it's me!)

Then after enough times of this, my page wont even appear in the dropdown list in the plugin to select anymore.

Total nightmare, along with so many other people, and zero action from Facebook. Madness.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
