### ISSUE TITLE
Hacked and logout of facebook

### ISSUE THREAD

**Issue by harrytheG** [facebookincubator/facebook-for-woocommerce#1128]
Hi, I have been using the facebook integration for WooCommerce a while now and every week I get the message that I need to update my token. When I try to login to my facebook it says I have been hacked. Even though I use two step verification via my phone. Does anyone else has this issue?

**Comment by kristofffff** [comment]
My account has been suspended. Facebook notify my that there are unusual activities on my account, then facebook logs me out and now my account is currently on review and i can't login anymore. Did your issue has been resolved?

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by woyao3002** [comment]
Hi Lindsey, 

My old Facebook account has been suspended. 

Now, I am trying to connect my website to a new page set up under a new Facebook account. However, it looks like the "Facebook for Woocommerce" plugin is still connected with a page under the old Facebook account as indicated by the message below.

"Your connection has expired. Please click Manage connection > Advanced Options > Update Token to refresh your connection to Facebook."

After I click on Manage connection, a window pops up with a message saying "Sorry, this content isn't available right now". Do you know how I reset the plugin in order to connect my website with a new Facebook page?

Best regards,
