### ISSUE TITLE
Problems getting match rate above 33.33%

### ISSUE THREAD

**Issue by metuza** [facebookincubator/facebook-for-woocommerce#113]
Hello.. I have several times totally deleted product cataloges and re-configured everything but it seems like i am not able to get a match rate above 33.33%

In Facebook product events when i check the sample history at the very bottom of that page i find that all products with catalog id like the below ones does not belong to catalog:

wc_post_id_7840
R130148

But these ID's that looks like this is OK, and found in catalog:

EC680131_11285

I have also found duplicate products listed here with different ID's:

R690157_9960  - This is in catalog and ok.
R690157  - This duplicate is not in catalog.

Absolute all products has a SKU set like this, EC680131 or R690157

I'm using latest versions always.

Brgds
Rune

**Comment by mengyingdu** [comment]
Hi,

As I understand, SKU should be unique, so your problem is you don't want duplicate, is it correct?
Also, can you explain more details? 
If you could give us your Facebook Page, it also helps.

Thanks.

**Comment by metuza** [comment]
Hello,

Actually it seems like the catalog and also the shop is working very well, no duplicate products as i can see. Also variable products seems to work ok in catalog and shop.

I think that this is a pixel issue, the pixel does not read the correct ID on my page/webshop as it sometimes return the differences as mention before.

The below 2 lines that shows the same product clicked on at 2 different days, first was found in catalog and second was not found. This info i find in Business manager -> Catalog -> Events.

As you can see it is the same product but the pixel has fired 2 different catalog ID's

05.10.2017 - R690157_9960 - Yes - Android-phone - https://www.arctic-fritid.no/produkt/friluftsliv/mat-og-drikke/kokeutstyr/kokeapparater/robens-logger-vedovn/

06.10.2017 - R690157 - No - Android-phone - https://www.arctic-fritid.no/produkt/friluftsliv/mat-og-drikke/kokeutstyr/kokeapparater/robens-logger-vedovn/

So what I mean is that pixel and catalog does not work ok together and thats why i get a very low match rate compared with my other webshop where i load catalog using a feed, it has always 100% match rate pixel / catalog.

This is my FB-page: https://www.facebook.com/ArcticFritid

Thanks

**Comment by dmitridr** [comment]
Hello,

Thanks for reporting this, 33.33% is definitely a magic number here, because we are always sending exactly 3 ids due to backwards compatibility where only 1 will ever match, for reasons outlined in #93. And it seems this is messing up the analytics that you are seeing.

Following up on my response in #93, it seems it's finally time to remove this backwards compatibility as most people have upgraded post v1.1 and resynced at least once.

You should be able to fix this for yourself immediately using the plugin editor by removing [these two lines](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/includes/fbutils.php#L114-L115) and hitting Force Resync on the settings page. In the meantime, we will work on incorporating this into the newer versions in a safe way.

**Comment by metuza** [comment]
Thanks.. Testing this now.

**Comment by metuza** [comment]
Ok, it seems like it works just great now as i today have match rate 100%

Thanks..

**Comment by jigneshdp1493** [comment]
Hello Metuza,

I need help from your side:

How to check Match rate in Facebook, It will be great if you will share the step of this. 

Thanks in advance.

**Comment by metuza** [comment]
Hello!

When you are into the product catalog view of your Facebook business account then just click the Events  in the menu and select correct pixel. See the attached image.

![match-rate](https://user-images.githubusercontent.com/11693376/33260299-afd6fa3a-d35f-11e7-9c7c-a1aaa605e385.JPG)

**Comment by tahoff** [comment]
This has been fixed in version 1.7.0
