### ISSUE TITLE
Issue with bulk variation action

### ISSUE THREAD

**Issue by jerbiun** [facebookincubator/facebook-for-woocommerce#1217]
Hello,
after updating to the last version of the plugin "1.10.0", i had this issue with bulk editing variation values  changing regular price or sales price ... showing an alert and changes doesn't saved 

i deactivate the plugin and the issue is gone

Can any one confirm?

Facebook-for-WooCommerce 1.10.0
WooCommerce 3.9.3
Wordpress 5.3.2
PHP 7.3.11

**Comment by simonporter007** [comment]
Hi @jerbiun !

Could you let me know what the alert you received was, was it to do with the product being excluded from sync in the plugin settings, yet included in sync on the product directly?

If so, and you don't wish to sync the product and the variations, you can use either the bulk action "_exclude from facebook sync_" option from the All Products screen, or uncheck the "_include in facebook sync_" checkbox for each variation/product on the edit product screen. With that done, it should then be possible to update the products!

Otherwise, you may need to look at the product category exclusions set in the plugin settings.

If this isn't the issue that you've seen, it would be great if you could pass over more details so I could take a closer look!

Cheers,
