### ISSUE TITLE
Undefined property: stdClass::$id 

### ISSUE THREAD

**Issue by nabeel-s** [facebookincubator/facebook-for-woocommerce#1222]
Please fix this error:

```
Notice: Undefined property: stdClass::$id in /home/account/public_html/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php on line 4004
–
```

https://nimb.ws/UxdOgR

**Comment by simonporter007** [comment]
Hey @nabeel-s,

This issue should have been fixed with the latest release, v1.10.2 - though it wasn't possible for us to replicate this locally, so it would be great if you could let me know if it has solved it for you.

Thanks so much for reaching out. Any issues after installing the latest release, please let me know!

Cheers,
