### ISSUE TITLE
HTTP ERROR 500 - Desktop version

### ISSUE THREAD

**Issue by yatanasov** [facebookincubator/facebook-for-woocommerce#123]
Hello,
May I kindly ask you to investigate why my facebook webshop is not working ?
 I haven't made any changes, it just suddenly stopped working. It's not working for 4-5 days now:

https://www.facebook.com/www.dima.bg/shop/?ref=page_internal

Please let me know if I have to provide any additional information.

**Comment by dmitridr** [comment]
Hello,

Thank you for writing in. That's very strange, I will forward this issue to our shops team to see if there is any change during that time period that could be responsible.

In the meantime I can only give some suggestions for a workaround:
- I noticed you have v1.4.3, you could try upgrading to v1.6.5 and doing a force-resync.
- You have a lot of products when variations are included, I noticed some errors when loading the shop because there were >10,000 variants, the shops. You could try hiding some substantial # of products using the visibility option to see if that can help your shop.

I will update this issue if there is a resolution from the shops team.

**Comment by bebemarketplace** [comment]
HI i'm having same 500 Error when trying to go to https://www.facebook.com/bebemarketplace/shop

I upgraded to v1.6.5.  

Please help!

**Comment by dmitridr** [comment]
Hi @bebemarketplace your shop works for me now. Did you do something specific in order to fix it? That may help us resolve the original issue.

**Comment by bebemarketplace** [comment]
Dmitri

It doesnt work for us still. Shop on Facebook loads on mobile only and its
partial. I disabled this plugin for now since I dont think its stable with
the number of products + variations. Really hoping for this to work. I wish
facebook had some support but that didnt get anywhere.

**Comment by yatanasov** [comment]
Hello,
We are still experiencing the same issue on Desktop version :(( it is really affecting our business.. Having more than 10,000 variations should not be a problem and also it is not possible for us to change this I am afraid.. We really hope that this can work.. Please investigate and get back to us.. Otherwise - great plugin! Thanks !

**Comment by mengyingdu** [comment]
Hi @bebemarketplace,

I checked you Facebook Shop on desktop and Facebook app, both of them have shop section. There are 1057 product groups in your catalog, so I think your problem is 'not all product synced'?

It'd better to open an new issue if you still have this problem since they seem different to this one.

Thanks.

**Comment by mengyingdu** [comment]
Hi @yatanasov ,

I will reach out to shop team for your issue  and try to resolve it soon. Thanks for your patience!

**Comment by dmitridr** [comment]
Thanks to the engineer who built the BigCommerce plugin that jumped in and fixed this issue, this problem has been fixed.

@bebemarketplace @yatanasov I can load both of your shops on desktop now. If the problem re-occurs feel free to open a new issue and reference this one. Thanks for your patience.

**Comment by yatanasov** [comment]
Thank you very much for helping with this !
