### ISSUE TITLE
$ is not a function

### ISSUE THREAD

**Issue by Grin0011** [facebookincubator/facebook-for-woocommerce#1233]
When I want to add a category that must be excluded in the synchronization, I am getting a modal with three buttons. When I click the buttons, I am getting the error $ is not a function.
![image](https://user-images.githubusercontent.com/23629444/78454111-53b89880-7696-11ea-895d-f594783f5e1e.png)
![image](https://user-images.githubusercontent.com/23629444/78454121-5fa45a80-7696-11ea-8166-baa2c9f026cf.png)
![image](https://user-images.githubusercontent.com/23629444/78454132-6af78600-7696-11ea-9ee5-c9699f3bba28.png)

How can this be solved?

**Comment by wvega** [comment]
@Grin0011 Thank you for reporting this problem. The screenshots were very helpful!

In this case I believe a third party is assigning the `$` variable to something other than `jQuery`. However, the source of the problem is that the script used for that dialog shouldn't rely on the global `$` variable to use jQuery features.

We are working to include a solution in the next version of the plugin. In the meantime, the following steps should allow you to workaround that error:

1. Attempt to save the settings to make the dialog with the three buttons show up
1. Open the browser's console and execute `$ = jQuery`
1. You should be able to press any of the buttons now without seeing an error

Would you be able to try those steps and let me know if the plugin lets you save the settings?

**Comment by Grin0011** [comment]
@wvega Thank you for your response. Your fix was helpful and I was able to press any of the buttons and the product in the selected categorie for excluding on Facebook is hidden on Facebook. Thank you for your response.
