### ISSUE TITLE
Why won't Facebook accept the URL of my website in the About section of our Facebook page?

### ISSUE THREAD

**Issue by Nerjhor** [facebookincubator/facebook-for-woocommerce#1237]
We are a legitimate company with an established website, but when I go to enter our website: https://www.valobasargolpo.com  into the appropriate field in our About section on our Facebook page, it responds with an error message: "The website URL you provided is invalid. Please enter a correct URL and try again."

Why is this happening? Please ans this important question.

**Comment by lgfogle** [comment]
Hey @Nerjhor,

Thanks for reaching out! 

Based on your description here, this sounds like a problem you're encountering within Facebook, rather than within the plugin itself. I would recommend [reaching out to Facebook support](https://www.facebook.com/business/help/148723649153231) to get their assistance with this problem.

Cheers!
Lindsey
