### ISSUE TITLE
No Inventory Information on Feed

### ISSUE THREAD

**Issue by ericsukalac** [facebookincubator/facebook-for-woocommerce#1339]
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

No Inventory column showing up in the product feed to facebook. Because of this, facebook shows the product as In Stock but with 0 Inventory. In Catalog Manager, I see this error on my feed -> "Without inventory information, your products may not appear the way you want them to in ads." When I manually look at the feed, I see the following columns:

- id
- title
- description
- image_link
- link
- product_type
- brand
- price
- availability
- item_group_id
- checkout_url
- additional_image_link
- sale_price_effective_date
- sale_price
- condition
- visibility
- default_product
- variant

but nothing relating to inventory. I have "Manage Stock?" enabled for most of my products at the variation level.

Using Facebook for WooCommerce v 1.11.3
Using Woocommerce v 4.1.1

Please let me know if there's any additional information I can provide. Thanks!

**Comment by alfaryolanda79** [comment]
I have the same issue. Nothing related to inventory, atributes, variants in products panel.

**Comment by lgfogle** [comment]
Hey @ericsukalac and @alfaryolanda79,

Thanks for reaching out!

This sounds like an issue that our support team would be best suited to help troubleshoot, since it sounds like something may be conflicting with the product sync in these cases. If you're still experiencing these issues, could you please reach out to our team on the [Facebook for WooCommerce forum](https://wordpress.org/support/plugin/facebook-for-woocommerce/) for further assistance?

Thank you!
Lindsey
