### ISSUE TITLE
variant_label and variant_value is missing

### ISSUE THREAD

**Issue by the-old-one** [facebookincubator/facebook-for-woocommerce#1434]
This issue was already reported in the ticket #638 
It's still an issue in 1.11.4

There were a few more comments from other users after the ticket has been closed.
@lgfogle advised to open a new issue.

**Comment by lgfogle** [comment]
Hey @the-old-one,

Thanks for following up!

The `variant_label` and `variant_value` fields are only populated for variable products, and are left blank for simple products (since they do not have variants). This shouldn't prevent the products from syncing / displaying in Facebook, since these are generally feed _warnings_ instead of errors that prevent product sync. Could you please confirm whether that's the case for you?

Thank you,
Lindsey

**Comment by Disenosos** [comment]
I have the same problem, where the facebook pixel tells me error with variant_label and others with variant format. Variations field is blank

**Comment by lgfogle** [comment]
Hey @the-old-one and @Disenosos,

I wanted to briefly follow up to share that we'll be investigating how to handle the `variant_value` and `variant_label` field issues on the product feed. Facebook currently parses those fields for simple products as well as variable products, but we'll consider if there's anything we can do to address that on our end to avoid these warnings. In the meantime, though, your product sync should not be impacted since these are _warnings_ instead of _errors_ in the upload. 

Thank you!
Lindsey

_[Internal reference CH53675](https://app.clubhouse.io/skyverge/story/53675/)_

**Comment by simonporter007** [comment]
We've looked at the available options for this and there was no clear solution. We need to retain the variant columns for syncing variation products from WooCommerce, and it was this that caused errors when Facebook parsed the file for simple products. As we've now moved back to the API sync, and all new merchants will no longer be relying on the feed file sync method - this should resolve itself going forward.

Thanks all for your patience while we looked into this further!
