### ISSUE TITLE
woo commerce Facebook pixel isnt active to use in Facebook

### ISSUE THREAD

**Issue by Angelabm-29** [facebookincubator/facebook-for-woocommerce#1450]
Facebook Pixel isn't working, it isn't active in Facebook, and Im not able to upload any product through it.
I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.

## ✍️ Describe the bug
Each time I try to use the woo commerce pixel to upload catalog, Facebook shows its inactive, which it isnt and the number it appears on woo commerce, isnt the same as the one in Facebook.

##🚶‍♀️ Steps to reproduce
I have already tried creating other pixels, I deleted all my catalogs, and still, it doesn't work.
## ✔️ Expected behavior
when I go to add products to catalog, through pixel, it is supposed to show my active pixel when I click on pixel, but it isnt, they all show that aren't ready to use.

## 🗃 Logs
Im not a website developer so Im trying to learn with all the help centers from woo commerce and Facebook, but non of them have actually worked.

**Comment by lgfogle** [comment]
Hey @Angelabm-29,

Thanks for reaching out!

This sounds like an issue that our support team would be best suited to help troubleshoot, since they are experienced in determining issues with catalog sync and onboarding. Could you please reach out to our team on the [Facebook for WooCommerce forum](https://wordpress.org/support/plugin/facebook-for-woocommerce/) for further assistance?

Thank you!
Lindsey
