### ISSUE TITLE
Facebook for WooCommerce error: Unsupported post request. Object with ID 'XXX' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

### ISSUE THREAD

**Issue by gugasbubas** [facebookincubator/facebook-for-woocommerce#1460]
Hi, I'm getting the following message on WordPress when updating some products. Could you please help with this issue?

> Facebook for WooCommerce error:
> Unsupported post request. Object with ID 'XXX' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

Here's some info that may be helpful:

1. Facebook Page URL 
https://www.facebook.com/underthecovershop/

2. WordPress and WooCommerce version number
WordPress Version 5.5
WooCommerce Version 2.0.16

3. Facebook Plugin version number
Version 2.0.0

4. How many products you have
846

5. Types of products (i.e. anything besides simple/variable products won’t work)
Some variable, some simple

6. Do you have Duplicate SKUs in your system?
No.

7. What kind of customization plugins you’re using (if any)?
Several, happy to provide a list id required.

Thanks for your help!

**Comment by lgfogle** [comment]
Hey @gugasbubas ,

Thanks for reaching out!

In general, I believe this error occurs when a product has been deleted from the Facebook catalog, so the plugin can't identify the product correctly based on the ID (since it no longer exists in Facebook). The best way to handle this is to [reset the Facebook metadata](https://cloud.skyver.ge/WnuJbjNk) for the product(s) in question, and then click Save to resync the product.

If that doesn't help, could you please reach out to our team on the [Facebook for WooCommerce forum](https://wordpress.org/support/plugin/facebook-for-woocommerce/) for further assistance?

Thank you!
Lindsey
