### ISSUE TITLE
Regularly My Site is not responsded after the facebook pixel script

### ISSUE THREAD

**Issue by Moiz5251** [facebookincubator/facebook-for-woocommerce#1469]
Hello Support,

I have an issue regarding my WordPress website based on woodmart official theme and I have used similarly most of the necessary plugins but I have found the 1 very illogical issue when I open my website at my start of the day website has been loaded as per the attached file after the Facebook pixel script website is not loaded. Please look into it and let me know the issue from my side or I have a plugin to deactivate. 

Regards,
Murtaza

![apples-issue](https://user-images.githubusercontent.com/37368022/90600057-844b3a00-e213-11ea-88e4-7f6ba800fe98.jpeg)

**Comment by lgfogle** [comment]
Hey @Moiz5251,

Thanks for reaching out!

I think this is something that our support team should help investigate, since this may be related to your site's theme or environment. Could you please [contact our team on the Facebook for WooCommerce forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) so they can assist with troubleshooting?

Thank you!
Lindsey
