### ISSUE TITLE
Clicking "hide" on product keeps moving me to top of page

### ISSUE THREAD

**Issue by lvl99** [facebookincubator/facebook-for-woocommerce#153]
If I can't programmatically set products to hide using the filters, then I have to one-by-one click "hide" on all my French language versions of products. When I click the "Hide" button, it moves me to the top of the page.

Ideally I'd also appreciate some kind of bulk method to do this, by selecting multiple products, selecting the bulk action "edit" and then selecting "Hide from Facebook" before hitting "Apply".

**Comment by dmitridr** [comment]
Thanks for writing in! I agree that this would be a nice feature. If you are so inclined, please consider sending us a pull request. We're very happy to review!

**Comment by dmitridr** [comment]
I believe we have support for visibility editing via bulk edit as of 1.7.x. So there is a partial resolution here now.

**Comment by mengyingdu** [comment]
Hi @lvl99 ,

We should fix 'bulk edit' as built-in of product editor in [v1.7.4](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.4) 

Instead of changing the hide action UI behavior which may need take a long while based on our priorities, I would recommend you try change visibility via bulk edit (Note: we support built-in bulk edit in Woo, but not bulk edit advanced plugin.)

Close this issue for now. Feel free to open a new one if you need more help.

Thanks!
