### ISSUE TITLE
Not Connecting To Facebook page after upgrade to version 2 of plugin

### ISSUE THREAD

**Issue by hlupekile** [facebookincubator/facebook-for-woocommerce#1531]
When I use the older version of this plugin I am able to connect to my Facebook page but if I upgrade the plugin to version 2 it stops allowing me to connect to my Facebook page

**Comment by lgfogle** [comment]
Hey @hlupekile,

Thanks for reaching out! I'm sorry about that connection issue. Are you seeing a specific error message? Would you mind sharing a screenshot or copying / pasting the message text here for me?

Thank you!
Lindsey

**Comment by hlupekile** [comment]
Hi

Thank you for getting back to me. See attached screenshots of process with
error message.

**Comment by lgfogle** [comment]
Hey @hlupekile,

I'm afraid I don't see the attached screenshots - could you please try again, or copy / paste the error message text here?

Thank you!
Lindsey

**Comment by hlupekile** [comment]
Hi

See attached screenshots of process with error message. 
![Screenshot_20200817_214759_com google android  #gm](https://user-images.githubusercontent.com/70919386/92639872-b9135400-f2dc-11ea-8381-8f0d2ea35b5e.jpg)

**Comment by lgfogle** [comment]
Hey @hlupekile,

Thanks for sending that along! When you hover over the tooltip for that page, next to where it says `Not Eligible`, what message do you see there? I think that will have some clues about why you can't select this Page.

Thank you,
Lindsey

**Comment by hlupekile** [comment]
Hi Lindsey 

When I hover over it says I am not loaded as an admin on the business manager and I should request access. This does not make sense as I am an admin and this works perfectly fine before updating the plugin. So not sure if it is a Facebook or pluin issue.

Regards

**Comment by simonporter007** [comment]
Hey @hlupekile,

The new version of the plugin uses Facebook's latest API for the connection, which in turn uses your business manager to connect. The previous version of the plugin (v1.11.x) did not have any API access, and so the products were only synced by Facebook polling the generated feed file.

We've had a few merchants report this issue since the release of v2, and most of the time this appears to be account specific, rather than something we can fix within the plugin, as the selection of the page is handled by the Facebook connect application.

Based on a few other merchants conversations with Facebook, I would suggest making sure that your Facebook profile is added as a manager of the business with full manage permission for all assets (page, catalog, pixel) and that all assets are owned by the same business as well, not only allowed access to them. You should be able to log into Business Manager and select the asset to see the owner.

Finally, we have also been told by the Facebook team that there can be an issue when a previous connection attempt was made to a different business. It links the connections from then on to a different business, which may not be the correct owner of the page. To workaround this, it is possible to reset the external business ID in your database and then try connecting again. If you'd like to try this, the option_name is **wc_facebook_external_business_id** and will need changing to be a new value. For instance, if it's currently _skyverge-5f5646a59343a_, I would recommend setting it to _skyverge-store-5f5646a59343a_

If you're still encountering issues after this, it would be best to reach out to the Facebook team directly to see if they can assist with the business manager set up. Our support team may be able to help you gather the required information for them too and rule out any other common reasons we've seen. To speak to our support team, please could you [create a topic on the Facebook for WooCommerce forum](https://wordpress.org/support/plugin/facebook-for-woocommerce/)?

Cheers!

Simon
