### ISSUE TITLE
Facebook Ad account vs Analytics and Dynamic Ads not showing sale price issue

### ISSUE THREAD

**Issue by SummayaSharif** [facebookincubator/facebook-for-woocommerce#1535]
Hey,

Thanks for your patience, and thanks for writing in. 

1. This is normal, but the design in the Catalog Manager interface can look weird if too many copies of the same product are visibile, I will give them this feedback... it would be helpful if you could provide a screenshot? 

The way the plugin works is we create a FB product for each variant (to account for different price/image/etc). The Facebook infrastructure requires a different 'product' to account for this differing information, so there's no easy way around this.

2. If you had an existing Shop already on FB, the shop creation defaults to `Off` when using our plugin, you have to manually set it to `On` in the last step before hitting `Finish`, as this will override your existing shop. If you send us your page URL we can confirm that. You'll have to reset your existing settings and go through setup again to fix this.

3. Interesting. This seems like an issue with one of our interfaces? If you could provide a screenshot and a link to the product that would be helpful, we can pass this along to the right team.

4. The variations of a single product belong to the same product group, in FB terminology. The way Dynamic Ads works there should be no possibility that products from the same product group are shown in the same ad. Are you seeing this in the preview? (Again a screenshot would be helpful).

Looks like (2) is the only one our team can really do anything about. For the others we can pass along this issue to other teams, but won't be able to help directly aside from advice.

Hope that helps.

_Originally posted by @dmitridr in https://github.com/facebookincubator/facebook-for-woocommerce/issues/277#issuecomment-365379042_

Hey @dmitridr, I’d be greatly thankful if you could please update me on these issues that Im facing with one of the client’s fb account and dynamic retargeting ads. 

1- Fb ad account column is showing mac 10-14 purchases recorded with some having 0 conversion value [from September 7, 2020] while the analytics events are showing 43 purchases of a total $479

2- I ran retargeting dynamic ads with all products in stock in my catalogue with strikethrough price in catalogue info. it is showing the strikethorugh for some of the products in the ad while it shows the oroginal price for others. However the tsv we are updating has proper columns for both the original price and the discounted price, but the discounted price for the products not getting strikethrough is not getting updated on the catalogue.

**Comment by simonporter007** [comment]
Hey @SummayaSharif,

Thanks for reaching out!

The plugin has changed a lot since 2018, and the latest version uses the new API from Facebook to connect, so a lot of the original post there will be different by now. That said, it sounds like you are having separate issues regarding the data in your Ad Manager compared with your Analytics, as well as an issue with retargeting ads.

I'm afraid issues such as these we wouldn't necessarily be best placed to assist with. I would recommend reaching out to the Facebook Concierge Support team to ask about retargeting dynamic ads, and why the conversion data might be mismatching. You can reach them by completing the form available here: https://www.facebook.com/help/contact/552096935652452

Cheers!

Simon
