### ISSUE TITLE
Product Titles are showing HTML tags

### ISSUE THREAD

**Issue by lthomas122** [facebookincubator/facebook-for-woocommerce#161]
Since updating the plugin from v1.32 to v1.66, I now have HTML tags showing up in my product feed, which previously wasn't an issue. I know it's not best practice to have HTML tags in your product title but it is needed in my case.  

Is there anyway to fix this?

![image](https://user-images.githubusercontent.com/13396465/33120804-116be574-cf6b-11e7-8e07-263bf3210e36.png)

**Comment by mengyingdu** [comment]
Hi,

If you upgrade from 1.32 to 1.66, that is a huge upgrade. From user request, we enable line break in description (but only line break, rather than html tag). This shouldn't affect product title. Did  you see this tag on product page as well?

Thanks.

**Comment by lthomas122** [comment]
No not on the product page, but you can obviously see it in cms/admin
panel. Yeah the plugin didn't get any update notifications at all, hence
the massive leap in versions.

Is there anyway I could possibly add a snippet to the plugin scripts that
could maybe strip out the html tag before being sent over to Facebook?

**Comment by lthomas122** [comment]
Oh do you mean the Facebook shop product page? If so yes it's visible on
there too.

**Comment by mengyingdu** [comment]
Hi,

I think your issue is about wordpress or woocommerce rather than our plugin. At the meanwhile, I found some resource for you and hope it is useful: https://medium.com/@clarklab/add-a-line-break-in-a-wordpress-title-b3aeff346037

As short fix, I would recommend use whitespace rather than line break tag. So at least, the product will show regularly.

**Comment by mengyingdu** [comment]
Hello,

There are some update: 
We will strip out HTML tag in next version in order to avoid this weird feed, however, in that case product title only have one line. We have to do this because it will cause some problems with ads (though maybe not in the shop).

I double checked and confirmed that in your WooCommerce store, you can use <br> as line break in product title. 

Thanks.

**Comment by lthomas122** [comment]
Basically, I have no qualms with it being one line on Facebook at all; it's
just I need the break on the WooCommerce store. Thanks for that link I will
definitely check it out, really appreciate it!

**Comment by mengyingdu** [comment]
Hope it helps.
