### ISSUE TITLE
Shop can't be published

### ISSUE THREAD

**Issue by Drakezpyro** [facebookincubator/facebook-for-woocommerce#1644]
Hi,

I have an issue with my facebook shop. Shop can't be published. I have this message about 1 week.
I sent a message to facebook but no reply.

How can i fix this?

Help me please. Thank you.
![fbissue](https://user-images.githubusercontent.com/73437328/97113673-3b6ca180-16ec-11eb-81e8-dc90c3213a08.PNG)

**Comment by simonporter007** [comment]
Hi @Drakezpyro,

Thanks for getting in touch! The error you've shared seems to suggest that the Facebook review process found some violation to their Merchant Agreement. I'm afraid this isn't anything we can control from the plugin side of things, and indeed, Facebook would be best placed to assist.

I would recommend reaching back out to their support to see if they can offer any further assistance in what the violation was so that you can publish your shop through Business Manager and begin to use our plugin!

Cheers,
