### ISSUE TITLE
 The plugin does not remove products that no longer exist in the woocommerce store

### ISSUE THREAD

**Issue by Izomar** [facebookincubator/facebook-for-woocommerce#1651]
As in the topic, the plugin synchronizes new products, unfortunately, it does not remove products that no longer exist in woocommerce from the fecebook store. Please solve the problem. Alternatively, how can you remove all products from the facebook store to create a new sync

**Comment by simonporter007** [comment]
Hey @Izomar,

Thanks for the question! In previous versions of the plugin, it used a feed file to sync your products and this was set to "_replace_" any existing products. This would mean that any products not included in the file would be removed from your catalog.

In newer versions, since v2, we use an API to sync the products which is better performing and allows us to do ad-hoc syncing of individual products, rather than all at once. However, because it syncs the products as they are edited, created, or deleted, it doesn't retroactively remove any other products that are now missing. It should delete products from the catalog as they are deleted from WooCommerce now though.

There are a few things you can try to get the catalog back in order:
- Retrieve the latest feed file from the server and upload it to your catalog as a manual file upload using the "_replace_" option.
- Delete the products manually from the Facebook catalog if there are not that many
- Delete the catalog from Commerce Manager and Uninstall the plugin from the **WooCommerce** > **Facebook** page. This will then let you run through the connection process again to create a new catalog and, once complete, initiates a full product sync of only the existing products.

If you'd like further information or assistance on any of the options above, our support team would be best placed to assist! You can reach out to them here: https://wordpress.org/support/plugin/facebook-for-woocommerce/

Cheers!
