### ISSUE TITLE
Set Up Default Variant Value for Variable Product

### ISSUE THREAD

**Issue by webplease** [facebookincubator/facebook-for-woocommerce#171]
Hi to all,

i have many products with variants on my shop, when I syncronize all products on the Facebook showcase it's shows the maximum price of the variant. How can i choose the right price to show? Or how can i show the min price?

**Comment by jieminz22** [comment]
Hi,
Try set the default price on Woo with the price you'd like to show and see if it gets updated on Facebook.

**Comment by webplease** [comment]
Hi jieminz22, how can I set the default price on Woo?

**Comment by mengyingdu** [comment]
Hi,

There's some confusion here. You could set your default price in this way:
1. set default variant value (the one with min price)
2. sync product

By doing this, it should show the product item with min price by default. See screen shot if it helps you find it.
![default variant value](https://user-images.githubusercontent.com/24535640/33508325-8b72188a-d6ae-11e7-9294-d4a7fc2d8b9c.jpeg)

Let me know whether it works. 

Thanks.

**Comment by webplease** [comment]
oh, i never have payed attention to this option! Thanks very much!

**Comment by ramonahaha** [comment]
hi, I have the same problem. On the facebook shop storefront is the highest price from all variations and on each single product page is the variation with the highest price pre-selected. The above solution is not working for me. 
Thanks

**Comment by mengyingdu** [comment]
Hi @ramonahaha ,

Would you mind give us more details why the above solution not working for you ? Do you have extra customized configuration? If your case is different from this issue, feel free to open a new issue so it helps us track your problem.

Thanks.

**Comment by ramonahaha** [comment]
Hi mengyingdu, Thanks for your reply. No, I have not any extra configuration and I set the cheapest variation as default but the most expensive is shown on my Facebook shop storefront, which is daunting for my customers. And when I open the product the most expensive variation is pre-selected (default) and not the cheapest one, which I set on my website. It is working absolutely fine on my website, which means the cheapest variation is shown on the storefront and insight the product the cheapest variation is pre-selected (default). Last night I worked around the problem a little bit and I deleted the cheapest variation and then I added the same variation again and it is now correctly showing on Facebook. But I think on Facebook is never the default variation showing you only see the variation you added last. Default setting from woo on my website is not working on facebook. I can't show you a screenshot because it is working at the moment and if I would like show you the problem I must delete the most expensive variation and add it again, which is a bit of work.
And there are two more problems but I am not sure have I to open a new issue or not. Please tell me if I have.
If you follow this link https://www.facebook.com/commerce/products/1566458443445090/ and you click on the drop down menu (variation) there are 2 variation shown they do not exist. I had the last 2 variation in the menu a few years ago but deleted it and they are not shown or visible on my website but  since a month they are on Facebook now. Any ideas from where they come?
The second issue is (properly connected to the very first issue): On woo on my website I can choose the position in the menu but it is not working on Facebook. On Facebook the top position product is always the one you added last in woo on your website. Maybe not for other people but for me. Any help?

THanks again

**Comment by mengyingdu** [comment]
Hi @ramonahaha,

Thanks for your update! I checked your shop site, it's version 1.4.2. However, we enable default variant from v1.6.0, and it's v1.7.2 now. Can you try to upgrade and see whether it works ?

Thanks!

**Comment by ramonahaha** [comment]
Hi mengyingdu,

Thanks for your answer. But how can I upgrade facebook for woocommerce. I'm looking now for 2 hours and all the usual ways are not working. Even downloading the zip from woo website and uploading to my website is not working. I always have the message File already exists. And I can not find any doc's about it. Must I delete the old version and installing the new version including all set ups on my website and facebook? That would be a lot of work for just updating?

Thanks for your help.

**Comment by ramonahaha** [comment]
Hi
Thank you for your answer and help. I updated the extension and most things work a lot better than before but on that facebook link I mentioned before there are still 4 variations but I only have 2 on my website. I said before the 2 wrong variations (the last 2 in the dropdown list) are very old ones and I deleted these month age. They are not visible on my website. 
Have you got any ideas for that?

Thank you

**Comment by mengyingdu** [comment]
Hi @ramonahaha ,

It's probably because you jump form v1.4.0 to v1.7.2 and not all of your changes have been synced. 
Can you try:
"Re-configure Facebook Settings > Advanced Options > Delete Settings" and setup  Facebook for WooCommerce again.

Let me know whether it works.

Thanks.

**Comment by mengyingdu** [comment]
Since there is no more follow-up questions in 2 weeks after last suggestion, it seems works for you .
I will close this issue now, but feel free to open a new issue if you have other question. 
 cc @ramonahaha
