### ISSUE TITLE
Something went wrong when connecting to Facebook!

### ISSUE THREAD

**Issue by ad33lzia** [facebookincubator/facebook-for-woocommerce#1738]
## 🔎 Isolate the bug

- [ ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

Hi,

When connecting facebook for wocommerce its giving error at the end. Everything works well, it even says your are connected but when we click on the DONE button it gives us this error.

![image](https://user-images.githubusercontent.com/76518300/102988447-b8be6200-4535-11eb-8582-67a3ee4311b2.png)

Can you please help ?

##🚶‍♀️ Steps to reproduce

1. The first step
1. The next step…

**Comment by Lynda1204** [comment]
I'm having the exact same problem.  Have you managed to resolve this yet?

**Comment by jconroy** [comment]
Hi @ad33lzia @Lynda1204 this is almost always because the "Manage business" option wasn't allowed when going through the connection steps on the facebook side.

https://docs.woocommerce.com/document/facebook-for-woocommerce/#something-went-wrong-when-connecting-to-facebook

For future help the best places to get general support are
* [Facebook for WooCommerce forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) 
* Contact support team directly if you are a Woo customer - [Click here to get in touch with support.](https://woocommerce.com/my-account/create-a-ticket/)
