### ISSUE TITLE
Pulling Pixel from Wrong AdAccount

### ISSUE THREAD

**Issue by sstiavetti** [facebookincubator/facebook-for-woocommerce#178]
I have two Facebook ad accounts. The first account is my personal ad account, while the second one is my business account. The WooCommerce Facebook integration is only accessing my original personal ad account with an old pixel that I don't use anymore. It will not access my business ad account, which contains the pixel I actually use. I contacted WooCommerce support and they suggested I post the problem here.

Here are two screenshots:

The only pixel the extension sees is this one, the pixel I don't want to use:
![personal ad account pixel](https://user-images.githubusercontent.com/21638/33538038-fd9076fc-d873-11e7-811f-f54a8783f32b.jpg)

This is the pixel I want to use, but the extension will not seem to access my business ad account:
![the pixel i want to use](https://user-images.githubusercontent.com/21638/33538060-079480e4-d874-11e7-9f9a-4ee7a40436e8.jpg)

Additional details:

- Wordpress 4.9.1
- WooCommerce 3.2.5
- Plugin Version 1.6.6
- I have roughly ten simple/variable products
- I have no duplicate SKUs
- The plugin has not been customized in any way. I haven't even been able to complete setup due to the problem above.

**Comment by dmitridr** [comment]
Hello,

Thanks for writing in. Can you confirm that you have an existing pixel for 'Fearless Fresh' and give us the ID of the pixel assigned to this account?

If this is a business account, usually creating a pixel and assigning it to this ad account using the business manager interface should enable you to see the pixel inside the selector. #175 #164 are somewhat related to this.

**Comment by sstiavetti** [comment]
Thanks. Yes, I have an existing pixel for Fearless Fresh. Here's the Pixel ID: 115256959212663

**Comment by sstiavetti** [comment]
Hi there. Any word on this?

**Comment by sstiavetti** [comment]
Also, the plugin is only accessing my personal ad account, not business. It can’t see my business ad account. That’s the whole reason I’m logging this ticket.

**Comment by dmitridr** [comment]
Hi, 

Thanks for your patience. I've confirmed that the pixel ID you gave is not attached to any ad account, but is under your business. Could you please attach it to an ad account, following the steps provided in this guide?

https://www.jonloomer.com/2017/03/17/share-facebook-audience-pixel/

The section titled 'Share The Facebook Pixel' is the most relevant for this process.
Once you do this, if you launch our plugin again, the pixel should show up in the selector.

The reason the plugin is not showing your business ad accounts now is because those do not have pixels attached to them. Only accounts which are `assigned` pixels, will be shown in that selector.

Hope that's clear and it helps!

**Comment by sstiavetti** [comment]
No -- the pixel IS already in my business account. I shared it months ago. In fact there are TWO pixels attached to my business account. See attached. The problem is that the plugin still won't see my business ad account -- it only sees my personal ad account. 

Or, maybe there's a different cause to this problem. Here's the whole story:

I created the old pixel under my personal ad account. Then Facebook released the Business Manager, so I created a business ad account with a second pixel. Then I realized I could move my personal pixel into my business ad account, which I did. So then were two pixels in my business ad account. (These are the two I referred to above. See attached.)

But then when I click the Pixels menu in Business Manager, I have yet a third account with a business ID instead of an account number. The weird thing is, this is where my original business pixel actually lives -- so the business account I created (ending in 6922) is empty with no pixels. 

It's super confusing. I even made a short screencast to actually show you what's going on: https://www.screencast.com/t/Oquppxbwd

So I guess the question is, is this maybe causing the problem? Which ad account and which pixel should I connect to the WooCommerce-Facebook integration and use going forward? And can I delete any of these to make it less confusing? 

Here are the two pixels that currently exist in my business ad account:
![two pixels in business ad account](https://user-images.githubusercontent.com/21638/34065630-a73d7b80-e1b8-11e7-856c-8f17115cf87e.jpg)

Here is where it shows only two ad accounts:
![two accounts in ad manager](https://user-images.githubusercontent.com/21638/34065635-b5c74532-e1b8-11e7-81b5-293557f4c188.jpg)

Then there is suddenly this ad account, which doesn't appear in the ad manager screenshot above:
![additional business ad account](https://user-images.githubusercontent.com/21638/34065647-cff5d126-e1b8-11e7-8f8c-45fe728c38c8.jpg)

**Comment by dmitridr** [comment]
Hi,

Thank you for the extremely detailed screenshots and screencast. I think I understand the issue... 

@"Suddenly this ad account appears" (in your last screenshot)
This is actually a business account, and not an ad account. (Hence why it says `business id`)
Yes the pixel is in your business account, but unfortunately that is not enough for our plugin, it must be in an ad account. Let me explain further: 

`ad account` and `business` are completely different things in our system, a `business` can own multiple `ad accounts`. A `business` can also own multiple `pixels`. However unless the `pixels` owned by the business are also connected to the `ad accounts` using the procedure in the link I sent previously, they will not show up in our plugin, because our plugin will not show 'business-only' pixels.

So there are a couple of ways I can see for you to potentially resolve this in order to use our plugin:
- In the screencast, where you saw a large 'Create a Pixel' dialog at 1m20s, try to create a new pixel, then use that pixel. It will be tied to your 'Fearless Fresh' ad account and can be used by your business as well. This new pixel should show up in our plugin when you use it.
- Try the procedure in the link of my previous comment in order to tie the existing `pixel` and `ad account` together inside of your `business`. 

Hope that helps!

**Comment by sstiavetti** [comment]
Ok! I finally had time to sit down and do this, and thanks to your advice it's working now. But I  have another problem, so  I've created a new post on it.

**Comment by sstiavetti** [comment]
Actually, never mind on the other problem -- fixed it myself! Thanks again for your help.

**Comment by nadorna** [comment]
I also have same issue Trying to solve it from 2 days still no solution anyone help?

**Comment by jloafs** [comment]
Same issue here - can only view the pixel in my personal account and not from my business account. What is the solution?
