### ISSUE TITLE
Images not showing on catalogue

### ISSUE THREAD

**Issue by fagnersantos** [facebookincubator/facebook-for-woocommerce#182]
Hi,

After catalogue sync, the URL to the main image is set to https://external.xx.fbcdn.net/safe_image.php?d=AQAHBkGTQCHPkP2v&url=https%3A%2F%2Fwww.vanillashakeclothing.com%2Fwp-content%2Fuploads%2F2017%2F11%2Ffox_set_vs-1.png&cfs=1&_nc_hash=AQBFvmVwZpK_B2ZP

This returns a 1x1 blank pixel. How can I fix this?

Best,
Fagner Santos

**Comment by dmitridr** [comment]
Hello,

Thanks for reporting this issue.
Someone just reported this the other day #177. Our product catalog team is working on a fix. I'll update this when they resolve the issue.

**Comment by dmitridr** [comment]
Hello, I'm following up on older issues. Have you had any luck with resolving this? We believe it's due to a hotlinking problem from what I heard from our Catalog team. Essentially we try to download the images from your site for use in FB, but we find that the image isn't there and we instead get a 403 error. 

The recommended resolution is to try and disable any hotlinking plugins you may have, then reset the plugin and try to sync again. Hope this helps.

**Comment by Onedy** [comment]
This is happening now to me also. The urls to the images are set to a 1 pixel image at https://external-ecv1-1.xx.fbcdn.net/emg1/v/t13/17662351650976269643?url=https%3A%2F%2Fwww.facebook.com%2Fproducts%2Fimage%2F%3Fitem_id%3D5512054088891558%26display%3Dsingle%26version%3D1%26image_id%3D5454847281300864%26display_option%3Dbackground_padding%26logging_boundary%3Ditem_preview&fb_obo=1&utld=facebook.com&stp=dst-emg0_q75&ccb=13-1&oh=06_Aaq5ZQ-b4fX4c0iqiumTmRIHctGG1vgher13ex3chk9DVg&oe=6341CB82&_nc_sid=ce7fe6

**Comment by rawdreeg** [comment]
Hi @Onedy, 

This issue requires isolation and further investigation. Unfortunately, the GitHub issue tracker is not the best place for support. I suggest you follow the [recommended support channels listed here](https://github.com/woocommerce/woocommerce#support).
