### ISSUE TITLE
Unable to create variable product in Woo when plugin Facebook for Woocommerce is active

### ISSUE THREAD

**Issue by oakidoaki** [facebookincubator/facebook-for-woocommerce#189]
Had an issue with an customer not being able to add variable products. In short, the setting for variable product wouldn't stick.

I noticed an error (500) in Chrome insights concerning admin-ajax.php when trying to add attributes for variants after the product was saved once.

The only thing new in her store was Facebook for Woocommerce. Problem disappeared when disabling this product.

Can recreate and post screens etc. if this is unknown to you. Didn't find it in the list.

Running latest Wordpress, Woocommerce and Facebook for Woocommerce with Divi theme.

**Comment by tahoff** [comment]
@oakidoaki Thanks for filing this issue. This is a new issue, so screenshots and your website url would be very helpful in debugging this issue.

**Comment by oakidoaki** [comment]
Hi. New version of Woocommerce since last time.

I have the same problem, but wasn't able to reproduce the error I saw in
insights.

Adding screens. It's with and without Facebook for Woocommerce plugin
activated.
3 steps each. New product. Pre save. And post save.

It's Norwegian language, but I think you catch the drift.

As you see, with the plugin there is a combo for simple product
(enkeltprodukt in Norw) and variable for BOTH product data and the short
description.
I change it to variable, put in my data.
After the save it is a simple product again.

You see the url, but since you asked: https://rosegull.no

Say if you need more.

Kai



2017-12-14 17:07 GMT+01:00 Adam Hoff <notifications@github.com>:

**Comment by mengyingdu** [comment]
Hi @oakidoaki ,

There is no pictures in your comments, did you upload them?

Thanks.

**Comment by mengyingdu** [comment]
I checked your store which seems has already deactivate plugin. 
1. Are you using [v1.7.3](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.3) ?
2. What other plugins are you using? eg WP all import ? or sth else?

We need more information eg. screen shot pictures in order to repro your problem.

Thanks.

**Comment by oakidoaki** [comment]
Believe everything is the latest versions (provided it supports auto
update).


It's correct, the plugin is deactivated. Because the store manager adds
products. I activate and force resync on request.

I uploaded screens in the email reply. Guess I have to add in the git thing.

I'll do that later on after a nap :)

Kai

18. des. 2017 19:11 skrev "mengyingdu" <notifications@github.com>:

**Comment by oakidoaki** [comment]
Doesn't seem like Facebook for Woocommerce (at my version) does auto
update....

I had 1.6.4 - unaware that there was any new version.

I'm dowloading 1.7.3 now to see if the problem still is there.

Kai

2017-12-18 19:25 GMT+01:00 Kai Olav Fredriksen <kai@oaki.net>:

**Comment by oakidoaki** [comment]
Problem is gone with 1.7.3.

Kai

2017-12-19 7:25 GMT+01:00 Kai Olav Fredriksen <kai@oaki.net>:

**Comment by mengyingdu** [comment]
Hi @oakidoaki ,

Glad to hear your problem has been solved!
Just want to clarify: Auto-upgrade means that you will get 'upgrade' notice in your Woo Admin, you still need to click on the button to upgrade. For example, in wordpress plugin page you may see the attached screenshot:

Before this upgrader was enabled, you WON'T receive this notice. This is because Wordpress will ONLY check version update for plugins hooked on "their" repository. Hope it helps you understand the reason why you didnt auto-upgrade.

![auto upgrade](https://user-images.githubusercontent.com/24535640/34147076-46c80112-e451-11e7-8808-5d6b5b9646fe.jpeg)

**Comment by mengyingdu** [comment]
I will close this issue now since the latest version works for you.
Thanks.
