### ISSUE TITLE
incompatibility issue with WooCommerce Membership: Incorrect price exported when membership plug is in use

### ISSUE THREAD

**Issue by barefiction** [facebookincubator/facebook-for-woocommerce#191]
When store uses Woocommerce Membership, the Facebook for Woocommerce plugin is taking the price for a product based on what the Admin User would pay as per the Woocommerce Membership plugin's discount methods.

Meaning that whichever call the Facebook for Woocommerce plugin is using to get the product price, it is also taking into account the other plugin's discounts for an admin user who is a member of a Woocommerce Membership Plan that has a discount available to it.

This means the price on the Facebook shop for the store's FB page is incorrect and when a customer would click on the checkout on store button the product will get added to their basket at the actual price and be confusing/frustrating to customer; potentially alienating that customer.

I have also contacted Sky Verge regarding this but they have obviously suggested I contact you and Woocommerce recommended I post this here.

**Comment by mengyingdu** [comment]
Hi @barefiction ,

Is Woocommerce Membership  a plugin you currently using? We didn't hear about this problem before. If so, this maybe a compatibility issue. Can you give us more context?
Also, I would recommend installing latest version [v1.7.3](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.3) since we add more security gate in it.

Thanks.

**Comment by mengyingdu** [comment]
Hi @barefiction,

I checked your issue and it should be a compatibility issue between WooCommerce Membership and Facebook-for-WooCommerce. 

Also, I found some resource which restrict sale to membership only (it may not be your original goal, but maybe helpful to fix your problem). https://gist.github.com/bekarice/6e4b69698952c61b86a0

Our dev team is prioritizing fixing bugs and perf for now. However, we will be happy to review any pull requests. Feel free to send us the fix as a pull request!! We'd love to give you the credit for that.

**Comment by mengyingdu** [comment]
Hi all,

Because the eng team is swapped now, we aren't not actively building this feature to support membership plugin. However, we'd be happy to review any pull request to add this functionality, please consider sending us one!

**Comment by lgfogle** [comment]
Hey all,

I'm going to close this issue since it's been several years and many updates for both WooCommerce Memberships and Facebook for WooCommerce since this was initially reported. If this problem is still occurring on the latest versions of both plugins, could you please open a new issue with steps to replicate?

Thank you!
Lindsey
