### ISSUE TITLE
Cannot delete settings

### ISSUE THREAD

**Issue by phillipswdc** [facebookincubator/facebook-for-woocommerce#195]
I am trying to delete settings from the advanced options -> advanced settings area of the plugin in the integration tab of Woocommerce.

When I try I get the following error...

Sorry, something went wrong. This might be a temporary issue and we're working to get it fixed as soon as we can. Please try again later.

Any insight into the problem would be appreciated. 

Thanks
Kevin

**Comment by jieminz22** [comment]
Hi,

Can you send us your store URL so we can take a look on our side? Thanks.

**Comment by dmitridr** [comment]
@phillipswdc Any luck? If you give us your store URL we can probably reset it for you, though you will also need to run the [hidden command](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/assets/js/facebook-settings.js#L117) `delete_all_settings();` in the Javascript console within the browser.

**Comment by phillipswdc** [comment]
Sorry for the delay our FB campaign manager was out on vacation. We had disabled this plugin and installed pixel my site and info started to come in as expected. After a month we are going back to your plugin because we are seeing more sales volume than what should be there, it looks like double the sales.

So I am back at square one, I usually do not have much need for trouble shooting this as your plugin normally just works.

Our FB Page is...

https://www.facebook.com/KnuckleBonz/

Our website is...

https://knucklebonz.com

Our Pixel ID: 169668496957231

Let me know what I need to do to get this working. Thanks!!

**Comment by dmitridr** [comment]
Hi @phillipswdc 

Sorry for the delay in getting back to you. Glad to hear you're still using our plugin. 

Is the problem still the same one you had before, that you cannot delete the settings? I see some failure to delete in our logs. We can delete the settings on the FB-side for you fairly quickly, I just need a confirmation that this is what you would like us to do.

**Comment by WFrankling** [comment]
I am also having this issue and I would very much like you to perform the action you have mentioned above for me too. Can you let me know what you need me to do?

**Comment by dmitridr** [comment]
@WFrankling  Done. You should be able to set up again now.

Would you mind answering a couple questions? I'm debugging why this happened but wasn't able to find a cause. Hoping you can help us a little to try and pinpoint the problem.

- Do you use Business Manager to manage your page?
- Have you changed the permissions for the page (or business manager) since setting up our extension?

**Comment by dmitridr** [comment]
You may want to do a `Force Resync` after setting up again, or there will be some errors from the old set up being removed in a non-standard way.

**Comment by WFrankling** [comment]
Thanks for sorting this out for us. 

It appears that I am now able to reset everything up but when I get to the last stage I'm getting this error. Any ideas why this is now happening?

The content you requested cannot be displayed at the moment. It may be temporarily unavailable, the link you clicked on may have expired or you may not have permission to view this page.

In answer to your questions, I do use Business Manager to manage my pages. I did change some setting but that was due to the system now pulling in required information, for example, add to basket info so I was not able to use this to create remarketed adverts. I did delete the plugin to try and set it up again and that's when I discovered I was not able to edit anything any longer.

**Comment by sammul** [comment]
@WFrankling I noticed you are page advertiser role on your page. In order to use the plug-in, you need to have editor or admin role. Can you ask for higher permission and try again?

**Comment by WFrankling** [comment]
Thanks @sammul I've sorted it now. It appears that although I was an admin in the business manager somehow I wasn't on the page. That didn't fix the issue though. I had to log in as the person that originally created the page and then it worked.

I'm now getting these errors when I'm trying to advertise my product sets which was the initial error I was getting hence deleting the plugin to try and start again. I'm not sure why these errors are showing because this is not the case and everything was working previously.

![image](https://user-images.githubusercontent.com/25960739/36529507-6afed726-17b0-11e8-892d-62e04edec954.png)

**Comment by sammul** [comment]
@WFrankling Is it still broken for you? If so, can you share your pixel id with me?

**Comment by WFrankling** [comment]
I have managed to fix it now, thanks

**Comment by adkinzd** [comment]
@dmitridr 
I am also having this issue . Can you let me know what you need me to do?

Our FB Page is...

https://www.facebook.com/Oncanvaswallart-1235158439964917/?modal=admin_todo_tour

Our website is...

https://oncanvaswallart.com/

Our Pixel ID: 219562232320699

**Comment by didaggelos** [comment]
I am also having this issue  .  Cannot delete settings  - Can you let me know what you need me to do?

Our FB Page is...

https://business.facebook.com/zazuelaboutique/

Our website is...

https://zazuela.gr/

Our Pixel ID: 177763173061365

**Comment by TrainerMerch** [comment]
@dmitridr 
I am having this issue a well where I try to "Delete Settings" and it says "Sorry, something went wrong. This might be a temporary issue and we're working to get it fixed as soon as we can. Please try again later."

My FB Page is:
https://www.facebook.com/TrainerMerch/

My website is:
https://trainermerch.com

My Pixel ID is:
313644459235602

**Comment by parapenT1sta** [comment]
@jieminz22 @dmitridr 

Having the same issue, please can you delete the settings for me.

Fb: www.facebook.com/uOnAir.pt
Website: www.uonair.pt

Pixel ID: ‭302670516997438

I want to setup it with other account, I am leaving the admin. Thanks
