### ISSUE TITLE
How to Change Facebook Page 

### ISSUE THREAD

**Issue by fashionunlimited** [facebookincubator/facebook-for-woocommerce#197]
Hi 
I have integrated one of my Facebook page, but now I want to remove this Facebook page connection and want to integrate new Facebook page. I have tried to do Re-configure Facebook Settings, but it is not working.
<img width="691" alt="re-configure screen" src="https://user-images.githubusercontent.com/34994145/34473519-ccee188a-ef41-11e7-9c84-95687e954d5a.PNG">
 
<img width="944" alt="facebook settings" src="https://user-images.githubusercontent.com/34994145/34473522-d79c3b7c-ef41-11e7-8559-41e3a75a7c69.PNG">

**Comment by fashionunlimited** [comment]
HiI have already tried but it's not working. After click does not give any reaction.I tried in Mozilla Firefox and Google Chrome both. Also in Google Chrome I havetried with Ctrl + Shift + N also. 
Regards.

 Ambrish V Parmar
BS (Civil Eng)
Alpine USA Construction LLC
General Contractor
1981 State Route 27
Somerset, NJ 08873
Phone: 732 991 0789
Fax: 732 640 5335

**Comment by jieminz22** [comment]
Hi Ambrish,

Looks like there might be some problem on our end. Instead, you can go to the "Advanced Options" and click "Delete Settings".  This will clear up the settings and then you can configure it again. Let me know if it works.

**Comment by dmitridr** [comment]
@jieminz22 FYI, we disabled Page Editing for Woo. Because the Shop migration had too many edgecases. It's disabled for almost all platforms now.

Ambrish, as Jiemin said, you can still change the page by resetting entirely. That should work.

**Comment by fashionunlimited** [comment]
HiThanks for your help.I have change the page by resetting entirely.Will you be able to help me for Pictures size setting in SHOP of mypage?My page SHOP is by default Crops all pictures from my woo commerce Media Library.
I do not have any problem if all pictures re scale without crops.My website address is www.fashionunlimitedonline.comMy Facebook page is fashionunlimited  or @fashionunlimitedUSA
You can see difference in both pictures. My website pictures are 667x1000 pixels.Regards.
 Ambrish V Parmar
BS (Civil Eng)
Alpine USA Construction LLC
General Contractor
1981 State Route 27
Somerset, NJ 08873
Phone: 732 991 0789
Fax: 732 640 5335

**Comment by dmitridr** [comment]
Unfortunately we can't help much with the square-cropping, as this is a feature the shops team would need to build. I can point you to this issue which there is a lengthy discussion about it, and possible workarounds : 

https://github.com/facebookincubator/facebook-for-woocommerce/issues/48

Perhaps if you have 667 x 667 (square) pictures in the additional images gallery, we can write a feature into the plugin to make those images the primary images the user sees in the shop. If that would be helpful to you, be sure to let us know!

I will close this issue, since the main problem is solved, but feel free to follow up on that issue I have linked if you have the same square cropping concern.
