### ISSUE TITLE
problem with the prices of some products

### ISSUE THREAD

**Issue by roby79** [facebookincubator/facebook-for-woocommerce#204]
the plugin works to perfection or just noticed that I have some products that the price is set to zero although in the woocommerce is right.
how do I update prices or upload the products back to the catalog ....

Help

this is the FB catalog
![schermata 2018-01-09 alle 00 22 22](https://user-images.githubusercontent.com/35241846/34697408-35c18d56-f4d3-11e7-97d9-421a18ca590f.png)

this is the link of woocommerce products
https://www.bodycolor.it/categoria-prodotto/glitter-tattoo/tattoo/

**Comment by mengyingdu** [comment]
Hi,

This has already been fixed. It seems your site is using old version 1.4.5. Can you upgrade and check it works? You can find the latest version [1.7.4](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.4) here.

Since there is a huge jump between the version you current using and the latest one, I would recommend re-config and then re-setup. It will clean up the incorrect products information on your FB shop.

Let me know if you need more help.

Thanks.

**Comment by roby79** [comment]
thanks the problem and solved I updated, but now I see the catalog on busness manager but does not appear on the window of my page, how can I solve?

**Comment by dmitridr** [comment]
Hello, 

Looks like we missed your message here. It sounds like if you don't see the products on your page that the shop was not created, which may happen if you do not select 'create shop' in the last step of setup.

#281 describes this in great detail. Hope that helps!
