### ISSUE TITLE
WPML & Database Server Crash & Delete Catalog from Facebook

### ISSUE THREAD

**Issue by vesceram** [facebookincubator/facebook-for-woocommerce#207]
OMG! Using new version 1.7.4
1. Not compatible with WPML pulling product for all languages and variations.
2. Crash my VPS server as it pull all products from database at once, I have 700product x 4languages x Variations x All images = Disaster.
I cant reach my admin side so I have to delete with ftp plugin and then reboot server.
3. I have 1.1K product in https://www.facebook.com/products/ and no option to delete them.  Is this posible?

**Comment by dmitridr** [comment]
1. What's your version of WPML? We are compatible with version >= 3.2, only the default language products are visible in the shop.
2. @mengyingdu is working on the perf of product sync. Sorry that you had this problem but we'll have an update for it soon.
3. You have to reinstall the plugin, go to 'Reconfigure' , 'Advanced Options', then 'Delete'. 

Hope that helps.

**Comment by vesceram** [comment]
1. I have latest version v3.9
2. That will be great!
3. I manage to delete catalogue and try to use just pixel side of plugin but now I get this error "Check that you're logged into your store. You can close this window and reopen the plugin from inside your store's admin panel."
I am logged and try 2 times to connect with facebook.

**Comment by vesceram** [comment]
Ahhh no not again. I choose not to export product to facebook but plugin start to export by itself and crash again my database,server...

**Comment by vesceram** [comment]
some more errors "Facebook extension error: Facebook for WooCommerce
Unsupported post request. Object with ID '237275066813087' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api"

**Comment by vesceram** [comment]
I delete catalogue but i now get this "Facebook for WooCommerce
Background syncing products to Facebook. Products remaining: 2815"

**Comment by dmitridr** [comment]
Sounds like you entered a weird state with the plugin, most likely you saw the error because you deleted the catalog. Try the following using the JS console (Ctrl + Shift + J In Chrome), run the command `delete_all_settings();` on the main configuration page, it should clear every setting added by the plugin, and it will stop syncing.

This can also be accomplished if you go to `Reconfigure Facebook Settings` > `Advanced Options` > `Delete Settings`.

**Comment by vesceram** [comment]
Yes you right I manage to reset plugin. And try again to send product to facebook but again I see in shop 4 same products for every language? Ofcourse my site crash again but plugin is working in background sending products to facebook .

**Comment by dmitridr** [comment]
Can you send a link to your shop? It should be showing the products not in the default language as invisible to users. We'll check to see if maybe there's a bug.

**Comment by vesceram** [comment]
Yes you are right for customer side it only showing product for default language for me it show x4. Now I only have to wait 5days to upload all 😊 https://www.facebook.com/pg/PaganRebels/shop/

**Comment by vesceram** [comment]
Again I have to delete catalogue as I see that plugin when send product to facebook upload every size separate. So if I have Shirt with 20colors and 5size and 4 language plugin will send 400 images-product to facebook so its imposible to use it.

**Comment by dmitridr** [comment]
5 days! We really need to improve perf ASAP.

Every product is separate because of the way the Facebook infrastructure is built. If you run Dynamic Ads, we will show the specific product (with the right color) that the user saw previously on your site. But in the shop, these products should appear under one variable product only. (The multi-languages ones will be invisible). Hope that helps clarify things.

Maybe we can provide an option to not sync the non default language ones entirely, that should speed up upload quite a bit.

**Comment by vesceram** [comment]
Well I stop upload when I see that it will not finish in 5 days it will need 1 century. On https://www.facebook.com/products side plugin send products like this 20colors variation X 5 size variation X  4 Language = 400 separate product for 1product with variation!  And I have 800 product most with variations I am scared to sum.  This plugin is must have for all shops on woocommerce so keep fighting.

**Comment by vesceram** [comment]
Again problem I manage this time to set plugin not to send products to facebook just to use pixel side so I can set add on facebook and it was working. BUT I have to go to woocommerce-settings-integration to activate another plugin and its just start to "Facebook for WooCommerce
Background syncing products to Facebook. Products remaining: 3058" crash mu server again. HOW CAN I STOP SYNCING OF PRODUCT NOT TO SEND TO FACEBOOK?

**Comment by dmitridr** [comment]
Hello,

Sorry for the lack of follow up here.

If you are still having this problem, many months later, please try upgrading to the newest version, v1.8.7 and doing a full reset. We improved Perf significantly in February and the new method of product sync is much much faster and solves the exact problem that you were having.

I hope you were able to resolve your issue with the syncing, but in case this happens to others as well I can share some solutions : in order to stop sync there are a couple of ways, you could open up the javascript console on the settings page and type `delete_all_settings();` then hit enter. Another approach to try is to delete all transient variables relating to FB : http://www.wpbeginner.com/plugins/how-to-manage-and-delete-transients-in-wordpress/ this should stop the sync as well.

The new version of the sync doesn't have a background sync, it is appx 60x faster on average because it uploads the products using a file instead of one by one. Hope that helps. Sorry again for the lack of follow up.
