### ISSUE TITLE
Strange dot in bottom of pages

### ISSUE THREAD

**Issue by zzbeck** [facebookincubator/facebook-for-woocommerce#208]
Hello,

After the recent update, I have noticed a small (but annoying) problem.
When _Facebook for WooCommerce_ is active, a small piece of code is added to the bottom of the page, adding a dot.

It's the following code:
`<div class="pub_300x250 pub_300x250m pub_728x90 text-ad textAd text_ad text_ads text-ads text-ad-links" style="position: absolute;">.</div>`

When I deactivate the plugin, it code and dot is gone.

Thank you for you work - really appreciate it.

**Comment by zzbeck** [comment]
Hello. I am not using an adblocker, the problem only vane after the recent update, and the problem follows across different browsers.

**Comment by dmitridr** [comment]
Hello,

Our extension does not add this code, a search through our repository confirms this. Therefore, this code must be being added by another extension that you have, or some other behavior.

As @citymont says it could be caused by AdBlock, but it could also be caused by an Anti-AdBlock extension that you may be using. For example this : https://github.com/sitexw/BlockAdBlock/blob/master/README.md

If you search for the string `pub_300x250 pub_300x250m pub_728x90 text-ad textAd text_ad text_ads text-ads text-ad-links` you will see that this extension uses that.

Hope that helps.

**Comment by bfp-zz** [comment]
It is happened in my website!
https://connect.facebook.net/en_US/fbevents.js
This js file some lines on 2018/1/12 15:32:05!
![fb](https://user-images.githubusercontent.com/656744/35313771-2dd9c44c-00fd-11e8-9817-d6b9fb14a759.png)
But they said their extension does not add this code.

**Comment by dmitridr** [comment]
Weird. Good point, maybe it was in the fbevents.js, this is not controlled by us but by a separate team. @zzbeck did the problem go away for you?

**Comment by dmitridr** [comment]
I assume it went away and this was an `fbevents.js` bug. If it happens again please open a new issue and reference this one.
