### ISSUE TITLE
Connect to new pixel

### ISSUE THREAD

**Issue by klorine** [facebookincubator/facebook-for-woocommerce#213]
Hello, 

I've created a new pixel and would like to integrate my page and store with that new pixel however I'm unable to find it when I click on edit specifically that I've created a new business account for this project and took ownership of the page from there. 
Any idea how to re-integrate everything with the new pixel? 

Thanks

**Comment by tahoff** [comment]
@klorine, if you can't see the pixel in the pixel selector step then it likely has to do with the business permissions (because only pixels associated with the business that's used in the page will appear). If you can't see the pixel, can you try re-completing setup by going to Advanced Settings, deleting all settings and then re-completing setup.

If neither of those options work, can you send your store URL and Facebook Page URL?
