### ISSUE TITLE
Multiple Facebook Products for same item (with variations)

### ISSUE THREAD

**Issue by miketurnermk** [facebookincubator/facebook-for-woocommerce#217]
Hi,

When I sync my Woocommerce catalog with the facebook store I end up with multiple products being shown due to having variations.

My variations attach different prices however each product listed is not unique

I.e.  If I have a keyring with personalisation available it is £8.95 but without it is £4.95

When looking at the Facebook store I just see 2 keyring products with the exact same name and description but a different price.

This really depends on where I am looking of course. For example, when tagging products I get both being displayed.  When I'm in the store some items show the highest price (which may put people off buying) and others show the lowest price (different default variations) and when viewing the catalog in the admin side, I see 2 of everything.

If there any way to either:

1. In facebook display the products so that they show the item with a price range (like Woocommerce does) i.e. £4.95-£8.95

2. Dictate the default variation selected so that products aren't showing in different ways (same variation attribute is present in Woocommerce across all products already)

3. Be able to customise the product title, especially for when we are tagging products in posts and both come up looking exactly the same i.e. keyring (with customisation)  keyring (without customisation)

Many thanks

btw site is www.oddbulls.co.uk and FB store is at https://www.facebook.com/OddBulls/

**Comment by tahoff** [comment]
Hey @miketurnermk, when I go to your Facebook Shop, I don't see duplicate products per se, but I see a product with two variations in the selector (you are right that the default variation isn't always the cheapest option). 

Unfortunately, the three proposals you have aren't currently supported by Facebook Shops. There is a way to include a Facebook-specific product description (but that would apply to each variant). In order to do this, you can go to the product page and enter in a Facebook Description.

**Comment by miketurnermk** [comment]
Hey, thanks for your reply.

You're right, you don't see duplicate products on the shop.  When looking at the Catalog I do see a seperate product for each variant which makes it difficult to understand which relates to which, and also when tagging I have to pick a specific variant.

The biggest issue for me is how the price displays.  Why do some products default to 1 variation setting but others default to another? - it would at least be some compromise if all products were defaulting to a particular value i.e. the cheapest.

With the proposal you mentioned in adding a facebook specific product description (applying to each variant) I don't think this is how it works.  When I go into my products that have variations there is only 1 facebook description field rather than a facebook description field appearing in each variation setting.  In my ebay product feed settings for example, such fields appear in each variation rather than in the overall product page.  

In terms of the custom product description itself though; it's less useful.  The only time I would really want to see a distinguisher would be in the catalog so I could identify which is which, but this would really apply to the title (at having the custom description at least visible in that long list)

**Comment by tahoff** [comment]
Thanks for clarifying where the multiple products are seen. In the Facebook catalog, each variant is seen as a separate product, which is why you are seeing multiple products.

Regarding the description, that's correct. The same description is applied to each variant. 

Regarding the price formatting, that's something we can add as an option in the Shop settings.

**Comment by miketurnermk** [comment]
Just following up on this again as there is a wider impact of this behaviour which is revenue impacting.

I plowed £120 into advertising shop products in the past few days but just stopped it all, why? - because of this problem.

In the ads i can select to have my products in a carousel, great....or not...

Every product variation appears as a seperate product in the carousel.  This means that if I am selling an item with different variations at different prices, the photo, and title appear the same but the price shows something different.

This really needs sorting.  Ideally we need to be able to advertise our products that are synced from Woocommerce (although I suspect this is a wider FB problem) so that the product 'group' is shown in ads and not every variation.  It should also show the item with a price range i.e. 9.99 to 14.99 

Imagine having 10 products with 5 variations each. You'd want the carousel to show all 10 products, and not just 2 products, taking up 10 spaces in the carousel, all looking the same apart from the price.

This kind of behaviour will simply cause drops in buyer conversions, and until fixed isn't going to be suitable for a lot of sellers investing in advertising on FB as a result..

**Comment by dmitridr** [comment]
This is an old issue so I will close this out, but I'll respond to the last comments, which unfortunately fell under our radar : 

It is an unfortunate limitation of the Facebook infrastructure that all variations display as separate products in catalog manager. However, these variations should *never* be shown in the same ad, though they can appear in preview, as you are seeing in your screenshot. 

The reason is that these variations are under the same `Product Group`. In facebook terminology this group is used as a category structure such that only one product from a product group will ever be displayed in an ad to the user. 

If you are still concerned that this is an issue, please try testing the ads as follows : 
Run the ad, then using another account, view some products on your own site, you should be able to see the ad without multiple products being shown in the carousel. If you are still having the problem, I would report a bug on Facebook itself, as this is a bug in Dynamic Ads.
