### ISSUE TITLE
Purchased not showing up in standard event

### ISSUE THREAD

**Issue by chalkandmoss** [facebookincubator/facebook-for-woocommerce#234]
When installing the Facebook for Woocommerce plugin/extension, some Standard Events were automatically created (ViewCategory, Search, AddToCart etc). However, Purchased is not part of these. It seems this should have been part of the automatically generated events. Can it be added? My site is www.chalkandmoss.com.

**Comment by sammul** [comment]
@chalkandmoss Purchase is one of the standard events. Are you not seeing Purchases fired when you have orders?

**Comment by chalkandmoss** [comment]
It’s a new site, so I haven’t had purchases yet :) So hopefully they’ll show up when I do get orders. Thanks!

**Comment by dmitridr** [comment]
We had a bug with purchases that was fixed in our latest version released just now (v1.7.7), available in our [latest releases section](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.7.7). Purchases should work in the new version.

**Comment by chalkandmoss** [comment]
Great, thanks! There are two versions there, both 1.7.7: 
- facebook for woocommerce
- facebook pixel for wordpress
I currently have the facebook for woocommerce extension (1.7.5), should I also have facebook for wordpress? What's the difference?
Also, how do I know when there are updates, as the latest update isn't showing up on my wordpress plugins page?
Thanks a million! 
Anna

**Comment by dmitridr** [comment]
To answer your questions:

The difference is one is for WooCommerce the other is for Wordpress (without WooCommerce). You don't need both, only one of them, the one for WooCommerce has more functionality.

We tested Stripe locally, we're waiting for confirmation that it fixed PayPal too, the fix was generic so it should have fixed the issue for all payment processors. It would definitely be helpful for us if you let us know that purchases are working correctly with PayPal for your site.

I'm not aware of how to get notifications from GitHub, but it may be possible... 

In terms of the latest update, you should be able to use [this guide](http://www.wpbeginner.com/beginners-guide/how-to-properly-update-wordpress-plugins-step-by-step/) to see the latest version and when it can be updated. I think it may take some time to appear though, we do have an upgrading mechanism within our plugin starting from 1.7.x, so it should show up if you have a newer version.

**Comment by dmitridr** [comment]
I'm going to close this out, assuming it is working for you, as we have many reports that Purchase works in the latest version 1.7.11. Please open a new issue for us if it is not!
