### ISSUE TITLE
5 errors when installing facebook-for-woocommerce extension

### ISSUE THREAD

**Issue by DaveNoakes** [facebookincubator/facebook-for-woocommerce#239]
Hi there,

I am trying to set up dynamic retargeting on Facebook. I had previously set up my pixel through Google Tag Manager. I followed the instructions on Facebook, which include installing your plugin, but I am now facing two issues.

1. The plugin gives me the message that my pixel is already installed on the site, so I should remove it first. However, I cannot find instructions anywhere online explaining how to remove pixels, except a couple of articles from 2016 which describe clicking buttons that now do not exist. In fact, there are lots of pages of people complaining about the fact that it's not possible to do so. I even spoke to a Facebook rep who wasn't able to tell me how to follow this instruction. So, I have paused the tags I set up in GTM assuming this might do the trick. The error message still showed up though, so I have just gone ahead and used the same pixel despite the warning.

2. Once the plugin announces that everything is set up and that I'm ready to start creating ads, I go to "catalog manager" and discover 5 error messages in the diagnostics box. These are the messages.

Missing content_type parameter from "Purchase" in South East Asia Backpacker's Pixel
Required parameter undefined is missing from Purchase events
To fix this:

Make sure the pixel code is installed correctly in your website
Make sure the event is sending all the required params: content_ids, content_type. Learn more.
For Facebook Pixel you can download the Facebook Pixel Helper for Google Chrome to debug your pixel fires

Missing content_ids or contents parameter from "Purchase" in South East Asia Backpacker's Pixel
Missing content_type parameter from "AddToCart" in South East Asia Backpacker's Pixel
Missing content_ids or contents parameter from "AddToCart" in South East Asia Backpacker's Pixel
Missing "AddToCart, Purchase, ViewContent" events in South East Asia Backpacker's Pixel

The Facebook rep I spoke to insisted that I would have to speak to WooCommerce about these errors, and that they have nothing to do with Facebook. I spoke to WooCommerce and they told me to contact you guys on this page. They told me you would require the following information.

    Facebook Page URL: https://www.facebook.com/SEAbackpacker/
    WordPress and WooCommerce version number: 4.9.2 and 3.2.6 respectively
    Facebook Plugin version number: 1.7.8 (updated seconds ago, previously was 1.7.7 and before that 1.7.3)
    How many products you have: 160 according to the facebook catalog page, 103 according to WordPress (some are variable)
    Types of products: Most Simple, Some Variable - all are virtual
    Do you have Duplicate SKUs in your system? I don't think so
    What kind of customization plugins you're using (if any)? I don't really know what would count here. We have YITH WooCommerce Wishlist, WooSidebars, WooCommerce PayPal Express Checkout Gateway, WooCommerce Frontend Manager - Ultimate, WooCommerce Frontend Manager, WooCommerce Deposits, WooCommerce Custom Product Tabs Lite, WooCommerce Currency Converter, Woo Checkout Field Editor Pro, WC Marketplace, Related Posts Pro (showing products on product pages), Product Enquiry for WooCommerce, Custom Related Products for WooCommerce (I don't think we're using this one, I'm surprised to see it's still installed), Custom Product Tabs for WooCommerce.

We are using Flatsome theme, which has a visual composer called UX Builder. (Just in case that counts as a customisation plugin)

Any ideas what I can do to fix this?

Thanks in advance for your help!

**Comment by mengyingdu** [comment]
Hi @DaveNoakes,

I went to your website and checked with pixel helper, it seems 'view content' and 'initiate check out fired' correctly (including content type and id) (see screen shot)

![content id](https://user-images.githubusercontent.com/24535640/35541604-7486b956-0510-11e8-9359-fec520b3f990.jpeg)

I also checked your catalog which seems normal. Can you upload a screenshot to show where you see the error messages in catalog?

As for the warning message' pixel has already installed XX', we detected that the fact your site have recent pixel traffic. You don't need to worry about that.

**Comment by DaveNoakes** [comment]
Hi,

Thanks for the response. I have attached the shot of the page where the error message is shown and then the page that you see when you click on the error message.

From what I can see on pixel helper, add to basket and proceed to pay were not been registered as specific actions, rather "SubscribedButtonClick". (see message below) Is that OK? I have unpaused the GTM tags I had with the pixel code installed, and those do register add to cart (actually I can't tell with proceed to pay, because it won't open in a new tab). Let me know if it is better to unpause them...

CUSTOM PARAMETERS SENT
formFeatures: []
buttonText: PROCEED TO CHECKOUT
buttonFeatures: Show
EVENT INFO
URL Called: Show
Load Time: 2247.71 ms
Pixel Location: Show

![captura de pantalla 23](https://user-images.githubusercontent.com/33318984/35549540-57d04950-0586-11e8-817e-7dee7de34a6e.png)
![captura de pantalla 24](https://user-images.githubusercontent.com/33318984/35549541-582141de-0586-11e8-8b2e-38d747baff80.png)

**Comment by DaveNoakes** [comment]
By the way, those other catalogues are there because I tried to use pixel caffeine plugin as an alternative. Now, I can't find how to remove the redundant catalogues...

**Comment by DaveNoakes** [comment]
Any news on this?

**Comment by dmitridr** [comment]
Hello,

Thanks for reaching out and thanks for your patience. I think as you suspect in (1) the problem probably has to do with the fact that you had the same pixel installed via GTM. If you have the same pixel installed twice with different plugins, there can be all sorts of different problems. 

If you would like to use GTM with a pixel with our plugin also, I recommend setting up a different pixel (different ID) in order to avoid the issues. I suspect that these issues are coming from GTM and how it interacts with our plugin.

I can recommend some things for you to try in order to try to pinpoint the problem further, which will also help us :
- Can you post some screenshots from what you are seeing in the pixel helper tool for the problematic events (AddToCart?). This will help us understand the problem.
- Could you try enabling/disabling GTM and going through with the pixel helper tool again to see if you can spot the problem. Does it only occur when GTM is disabled/enabled?

If you do decide to use a separate pixel, you should be able to see using the interface in your screenshots whether the errors are coming from our plugin or it's a problem in GTM.

Hope that helps.

**Comment by DaveNoakes** [comment]
Hi,

Thanks very much for your response. I have paused all of my original pixel tags in GTM (they had been paused originally, but I thought I'd try unpausing them to see if that helped at all) and have set up a new pixel on the Facebook for WooCommerce plugin. There is now 1 error in catalog manager, which references add to cart, purchase and view content. (See attached screenshot). Very strangely, add to basket is registered by the old pixel, even though it's paused in GTM. I have attached screenshots from pixel helper all the way through the purchase process.
Any ideas what I can try next?
![error message on catalog manager with new pixel set up through the plugin](https://user-images.githubusercontent.com/33318984/36192158-b96ccd2e-1160-11e8-98a0-419846cb3add.png)
![pixel helper on basket page after proceed to pay is pressed](https://user-images.githubusercontent.com/33318984/36192188-d0c109ae-1160-11e8-92da-d4d0b199b37b.png)
![pixel helper on basket page](https://user-images.githubusercontent.com/33318984/36192189-d0f8edc4-1160-11e8-8e15-9fc6a5f38980.png)
![pixel helper on checkout screen](https://user-images.githubusercontent.com/33318984/36192190-d12db824-1160-11e8-8db2-5e2040bafc5f.png)
![pixel helper on main shop page](https://user-images.githubusercontent.com/33318984/36192191-d167c672-1160-11e8-911f-db40aba5ea4b.png)
![pixel helper on order received page](https://user-images.githubusercontent.com/33318984/36192192-d1a073c8-1160-11e8-8d50-7ad981f0f62c.png)
![pixel helper on product view after add to basket is pressed bottom of screen](https://user-images.githubusercontent.com/33318984/36192193-d21c3986-1160-11e8-86a8-54942a88f42a.png)
![pixel helper on product view after add to basket is pressed top of screen](https://user-images.githubusercontent.com/33318984/36192194-d252bfba-1160-11e8-8c38-f472f7777cff.png)
![pixel helper on product view](https://user-images.githubusercontent.com/33318984/36192196-d2887ede-1160-11e8-888c-cf639a67dc5b.png)
![pixel helper once category is chosen](https://user-images.githubusercontent.com/33318984/36192197-d2bc47a0-1160-11e8-83fe-f9c1cde9810e.png)

**Comment by DaveNoakes** [comment]
Those images had titles that seem to have disappeared when I uploaded them, and they're not in order. Sorry about that. Hope you can make some sense of them nevertheless...

**Comment by DaveNoakes** [comment]
I've actually momentarily set the plugin pixel back to the orginal (duplicated) pixel as I'm running a dynamic ad which was using data from that pixel to choose its audience. Let me know if you think it'll work with the newer pixel (ie the plugin pixel won't interfere with the pixel the ad is using)

**Comment by dmitridr** [comment]
Hello,

Fortunately our internal tooling preserved the filenames even though GitHub did not, so I was able to understand the screenshot and the meaning. I think that since `ViewContent`, and `AddToCart` are firing with the new pixel from your screenshots, that it seems to be working... It's possible the Catalog Events Manager needs some time to detect the new events before that error goes away, because it is sending these events as confirmed by your screenshots. 

Here are the problems I noticed though:
(1) Purchase has an error. Would love if you could send us the result of right clicking and hitting `view source` on that page to our email: ads_extension_woocommerce@fb.com Also if you have a custom purchase flow, or any plugins that specifically enhance purchase, that would be good to know.
(2) Add To Cart at the 'Bottom' appears to work, but not at the 'Top' can you clarify the difference between those two and maybe a screenshot of where they appear on the page? Is this from a specific theme or plugin?

Aside from these two issues, the newer pixel should work, though I understand if you have ongoing dynamic ads and you don't want to change this for now.
