### ISSUE TITLE
Sync between Facebook and WooCommerce

### ISSUE THREAD

**Issue by Jyceek** [facebookincubator/facebook-for-woocommerce#240]
Hi, 
Facing some issues with the sync between FB and WC
www.la-cabanne-des-createurs.com for the site and FB with www.facebook.com/pg/Lacabannedescreateurs

I've upgraded the connector to the last release 1.7.3 and resent a sync directly from Woocommerce, still KO with former entries that can't be deleted from Facebook.

Any idea ?

Best regards.
JC

**Comment by mengyingdu** [comment]
Hi @Jyceek,

Would you mind explain more details? 

Not sure whether i understood your case correctly:
You delete a product from Woo product editor, then it still exists on Facebook shop.

In the meanwhile, i checked our remote log, there's no error from your site.

Thanks.

**Comment by Jyceek** [comment]
Hi, 

Yes, that’s exactly the case. I delete a product from Woo and it still exists on FB.

 

Is there a way to clean FB with all those outdated products ?

 

Best regards.

Jean-Christophe.

 

De : mengyingdu <notifications@github.com>
Répondre à : facebookincubator/facebook-for-woocommerce <reply@reply.github.com>
Date : mardi 30 janvier 2018 à 01:05
À : facebookincubator/facebook-for-woocommerce <facebook-for-woocommerce@noreply.github.com>
Cc : Jyceek <klarer@orange.fr>, Mention <mention@noreply.github.com>
Objet : Re: [facebookincubator/facebook-for-woocommerce] Sync between Facebook and WooCommerce (#240)

 

Hi @Jyceek,

Would you mind explain more details?

Not sure whether i understood your case correctly:
You delete a product from Woo product editor, then it still exists on Facebook shop.

In the meanwhile, i checked our remote log, there's no error from your site.

Thanks.

**Comment by mengyingdu** [comment]
Hi @Jyceek ,

You can easily erase all of you Facebook data. 
Woocommerce settings page ==>
Integration ==>
Facebook-for-woocommerce ==>
re-config your facebook settings ==> 
advance option ==>
delete ==>
Get Started ==> redo set-up

I'm not sure why when you delete your product in Woo, it didn't delete from FB. I checked your log, and there is no error about that. Would you mind list the repo step? On all product page or single product page? Did you use some other plugins related to this action?
Let me know if you need more help.

Thanks.

**Comment by FlairTrade** [comment]
Apparently this is a known issue according to the response I received #224. It makes for a cumbersome integration unless you sell static product catalogs.

**Comment by dmitridr** [comment]
Generally, Woo and FB should remain in sync, unless there are some custom plugins that block this behavior, or unexpected user action is taken (For example, restoring your products DB to an earlier state).

I'm not sure what happened in this case, but a reset should not need to be done often.
@Jyceek if you still have this problem, feel free to open a new issue and reference this one. I think resetting according to the instructions @mengyingdu gave should fix your problem.

**Comment by FlairTrade** [comment]
@dmitridr why am I getting conflicting responses to the same question? You claim it's a plugin conflict that is causing the sync issue, yet @tahoff acknowledges "you're correct that we have an issue with removing deleted products if they're deleted on your site" and it's also reported in #209 . You are quickly editing bug reports to close them out as you did in mine #224 yet this issue is widespread. Why the disparity in responses between you and @tahoff?

**Comment by dmitridr** [comment]
We should no longer have any issue if the product is deleted or trashed in the normal way, at least not for new installations with users using the new versions. It's true that we had this problem in older versions, I think that's what Adam was referring to. I am not aware of any open issues with reproducible steps that show a normal deletion of the product is not reflected on FB.

We may want to disable the `Clear Facebook Metadata` option if that is what causing the loss of sync, though, thanks for flagging that. I've opened a new issue for that #274. We can discuss further out of sync issues there and open new issues accordingly. Also we plan to keep yours open #224 until there is a resolution. 

I closed this one not because all out of sync issues are solved, but because this particular case appears resolved. Hope that helps explain things.

**Comment by margar1n** [comment]
Hi to all. I have the same problem. How I can delete all products in FB ? I linked my WOO and FB page. All products was exported. But in description in Facebook I see HTML code/WPBakery shortcodes. I want to delete all products from FB. Support FB can't helping me. 

-------
I'm trying do like this but it not helps.

You can easily erase all of you Facebook data.
Woocommerce settings page ==>
Integration ==>
Facebook-for-woocommerce ==>
re-config your facebook settings ==>
advance option ==>
delete ==>
Get Started ==> redo set-up
--------

In integration no any info and buttons about FB. @mengyingdu
