### ISSUE TITLE
Facebook showing old sale prices

### ISSUE THREAD

**Issue by domGaultonRR** [facebookincubator/facebook-for-woocommerce#259]
<img width="851" alt="screen shot 2018-02-03 at 11 58 34" src="https://user-images.githubusercontent.com/26330785/35766971-a0c28928-08da-11e8-90e8-c5a03462c632.png">

Facebook has been showing old sale prices for a number of weeks now - I have updated the price on the site multiple times and republished stock level changes but nothing seems to update on facebook.

My site: https://oldschoolski.co.uk/product-category/ski-suits/
My facebook page: https://www.facebook.com/pg/oldschoolski/shop/?ref=page_internal

**Comment by mengyingdu** [comment]
Hi @domGaultonRR,

What's your current plugin version? 
(I checked your site but it's weird it doesn't show up in pixel helper tool.)

Also, I checked remote log from your site, there is no record to show the updates for sale price. The last update time is 12/02/2017. Can you list repo steps to update your sale effective date which raise this issue?

Thanks.

**Comment by domGaultonRR** [comment]
Version 1.4.1 but it is currently unactivated due it breaking the homepage.

The sale was taken down mid December hence the website showing the non sale prices - https://oldschoolski.co.uk/product-category/ski-suits/

**Comment by mengyingdu** [comment]
Hi @domGaultonRR,

We fix sale price date from v1.6.0, which is the reason why you can't see the updated sale price date.
Please check our [release](https://github.com/facebookincubator/facebook-for-woocommerce/releases).
Can you upgrade (at least 1.7.5) and check whether it works for you?

Since there is version jump between your current version (1.4.1) and latest one, I would recommend you delete setting and set-up with beginning. 
Steps:
1. go to 'WooCommerce' -> 'Settings' ->'Integrations' -> 'facebook-for-woocommerce' --> re-config your facebook settings' --> in the pop-up window, 'advance option' -> delete settings
2. go to 'plugins' -> deactivate 'facebook-for-facebook' -> delete
3. download new version of the plugin from the [release](https://github.com/facebookincubator/facebook-for-woocommerce/releases) page 
4. add new plugins
5. upload -> install -> activate
6. same path in step 1 go to the 'facebook-for-woocommerce' in integration section, 'get started'
7. finish set-up
8. wait till finish products synced to facebook

Let me know if you need more help.

Thanks.

**Comment by domGaultonRR** [comment]
I think this might have resolved it.

I am now getting old products on the facebook page that have been deleted from wordpress!
