### ISSUE TITLE
Manually list catalog on Facebook shop

### ISSUE THREAD

**Issue by vesceram** [facebookincubator/facebook-for-woocommerce#260]
Hello
I have catalog list-feed that I would like to manually send to our page Facebook shop. 
I am killing my self to find that option in business.facebook.com admin side. Do anybody know
how can this be done? Thanx!

**Comment by jieminz22** [comment]
Hi,
Facebook shop currently doesn't support uploading product via feed. Our catalog supports to upload products via feed, but it won't be sync-ed to your Facebook shop. I'll pass this request to our shop team. Thanks.

**Comment by christiaangieles** [comment]
I would love this feature - to be able to publish from the catalog in business onto the Facebook Shop page. 

That is a feature we'd love indeed.

**Comment by mengyingdu** [comment]
Hi @christiaangieles and @vesceram ,

This is a feature (onboarding DPA catalog to shops directly in business manager) that Facebook shop team are currently working on. Alpha test starts this week and will likely roll out within two months.

Thanks.

**Comment by dmitridr** [comment]
Hi all, 

Small update. The shops team has launched this feature, but it's gated to a select few whitelisted clients. From my communications with them, it seems they don't think the interest in the feature warrants opening it up to the public (though there are other considerations). 

I will keep this issue open for others to comment on, if there is enough interest, we can try to convince them to open it up because many people want it. Please comment here (if you haven't already) for us to get a sense of public interest in this feature.

Thanks for your patience.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
