### ISSUE TITLE
Add to Cart pixel not working properly

### ISSUE THREAD

**Issue by belladonnaboutique** [facebookincubator/facebook-for-woocommerce#269]
I went to check in my FB ads manager to make sure all my pixel events are working properly. 

I just had a sale last night and wanted to ensure the Purchase went through in the ads manager and the Purchase pixel looks fine, initiate checkout is good, but strangely the Add to Cart pixel hasn't fired in 5 days, which makes no sense because I have had a few sales and the Initiate checkout and Purchases are working. 

Then I went to my site and clicked Add to Cart, and when I was in the Cart, the Chrome pixel helper does not show an Add to Cart pixel event. It shows "subscribed button clicked," with that event being labeled as "add to cart," but the actual Add to Cart pixel is missing.
![screen shot 2018-02-05 at 3 13 11 pm](https://user-images.githubusercontent.com/35646111/35826727-97e64138-0a87-11e8-8d77-e854cb173106.png)

![screen shot 2018-02-05 at 3 00 11 pm](https://user-images.githubusercontent.com/35646111/35826519-f68b88e8-0a86-11e8-9e5d-e0dd3f567636.png)

**Comment by jieminz22** [comment]
Hi,

We've noticed this issue. Can you please take a look at #219 to see if the workaround works for you? Thanks.

**Comment by dmitridr** [comment]
Hi,

As Jiemin said, I recommend the workaround, but I bet there's a way we can fix it so AddToCart works for all users. I've marked this as a bug that we can address in our next sprint after we finish the perf work around product sync, in the meantime at least there's a workaround.

**Comment by dmitridr** [comment]
The AddToCart issue has been fixed. Here's what we did:

- If your store setting is redirect to cart, we fire the event on the Cart being viewed.
- If your store setting is not redirect to cart, we fire the event via AJAX when the button is clicked.

The fix is in v1.8.4 and later versions available [here](https://github.com/facebookincubator/facebook-for-woocommerce/releases/latest). Thanks for your patience!
