### ISSUE TITLE
getting 3 purchase conversions for the price of one

### ISSUE THREAD

**Issue by jessdaddy** [facebookincubator/facebook-for-woocommerce#271]
i think somehow i have the plugin pixel applied three times. but I cant figure it out for sure. every time make a sale FB is reporting 3 purchase conversions. how to check and correct? thanks 
site - stylemonkey.xyz
FB page /wearmorebananas

thanks again.

**Comment by jieminz22** [comment]
Hi,

Where do you see the 3 purchases being reported? Is there an Ad you are looking at in particular? Can you share your ad id? Thanks.

**Comment by jessdaddy** [comment]
Thanks for getting back to me.. Ad ID is 6083362588973

**Comment by jessdaddy** [comment]
Already stopped that one though.

**Comment by jessdaddy** [comment]
any ideas? about to start new campaign and hopefully the pixel wont be misreporting so much. thanks

**Comment by jessdaddy** [comment]
![imagesm_fri february 9 2018 7_29_32 am_01800](https://user-images.githubusercontent.com/7205015/36003931-182951ba-0d6b-11e8-8b88-9ad98ae08909.png)

**Comment by dmitridr** [comment]
Hello, 

In order for us to confirm the problem, I would recommend you install the `Pixel Helper` extension for chrome, and try doing a test purchase on your own site (maybe with a hidden product) and observe to see if the `Purchase` event fires 3 times as you suspect. If that's true, it's probably an issue with our plugin. And we can dig in further.

Otherwise, I think it may be a bug in our reporting interfaces... which we cannot help much with, except to pass it a long to another team.

**Comment by jessdaddy** [comment]
Ah okay, but how can I confirm the event fires one or three times without
running an ad? Where can I view it? Thanks.

**Comment by dmitridr** [comment]
The `Pixel Helper` extension adds a little tab on the top right which you can click, it will display the details of the pixel firing on any page. 

Here's a guide : https://www.facebook.com/business/help/198406697184603

**Comment by jessdaddy** [comment]
I guess it's a problem with the reporting interface. The pixel helper only
shows one. Thanks for your help.
