### ISSUE TITLE
Sync Crashes WEBSITE : memory issue

### ISSUE THREAD

**Issue by tonivm** [facebookincubator/facebook-for-woocommerce#273]
I have been trying to get this to work! I have tried it on the latest update 1.7.11 and it still does not work! It crashes my website every time which it cannot work if the website is down.

Website is needmystyle.com

PLEASE HELP!

**Comment by jieminz22** [comment]
Hi,

Can you please provide us more information? At what stage did it crash your website? Also, can you share any PHP stack traces within your error logs with us? Thanks.

**Comment by dmitridr** [comment]
Yeah it would be helpful to know at what stage the crash happens. If it is during product sync, @mengyingdu is working on a fix for `1.8` a complete change to how product sync works which should solve this problem. In that case, I would encourage you to wait until we have this version ready, sorry that you had this problem though.

**Comment by tonivm** [comment]
Yes that is exactly the issue.  The sync starts up and after a couple of products and variations I start to receive a 500 internal error on my website.  What is the tentative release of the new version?

**Comment by dmitridr** [comment]
I would say ETA ~1 week. We may release a beta version first, because it's such a big change. I'll update this thread when it's ready.

**Comment by tonivm** [comment]
Downloaded the beta 1.8 and still got a 500 internal server error

**Comment by dmitridr** [comment]
Thanks for trying it out, sorry to hear that it didn't work. @mengyingdu looks like we may need some more work on this, I'm guessing this is an out of memory issue, since the performance fix mostly fixed cpu.

@tonivm do you have any server or php logs you could provide us with a snippet of during the time of the 500? We'd love to fix this but need to confirm why it's going 500. The logs will greatly help us figure out what's going on. If you do have some, you can email us at ads_extension_woocommerce@fb.com

**Comment by dmitridr** [comment]
There's some further improvement in 1.8.2 that you can try. I strongly recommend doing a full reset of the plugin before attempting sync, to get the full benefit of the perf improvement.

**Comment by mengyingdu** [comment]
In 1.8.6, we have a specific fix for 500 error, and I would suggest upgrade to the latest [1.9.1](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.9.1)

**Comment by dmitridr** [comment]
Closing as there has been no reply. Hope the new version solved your issue.
