### ISSUE TITLE
Socket Timeout Error and Feature Requests

### ISSUE THREAD

**Issue by pramathesh** [facebookincubator/facebook-for-woocommerce#282]
Using a 1GB LEMP (VestaCP) server everything works fine until the plugin is activated and it starts syncing which gives me a socket timeout error for WP and consumes a very high amount of RAM thus knocking the entire website offline.

Feature Requests:
1. Allow changing of product description (Short Codes are currently copied in product description which is not needed)
2. Allow dynamic display of prices in different currencies as declared in WooCommerce (I'm using Price Based on Country to declare different prices for users from different regions until this should also be reflected on the FB Store for convenience of the customer rather than seeing a different price when they try to checkout).

**Comment by dmitridr** [comment]
Hello, 

Thanks for writing in. We are very aware of this problem, it's our top priority right now to fix the performance issues with product sync. @mengyingdu is working on a huge overhaul for how product sync works to make it much less performance intensive. This should be out in `v1.8.0`, eta 1 week.

Addressing your other requests:
(1) This is already possible if you use the FB product description, available under the Facebook section in the product edit screen, is this not working for you? We should have fixed shortcode compatibility in `v1.7.3` as well, weird that those are not working for you.
(2) Thanks for the suggestion, I agree with you. Unfortunately the limitations of the Facebook Infrastructure don't allow for multiple different prices per product in different currencies. Generally users create multiple pages, one per language, to deal with this limitation on the FB side. We can pass along this request to the core infrastructure team, but our team won't be able to help much with this since we work mostly on the plugin itself.

**Comment by pramathesh** [comment]
(1) Is this available under the prodct edit section in WooCommerce? I had to disable the plugin because of the socket timeout error. Hopefully the update fixes this.
(2) It's high time FB supports multiple currency listing for stores. The plugin WooCommerce Facebook tab would just display the entire website within a canvas but it would have all the fuctionality of the website including multiple currency. Product tagging is the only current benefit that I see at this stage with this plugin, but I hope FB takes such feedback into consideration in the near future.

**Comment by dmitridr** [comment]
We have a beta version out of `v1.8.0` if would love for you to try it if you're willing, available [here](https://github.com/facebookincubator/facebook-for-woocommerce/releases). It would be good to know if it fixes your timeout problem... It should, since we've replaced the model of product sync from many API calls to just one API call for the entire sync, via a feed.

(1) Yes, it's in the product edit section.
(2) Thanks for the feedback, I'll pass this along to our catalog infra team. Multi-currency is definitely not well supported right now.

**Comment by pramathesh** [comment]
Also, you may want to check

My base currency for the store is set at USD while the admin account under which I'd synced has the currency set to GBP. All the synced products were listed in GBP instead of USD. Something that could be a hidden bug.

**Comment by pramathesh** [comment]
When is the final release for 1.8.0 expected?

**Comment by sammul** [comment]
@pramathesh It's still in beta and concrete release date is not decided yet. The release will depends on how stable it is based on the users currently are using it.
