### ISSUE TITLE
Plugin works but doesn't post to facebook shop

### ISSUE THREAD

**Issue by gianlucarispo** [facebookincubator/facebook-for-woocommerce#298]
Hello,

I'm running an affiiate website. I've configured the plugin and imported my catalogue, but when I create a product on woo commerce it doesn't sync with facebook shop.

Infact I've got "n" products on facebook and "n+1" on Woocommerce list.

How can it be? Any ideas?

**Comment by gianlucarispo** [comment]
website is www.artikolar.it

**Comment by sammul** [comment]
@gianlucarispo I can see there are in total 36 products on your website and same on facebook shop. Am I wrong?

**Comment by dmitridr** [comment]
Hello, are you still having this problem? I am going to close this issue because it has been a while since your reply, but feel free to open a new issue and reference this one if you are still having this problem.

That said:

There are several ways to create a product which may not be synced properly to FB. For example, if you edit your DB manually to add a product, this will not be reflected on FB. Similarly, a number of extensions when used to create products, will not properly sync to FB, `WP All Import` is the one which causes the most issues for us.

If you are still having this issue, my recommendation for resolution would be to `Force Resync` all products or `Update` the product after you create new ones. Hope that helps.
