### ISSUE TITLE
Facebook for Woocommerce Help I can't Sync : Product Catalog is no longer valid.

### ISSUE THREAD

**Issue by Bolis5** [facebookincubator/facebook-for-woocommerce#308]
Hi,

I try to setup my shop to my Facebook page 

www.mexmarket.co.uk
www.facebook.com/mexmarketuk

I have my pixel working but I have problems so sync my shop. I have the same message on woocomerce 

attached

somebody can 

> help!!!
![screen shot 2018-03-04 at 21 16 58](https://user-images.githubusercontent.com/37050866/36950746-6d9ab546-1ff2-11e8-9ba4-4dea169254a7.png)

**Comment by jieminz22** [comment]
Hi,
Have you tried setup again as the message suggests?

**Comment by Bolis5** [comment]
Yes, I try to delete the plugin and nothing

**Comment by jieminz22** [comment]
Did you delete the plugin or delete the settings via the plugin?

**Comment by Bolis5** [comment]
Yes i try

**Comment by Bolis5** [comment]
I try everything and still the same problem!!!

**Comment by jieminz22** [comment]
Hi @Bolis5,

What is the current status of your shop? Is the settings deleted? If so, can you try setup again? If you still have this problem, we can check your catalog on our end.

**Comment by dmitridr** [comment]
@Bolis5 It appears (correct me if I'm wrong) that your page is owned by a business? I think this is related to the cause, could you make sure that you are an Admin on the page itself, not just assigned an Admin role by the business, and try again?

**Comment by Bolis5** [comment]
Hi @jieminz22 Yes still have the same issue. Let m know what I need to do please

HI @dmitridr Yes is for my business and Im the owner of the business page. Let me know what I need to do please.



Thank you!

**Comment by Bolis5** [comment]
I try just now to delete and setup again and still have the same problem 
![screen shot 2018-03-04 at 21 16 58](https://user-images.githubusercontent.com/37050866/37432093-25aa77be-27cf-11e8-80cb-7ce73d28ecb1.png)

**Comment by Bolis5** [comment]
I try just now to delete and setup again and is the same problem
![screen shot 2018-03-14 at 21 30 33](https://user-images.githubusercontent.com/37050866/37432164-5c2a271c-27cf-11e8-9e2e-3295e8e9e2b0.png)

**Comment by dmitridr** [comment]
This is a tough issue to debug. It looks like all API calls to Facebook are failing for you, so we have no logging on our side about what went wrong with your installation. 

I have a couple of ideas to try, but it may be a long process to solve, because the issue could be caused by many different things.

(1) Perhaps there is a problem with your user account? You could try creating another user and assigning the user to be an admin of the page. Then login as that user and try going through set up, does it work?
(2) Perhaps there is a problem with the page? You could try going through setup with a new page, to see if this would work. This would mean the problem is the page.
(3) Verify that the API key is being set into the database correctly. If you have a way to access your DB, you can check the table `wp_options` for the row marked `woocommerce_facebookcommerce_settings`. Does the value contain something like "fb_api_key";s:178:"EAA..." ? Or is the "fb_api_key" field absent or empty?

I suspect the answer is (2), but I don't know what the problem with the page could be. 
Alternatively, to (1) you could ask one of the other admins of the page to go through the setup, it may work for them. In any case, if you try those steps, we should have a better idea about what the problem is here.

**Comment by dmitridr** [comment]
I'm following up on older issues. If you are still having this problem, let us know if there is more we can do to help you by filing a new issue and referencing this one.

**Comment by samrgomes** [comment]
If anyone has issues on setting up Facebook for WooCommerce plugin this SAU/CAL post may be of GREAT help. It guides you in all steps.
https://saucal.com/the-definitive-guide-on-how-to-setup-woocommerce-facebook-instagram-shop/

Step 2.3 is specially useful if you're having problems deleting the current plugin's configuration.
