### ISSUE TITLE
Plugin failure and upgrade issue to 1.5.1 : FB Config Data Loss

### ISSUE THREAD

**Issue by NoviceWare** [facebookincubator/facebook-for-woocommerce#31]
Hello,

A couple of days ago, the plugin stopped working and prompted me with "Facebook for WooCommerce is almost ready. To complete your configuration, complete the setup steps". Apologies, but I don't remember the previous version of the plugin I was using (maybe 1.4.3??). However, I made no changes or updates to the site and all was working well and products were feeding successfully to FB until this message in the dashboard. When I clicked the link, after a couple of seconds, it would error with only a message that "we are working to fix the problem". I decided not to pursue that error as the 1.5.1 update showed as available and I thought that perhaps the update would rectify the problem.

Attempting to update the plugin through the normal Wordpress facility failed and stated that the package was not available. After reading issue #23 where it stated, "Don't worry, your data and connection with facebook is still saved in the backend.", I elected to deactivate, uninstall the old plugin, and upload version 1.5.1. Install and activation went fine, however, I am now prompted with, "Facebook for WooCommerce is almost ready. To complete your configuration, complete the setup steps". When I follow the link in the message box, it sends me to the Facebook for Woocommerce welcome page as if I never had it configured and working previously. If I try to select the existing page, I am warned that I have to disconnect from the existing or add it to a new page to continue.

I really don't want to restart this as it took awhile for FB to approve the listings and has delayed our FB release already and this will delay things further. Any guidance is greatly appreciated, especially since I don't want to have this happen in the future when the FB page is live.

I'm running WP version 4.8.1 and Woocommerce Version 3.1.2 with the Boutique child theme of Storefront.

Thanks!

**Comment by dmitridr** [comment]
Hello,

Sorry to hear that you're having trouble here. I tried an upgrade on 1.4.3 to 1.5.1 on our test servers and all data was still there, so I don't think the upgrade caused your data loss.

The "almost ready" message should only appear if there is no Facebook for WooCommerce data available in the DB, so somehow the data loss must have happened earlier.

If you can remember anything you may have done in the days before you saw this message that would be helpful to know. Were you saving/changing the settings of another different plugin? (That is my suspicion for the cause of the lost data, it was a problem in previous versions.)

Unfortunately you will likely have to reset the connection to continue. If your shop is still working on the FB side, you can continue to use it without resetting, but any updates you made on the woo side will not be reflected until you reset the connection and setup again. 

Let us know if the data-loss happens again in the latest version, hopefully this was a one-time thing because you were using a really old version that had this issue.

**Comment by nuclearape** [comment]
This has happened to me too :(

I upgraded to 1.5.X and the "almost ready" message is constantly showing - If I go to complete the setup steps as prompted it it comes up with the warning saying that our page is already connected to a store.

I have always kept the plugin up to date.

The FB Pixel is still working and the shop section on FB still has our products but I cannot make any changes to the plugin on our site as it "isn't set up"

How shall I go about fixing this? Disconnecting the website from FB and going through the setup process again?

**Comment by dmitridr** [comment]
@nuclearape That's troubling, but I'm glad you recovered. I still can't reproduce this problem.
Do you remember which version you updated from and how you updated?

Do you have any extensions which could be wiping the DB during uninstall? (e.g. DB Cleaner, WP Optimize?)

**Comment by exactsameproblem** [comment]
Exact same problem here.
Didn't update anything, didn't change anything in the DB...But still I get this error asking me to remove the connection and set everything up again. Why?

> Facebook for WooCommerce is almost ready. To complete your configuration, complete the setup steps.

**Comment by dmitridr** [comment]
@exactsameproblem Very troubling. Do you remember the previous version you had before the upgrade?

My theory is something erased the FB settings from the DB. We used to have a bug like this in 1.2.5 and below. 

Do you have any other WooCommerce plugins installed? The problem used to happen when you would 'Save' the settings on another Woo plugin, it would erase the FB settings.

**Comment by pacificao** [comment]
When I click on the Get Started button I get routed to Facebook and the page says

“Sorry, something went wrong.
We are working on it and we'll get it fixed as soon as we can.”

It has been the same error for the last two days on a clean install, any ideas?

**Comment by dmitridr** [comment]
@pacificao Sounds like a different issue than the one in this thread. We'd need more info to figure that out:

- Which version are you using? 
- Was this your first time using the plugin?
- Could you send us some screenshots of what you are seeing?

We'd prefer if you open a new issue for this. Thanks!
My guess would be the window opened to the wrong URL. We used to have a bug in older versions around staticx appearing in the URL because of another plugin.

**Comment by dmitridr** [comment]
Found a fix for the original problem! 

The problem is [this line](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/facebook-commerce.php#L116). Because of this, if you save the settings of another WooCommerce plugin it will erase the settings of the FB plugin (ouch!). 

The fix is to use `woocommerce_update_options_integration_facebookcommerce` instead. Will issue a new release with the fix ASAP.

**Comment by dmitridr** [comment]
@nuclearape 
@NoviceWare 
@exactsameproblem 

Just released a new version, [v1.6.1](https://github.com/facebookincubator/facebook-for-woocommerce/releases/latest), should fix this issue permanently. Please re-open if it happens to you again on 1.6.1 or above.
