### ISSUE TITLE
Add to cart not firing 

### ISSUE THREAD

**Issue by veroak123** [facebookincubator/facebook-for-woocommerce#313]
I created product pages using my theme, instead of woocommerce's. The 'add to cart' is a link i created following this --> http://www.lankawebsites.com/blog/woocommerce-add-product-directly-cart-using-url-link/.

This is my product page: https://www.bambamboom.com/hedgehog-dino-black/ 

I don't want to use Facebook for woocommerce plugin bc it only pulls my 3 parent products and not the color variations - which are important to have for my retargeting ads. Also, i wanted to specify the product page to my own url, and not woocomemrce's default product page. Long story short, I created my own catalogue which is uploaded and working fine.

I'm a bit confused by something: On my events manager (FB) I can see my
FB custom conversions events, everything is firing. But when i go to the actual pages (cart, checkout and purchase confirmation), i dont see the pixel being triggered on the Pixel Helper Ext. 

I'm using a plugin called Pixel Cat for the integration. The ViewContent for product pages is working perfectly. Now... what's the diff between the events that i create on my Pixel plugin, vs the events that I created on my FB custom conversions?.... no idea.

I'm testing creating an event on PixelCat for AddtoCart... it fires, but with issues bc I think it thinks it's a product? no idea...
<img width="568" alt="screen shot 2018-03-06 at 11 53 53 am" src="https://user-images.githubusercontent.com/34290401/37054913-216c0f64-2135-11e8-976d-4c763d2681a6.png">
![screen shot 2018-03-06 at 11 54 57 am](https://user-images.githubusercontent.com/34290401/37054944-3e7ba88a-2135-11e8-905c-239eb0e061d1.png)

Any help would be much appreciated!! please!!! thank you

**Comment by jieminz22** [comment]
Hi,

Since you are not using our Facebook for Woocommerce plugin, we won't be able to help you on this matter...

**Comment by dmitridr** [comment]
Hi,

Weird that you say our plugin is only pulling your parent products? Our plugin should pull all variations for sure. 

Seems like you installed a pretty advanced plugin that allows you to configure your own types of events.

I guess [our developer docs](https://developers.facebook.com/docs/facebook-pixel/api-reference#events) could be helpful to you if you want to configure your own events or set up standard events. You'll have to make sure you configure the right events as the docs say you should if you want Dynamic Ads to work for you. 

As Jiemin said, we can't help too much here though, since we're not familiar with this other plugin.

**Comment by dmitridr** [comment]
#219 may also be helpful if you want to get AddToCart working.
