### ISSUE TITLE
Imported products do not sync : Incompatibility with extension WP All Import

### ISSUE THREAD

**Issue by jlev00** [facebookincubator/facebook-for-woocommerce#32]
Not expecting you to support every plugin out there but products imported via WP All Import never sync. Haven't tested with the new WooThemes import functionality yet.

**Comment by jlev00** [comment]
Updates via import (eg to stock levels, prices) also aren't synched.

**Comment by dmitridr** [comment]
We'll support it as a new feature if it's affecting enough people. A workaround here would be to force resync after using WP All Import.

**Comment by hut09032681** [comment]
I am having problems syncing my products from woocommerce to facebook as well. A few items there was no problem with but some, 5 hours later, are still 'processing'. I'm new to all this and can't find anything anywhere to 'reboot' the process so to speak. Any suggestions?

**Comment by dmitridr** [comment]
@hut09032681 There should be a button on the settings page titled 'Force Resync' which resyncs the products, is that not working for you? I recommend updating to 1.6.x as well, as the product upload has been improved upon significantly in newer versions.

**Comment by hut09032681** [comment]
@dmitridr I tried the 'Force Resync' and that didn't do anything. I tried deleting the products and readding them, that didn't work either. In the end I deleted the plugin thinking I'd try reinstalling it, and then I couldn't even find it to reinstall it, and still can't! The plugin's name is 'Facebook for WooCommerce' isn't it?!

**Comment by dmitridr** [comment]
@hut09032681 You can always find the latest version here as a zip file, which you can upload directly : https://github.com/facebookincubator/facebook-for-woocommerce/releases

Or at the woo-commerce website.

https://woocommerce.com/products/facebook/

**Comment by dmitridr** [comment]
Given that we're dealing with a high volume of bugs, we unfortunately won't get to this feature request to support WP All Import for a long time to come, even though we'd like to. However, we'd be happy to review any pull request to add this functionality, please consider sending us one!

**Comment by comarastaman** [comment]
I'm having the same issue. It's not with imported products though but all of my new products are not syncing. I've already deactivated, deleted and re-uploaded the extension and it's still having the same issue.

**Comment by mengyingdu** [comment]
Hi @comarastaman ,

Not sure whether your problem is the same as this issue and sorry for delayed response since this issue is old. Can you send us your store url or fb page? Are you using the newest version?

Thanks.

**Comment by joanesle** [comment]
Yes, I'm using the newest plugin version

The store url:
https://www.globeinteraction.com/art-shop/

Facebook page url:
https://www.facebook.com/globeinteraction/

**Comment by dmitridr** [comment]
Thank you, all, for the reports. We are prioritizing the performance of product sync for now, so it is unlikely we will get to this compatibility issue soon. However, as I said back in Oct, if you would like to send us a pull request to build an initial compatibility with `WP All Import`, we'd absolutely love to review it!

If your issue is not due to `WP All Import` please open a new one.

**Comment by dmitridr** [comment]
Working to add preliminary support for WP All Import for the next release.

**Comment by mengyingdu** [comment]
Hi @jlev00,

We added preliminary compatibility support for WP All Import in [v1.8.6](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.6).

Thanks.

**Comment by milosmili** [comment]
How we made our Shopify store becomes Instagram-shoppable-ready... We wrote this out of frustration due to lack of a detailed & clear Shopify & Instagram  support.

To our experience with iPhones, the shaky shaky marriage between those 2 work with iPhone5 and +. No, it will not work on iPhone4 or less (anyone still using those ??)

1. Create a FB business account (secret code: PITA: pain in the....) on FB

2. Using iPhone 5 +, log in to your Instagram account -> Options (gear) -> switch to Business Profile. And again, no, it will not work on your iPhone 4 or less.

3. In your Shopify store make sure you selected Instagram sales channel and all your products are added to it

IMPORTANT #1: You have to add all your products to the Shopify Facebook Sales Channel before and wait until your FB business page shop section process and make your products shoppable.

IMPORTANT #2: You can add only 1 product to cart on your Shopify-Business Facebook Shop. This is the FB limitation.

IMPORTANT #3: Your FB business page will have a URL like https://business.facebook.com/<yourpage name> anf NOT https://facebook.com/<your page name>.  And yes, your FB business page should be approved by FB.

4. Wait for at least 2 days for the Instagram approval...(might take longer if their support sleeps until 4 PM he he he)

5. Once you get confirmaton inside of your Shopify store -> upload some of your Web site product images form your site to your iPohne image libaray. I've been using a lot iCloud/images on my desktop PC: copy & paste from desktop to my iCloud images section instead of painfully trying to save using iPhone

6. Ha! 1st product to sell -> Sign to your Instagram account -> go to Options (gear) -> Select SHOPPING -> Products (no, you will NOT see your products listed, but don't panic....)

7. On your Instagram account home page, tap on SHOP - > tap to a product image from your iPhone photo library

NOTE: You may add multiple images from you smartphone image library to your Instagram-shoppable product before tag it

8. Go through unitl you are prompted to tag it -> so enter a tag

9. Select TAG A PRODUCT underneath the photo -> Select product from a list of available products

NOTE: you may wait up to several days unitl Instagram list all your products, trasfer can be that slow...

10. SEND -> verify if it is shoppable on your iphone : when you tap on it it should forward to your Shopify product's page

NOTE: Your product will be shoppoble on cell phones only! If you log in to your Instagram account on a desktop/laptop/Mac they won't be shoppable, just plain "old-fashioned" static Instagram images.

Check it our on your smartphone: https://www.instagram.com/freephonestuffnet/

Or visit: https://TopPhoneStuff.com

We certainly hope this will help someone!

Milos, Sandra, Gabriel, Alexander and many other hard-working gals & guys @ TopPhoneStuff.Com
