### ISSUE TITLE
Products are synced and visible in inventory but do not appear in shop

### ISSUE THREAD

**Issue by solebystyle** [facebookincubator/facebook-for-woocommerce#323]
No matter how what I cant get my products to show up in the shop. I deleted it because some products were incorrect and since I deleted the upload once, it never show the option to push the synced products into the shop. Also there is no info how to move products from inventory to shop either. I think my shop might be blacklisted for some reason.

**Comment by dmitridr** [comment]
Hello,

Could it be the same case as #281 ? The shop selector can default to off if you have an existing shop, it's easy to miss. I can also check if your shop is blacklisted if you link me to your page.

**Comment by brookescarborough** [comment]
Hello, I'm also experiencing this issue. I just installed the newest version of the plugin (1.7.11) and resynced my products. All 134 products show up in my product catalog in Facebook/products/catalog, but when I go to my page and click on the Shop tab, only 10 products show. Help??

**Comment by dmitridr** [comment]
Hello, @brookescarborough I hope you've resolved this by now, but if not please ensure you see the shop selector as described in #281 and toggle it to on during the initial setup. In order to redo the setup from scratch you'd have to go to `Reconfigure > Advanced Options > Delete` and then you can set up again. Hope that helps.

If you encounter further problems or bugs, feel free to file a new issue on us.
