### ISSUE TITLE
Can't change/delete pixel on website.

### ISSUE THREAD

**Issue by mkolotushkin** [facebookincubator/facebook-for-woocommerce#324]
Hello!
I have pixel on my website: https://clinchedflares.com, it worked with my personal ad account, but now I need to change pixel to my business account. If I try to delete setting, plugin tell me that something going wrong: 
<img width="448" alt="2018-03-12 13 50 45" src="https://user-images.githubusercontent.com/37293909/37279679-829bfdf0-25fc-11e8-839e-fedca2b109c7.png">

How change pixel code on my website correctly?

**Comment by dmitridr** [comment]
Hello,

Thanks for reporting this problem. Most likely it's an issue of not being able to delete because there's a problem with permissions on the pixel since it is now business owned. We will look into it.

Can you confirm the ID of the pixel, is it 1523810284401662 ?

**Comment by mkolotushkin** [comment]
Yes, it is 1523810284401662

**Comment by dmitridr** [comment]
Hello, looks like it's a permission issue because it seems you don't have the required permission to do the operation. There's 2 issues:

(1) I see you have an advertiser role on the page, but you need the permission of at least content creator in order to do a deletion. 
(2) The previous point may be enough, but if it still doesn't work, you may need to add yourself as an admin on the page directly, not through business, in order to perform this action. Hope that helps.

**Comment by dmitridr** [comment]
Closing this up. Please open a new issue on us if following these steps didn't resolve your problem.
