### ISSUE TITLE
Your API key is no longer valid. Please click "Re-configure Facebook Settings > Advanced Options > Update Token".

### ISSUE THREAD

**Issue by gervet** [facebookincubator/facebook-for-woocommerce#325]
For some reason since yesterday, I got those messages.

1. Your API key is no longer valid. Please click "Re-configure Facebook Settings > Advanced Options > Update Token".
2. We've detected that your Facebook Product Catalog is no longer valid. This may happen if it was deleted, or this may be a transient error. If this error persists please delete your settings via "Re-configure Facebook Settings > Advanced Settings > Delete Settings" and try setup again.

The catalog and shop page stopped synchronizing products.

Seeing this behavior, I deleted the plugin, reinstalled, deleted the info in the DDBB, reinstall again and still having the same problem.

My Pixel is 524596031224198

Please, can somebody help us with this? 

Thanks

**Comment by dmitridr** [comment]
Hello,

Thanks for writing in.

Can you think of anything you or someone working at your business did at the time you got this message? We have seen this happen for example, when there is a Business Permission change on the page.

The user who goes through set up needs to be an Administrator on the Page itself (not assigned via the business role). Could you check to see if that is the case in your scenario? If so, the resolution would be to add yourself as Administrator of the Page directly via the page interface. If not, can you send a link to your page and we can dig into what's going on?

**Comment by gervet** [comment]
Hi @dmitridr Thanks for your reply.

I hope you can help us.

We are having a lot of problem with this plugin. 
Basically, our sales are dying for all the problems we have related to advertising and this plugin.

Currently, my facebook user is an administrator in business manager, page, catalog, etc ... I am basically the only administrator in everything.

To try to fix all the errors, I have done the following.

1. I have assigned another user as an administrator to recreate the catalog.
2. The catalog has been created successfully with the other user, however, for some reason, the prices that show in the catalog and shop page are not the same with the prices we have on the website. Some prices show discounts that do not exist and others show the price without the discount that the product has on the website. It is totally weird.
3. On the other hand, in the catalog at the business manager, I do not get the catalog. I guess it's because I didn't create it with my user.

Our facebook page is http://grvet.net/2HAjGEX

Please, if you can help us with this, I'll appreciate it. It's quite urgent for us.

Thanks Dimitri

**Comment by gervet** [comment]
Hi @dmitridr 

Please, any help with this.

Please let me know.

Thanks

**Comment by dmitridr** [comment]
Hey @gervet 

Thanks for taking the time and trying different things, I can try to help figure out the problems you list. First let me ask, did the API token error go away, or is it still present? Since you seem to describe other problems now after uploading.

Let me also reply to your points:
(1) Did this fix the API problems?
(2) Could you give an example of the product which has the wrong price? A link to the product, plus a screenshot of the price on your WooCommerce edit product page would work.
(3) If you need the Catalog in your Business manager, you will need to attach it to your business manually. This can be done by going to www.facebook.com/products and selecting the product catalog created with WooCommerce.
(4) I am not sure if this is related to the plugin or not, so we may not be able to help with this. We can however file a bug on the team that owns this app if you can provide a screenshot with some details.

Hope that helps.

**Comment by dmitridr** [comment]
Closing this as it has been a while since there has been a reply, if the problem persists after doing a resync on the latest version v1.8.7 please open a new issue on us and reference this one.
