### ISSUE TITLE
Japanese characters in variations not working

### ISSUE THREAD

**Issue by jlev00** [facebookincubator/facebook-for-woocommerce#33]
That should read "200錠" and "50錠"

![image](https://user-images.githubusercontent.com/28719041/30245371-0ed1f21a-961b-11e7-8824-bb91cbe6ecf3.png)

**Comment by tahoff** [comment]
Thanks for reporting this issue. I have a few follow-up questions because I'm unable to reproduce this issue.
- What version of the extension are you using?
- Do you have any internationalization/translation extension which you've used to create the above strings?

This is what I get when I copy & paste the strings you listed above:
![screen shot 2017-09-11 at 1 21 58 pm](https://user-images.githubusercontent.com/6645131/30295238-c1724c92-96f4-11e7-9c9f-8165ddf33e9a.png)

**Comment by jlev00** [comment]
Hi Adam - thanks for taking a look at this.

v1.4.5

I'm pulling the strings into Woocommerce using another module (All WP Import Pro/Woocommerce) so that's definitely a possibility, although they appear fine in backend/frontend in Woocommerce, and in the database. 

Just to make sure, you created the variations in the Woocommerce backend? 

If you wanted to test whether the attribute name was affecting things you can copy-paste this: 
 
サイズ

Happy to help any way I can, and am open to the possibility that it's something odd with my setup. Let me know if you need links to specific products/etc.

**Comment by tahoff** [comment]
@jlev00 Thanks for reporting this issue! We've fixed the issue in [v1.6.0](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.6.0). Please download the new version and re-open the issue if the problem re-occurs. The new version should be available on the WooCommerce site next week.
