### ISSUE TITLE
Facebook extension error : Woocommerce

### ISSUE THREAD

**Issue by mybluepink** [facebookincubator/facebook-for-woocommerce#333]
![error](https://user-images.githubusercontent.com/37506089/37566262-cc7edb6a-2adc-11e8-8993-3cb5632cc03b.JPG)

Hi 
I  am getting the below mentioned error and as in screenshot while I try to syn products with my facebook page. I changed the password a few days back. I tried installing the plugin again by deleting the previous one but it didn't work. 
Facebook extension error: Facebook for WooCommerce
Error validating access token: The session has been invalidated because the user changed their password or Facebook has changed the session for security reasons.

Please help, how can I get to normal and sync my products again with fb shop

**Comment by dmitridr** [comment]
Hello,

If you go to the configuration page for the plugin (in the WooCommerce tab under `Integration`), you should see instructions about how to proceed, there's two ways.

(1) Launch the plugin via `Reconfigure` then go to `Advanced Options` and hit `Update Token`
(2) Reset the plugin entirely by going to `Reconfigure` then going to `Advanced Options` and hit `Delete`. Then complete set up again.

I recommend doing (1) as it will not affect your existing shop or ads.
Hope that helps.

**Comment by mybluepink** [comment]
![error1](https://user-images.githubusercontent.com/37506089/37639841-fda338d2-2c38-11e8-93cd-39f19fb4a113.JPG)
Hello,
I tried doing the (1) but I don't see any Update token button in Advanced Options. Please check screenshot and suggest accordingly.

Thanks in Advance

**Comment by mybluepink** [comment]
Hello,
I tried doing the (1) but I don't see any Update token button in Advanced
Options. Please check screenshot and suggest accordingly.

Thanks in Advance

**Comment by mengyingdu** [comment]
Hi @mybluepink ,

I think your have another problem besides the password change: there should be a pixel name in this pop up window under 'facebook pixel' section.  I can't repo your issue in my demo sever. 
Suggestion:
1. quick workaround: (but you need to re-create your Ads)
delete your settings -> set-up -> sync
2. more time to troubleshooting
1) can you check  your db whether your pixel id is still there? (you can query by sql search option_name like '%facebook%')
If it's not there, you need to delete and re-setup
It it's there, and you really want to keep your Ads running, can  you try to set your credential (wooCommerce) to [here](ads_extension_woocommerce@fb.com) ? 

I would suggestion option 1 since we can't guarantee the timeline to help you out by back-forth email support. But we can try..

Thanks.
