### ISSUE TITLE
Product partially synced 

### ISSUE THREAD

**Issue by Danielriott** [facebookincubator/facebook-for-woocommerce#337]
Hi.

I am having some issues with my view content pixel. its turning yellow and says "can't matchproducts"  , but as i'm using this plugin it should have no problem to match the products i would say.

I attached and image of the pixel error.
![udklib](https://user-images.githubusercontent.com/37449380/37769750-4eb493f2-2dd2-11e8-8382-4c131570985d.JPG)

**Comment by coccoinomane** [comment]
Hi!
I was having the same issue after my first product sync.
The warning disappeared by itself after one day.
Guido

**Comment by Danielriott** [comment]
Okay. I have had the problem for about a week now.
But it used to work :)

**Comment by sammul** [comment]
@Danielriott can you share a url example?

**Comment by Danielriott** [comment]
www.riott.dk

**Comment by sammul** [comment]
@Danielriott can you click force-sync? Looks some of the products are not uploaded to facebook.

https://www.facebook.com/products/catalogs/190641568332440/products
This is the product catalog UI you can use.

https://riott.dk/produkt/strik-pullover-i-raat-look/?attribute_pa_farve=farve-hvid&attribute_pa_stoerrelse-1=stoerrelse-l
This one is firing correctly

**Comment by sammul** [comment]
@Danielriott after the resync the issue is still there?

**Comment by Danielriott** [comment]
Yep :/

**Comment by mengyingdu** [comment]
Hi @Danielriott ,

We fix viewContent in v1.8.5 and the [commit](https://github.com/facebookincubator/facebook-for-woocommerce/commit/dbf7a40683bdc358f0f08664f48551ab26c10487) is here. 

I have checked your catalog with product has this problem and I confirm the product_group_id is the wrong/old one before that fix.

The reason why you suffer from this unmatch is because the product group (since this is a variable product) still use the old id to match.  I would suggest you follow these steps:

go to your woo setting tab --> integration --> facebook-for-woocommerce
re-config
in pop-up window: advanced option -> delete settings
when it completes, go back to your integration's tab, refresh
in the blue window of 'facebook-for-woocommerce' --> 'get started'

I'm 80% sure this can fix your problem. Sorry for delayed response.

Thanks.

FYI @dmitridr, it seems force-resync can't update the product_group_id in this case. This user is on v1.8.5 but not sync from scratch still have this problem.

**Comment by Dedagroup** [comment]
Yep.. it looks like it solved the problem after i updated to 1.8.6 and re-synced :)
Thanks for your help.

**Comment by mengyingdu** [comment]
Glad to hear I could help @Dedagroup!

If you like **Facebook-for-WooCommerce**  please leave us a [*****](https://woocommerce.com/products/facebook/) rating. A huge thanks in advance!
