### ISSUE TITLE
Products are synced to Facebook but All products not showing at Facebook shop!

### ISSUE THREAD

**Issue by jyotibiswas** [facebookincubator/facebook-for-woocommerce#349]
Hi,

I have 403 products in woocommerce website.
I am using facebook-for-woocommerce plugin to import the products in facebook shop from woocommerce website.

after complete configuration it shows  Status: Products are synced to Facebook.
but only 107 product available at facebook shop out of 403 products. Its only about 25% showing at facebook shop.

**Comment by mengyingdu** [comment]
Hi @jyotibiswas,

Can you follow the 'support' section of readme and give us more information when you open an issue?

Thanks!

**Comment by mengyingdu** [comment]
This is fixed.

**Comment by mengyingdu** [comment]
Hi @jyotibiswas  ,

Can you check your shop now? I add the support to show a product item in a group and landed yesterday. We have limit for the # of products to show up in the shop section due to page loading performance concern. 
Also, we have released new version [v1.8.3](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.3) which have many fixes and new feature. Can you check there and upgrade? If you want to have the full version of the new features (mostly about default variant), you need to delete your settings and re-setup.

Thanks.
