### ISSUE TITLE
cannot integrate my page by facebook for woocommerce

### ISSUE THREAD

**Issue by khlam107** [facebookincubator/facebook-for-woocommerce#36]
everything was set, but cannot integrate at the last step...

![error](https://user-images.githubusercontent.com/31948034/30413781-c8fca6e6-9952-11e7-9b2b-ad8aff948e61.jpg)

Please help...

**Comment by dmitridr** [comment]
Looks like the reason you couldn't finish is that your website is blocked by our spam filters. We've started an internal investigation into why, but you may find it helpful to submit a report here to try to get it unblocked:

https://www.facebook.com/help/contact/244560538958131

**Comment by dmitridr** [comment]
So I have some good news and some bad news here.

Good News : We've changed the error message to be more descriptive, so you can try again and you should see an error message regarding your website and how to resolve the block.

Bad News : *.000webhost.com is blocked on Facebook due to a large volume of spam coming from these domains. In order to get an individual exception, you would have to use the form in my previous comment, though I recommend switching hosting providers, if at all possible.
