### ISSUE TITLE
 Missing "AddToCart, Purchase, ViewContent" events in Pixel

### ISSUE THREAD

**Issue by jaredkotoff** [facebookincubator/facebook-for-woocommerce#369]
Website: https://www.updownleftdie.com/shop
FB Page: https://www.facebook.com/UpDownLeftDie/shop

Using Facebook Pixel Helper i can see these events firing but the catalog is saying they're missing.
I'm confused because I see the events in the Pixel but the catalog says it's not seeing them:
![screen shot 2018-04-02 at 11 23 26 am](https://user-images.githubusercontent.com/3268576/38209208-6e4c1c78-3668-11e8-8928-4a4a25af3996.png)
![screen shot 2018-04-02 at 11 22 45 am](https://user-images.githubusercontent.com/3268576/38209210-6ff30b22-3668-11e8-98f8-509186d875ec.png)

I'm new to this but it seems like a bug to me. If not could someone point me in the right direction?

I also have the problem where my Shop on our FB page is forever processing. I'm not sure if it's because of this or not.

**Comment by jaredkotoff** [comment]
Deleted and resynced Woocommerce plugin, down to only missing `Purchase` event and `Processing`on 3 items in the shop tab on FB are taking a very long time.

**Comment by jieminz22** [comment]
Hi @jaredkotoff,

Good to know that the other events are firing after you reset. "only missing Purchase event" - do you mean you had a purchase event on your site but it's not firing? 

In terms of shop processing, we are currently experiencing problems on shop processing and we have engineers looking into it right now. Sorry for the inconvenience! We will update you once we have it fixed.

**Comment by jaredkotoff** [comment]
Hey @jieminz22,
yea,  I've manually made purchases and checked looked at Facebook Pixel Helper to see it with a green check the Purchase event for that product. I'm hoping it simply takes a reaaaaallllyyy long time for these events to be seen in the catalog (~24hr??).

That's pretty frustrating since it doesn't even tell you that. I've been trying to get our store to open for over a week now with most of the time with all times processed

**Comment by dmitridr** [comment]
Hey, 

Jumping into say the Shop issue has been fixed, looks like your shop is visible now!

Regarding your other concerns I can maybe offer a bit of help : about the events not appearing, do you have the `Google Enhanced E-Commerce` plugin installed? There is one open issue about that #329. And there are some other related issues where you may be able to find help from people who had the same problem. 

Generally, if you see it fire with the Pixel Helper tool, it should be working. 
There's another related issue #242 I think? Basically the `Advanced Matching` option in the pixel is causing reduced reporting due to privacy issues. You can disable `Advanced Matching` via `Reconfigure > Pixel > Advanced Matching (off) > Save`. 

Anyway, hope that helps!

**Comment by jaredkotoff** [comment]
Fixed: https://github.com/facebookincubator/facebook-for-woocommerce/issues/366#issuecomment-378825000
