### ISSUE TITLE
Your Shop is Being Processed - Same Issue

### ISSUE THREAD

**Issue by unslse** [facebookincubator/facebook-for-woocommerce#370]
Hello,

Same issue here as many others who have also commented. Have been stuck on "Your Shop is Being Processed" for almost a week now. Quite frustrating.

Hopefully it'll be fixed soon!? Anyone know **why** this is happening? Something to do with Facebook or is it this plugin? My products have all synced perfectly from the website store to the Fb page...

**Comment by dmitridr** [comment]
Hello,

I have some good news here, we've identified the problem (it was a problem in our review system) and we have a fix for newly created shops going live in a few hours. We plan to fix all the shops that are having this problem tomorrow. Will update more when we've fixed everything. Thanks for your patience!

**Comment by unslse** [comment]
Hi,

Thanks for the update @dmitridr ! Really great news! Please do let me know when you have the fix available and what we should do to get it installed on our end.

**Comment by dmitridr** [comment]
Hey again,

Happy to say that we flat out fixed the problem for 95% of shops created in the past, so with luck your shop should be live now.

If you're in the 5% we could not fix, try the following, first wait ~2-3 hours (it may still be in the review system because people are reviewing it). If it's still not working, reset the plugin using `Reconfigure > Advanced Options > Delete` then wait 48 hours, the shop should be processed correctly.

If that *still* does not work, which is very unlikely, please let us know by opening a new issue. That said, most likely everything is working for you now!

**Comment by unslse** [comment]
Thank you, it's working 100% now! Much appreciated!
