### ISSUE TITLE
Problem connecting

### ISSUE THREAD

**Issue by pederwuth** [facebookincubator/facebook-for-woocommerce#372]
Hi 

I run the setup on a site on a multisite installation, and i get:

Check that you're logged into your store. You can close this window and reopen the plugin from inside your store's admin panel.

What am I doing wrongP

Peder

**Comment by jieminz22** [comment]
Hi, 

Generally, unable to connect happens if you close the parent window, or navigate to another location. This disrupts the communication between the popup and your woo store. If you keep both the configuration window (the window that says Grow your business on Facebook and there's some text and a button) and the popup open, it should generally work.

However, we did get a similar report before (https://github.com/facebookincubator/facebook-for-woocommerce/issues/330) with multisite as well. If you continue seeing this error, let us know with a bit more details on multisite installation. We are not familiar with it. Thanks.

**Comment by dmitridr** [comment]
Closing as there has not been a reply in a while. Feel free to open a new issue if the problem persists.
