### ISSUE TITLE
Can I add the vendor name to the product meta in facebook and have one default image for all my products in facebook

### ISSUE THREAD

**Issue by RamiSadi** [facebookincubator/facebook-for-woocommerce#373]
1)I use a multivendor marketplace plugin called "wc marketplace" , I need to synchronize the vendor name to the products in my facebook page to be displayed above the product image (or right below), 
Here is the code where  "wc marketplace" adds the vendor name in their plugin:
`  /**

     * Add Sold by Vendor text

     *

     * @return void 

     */

    public function wcmp_after_add_to_cart_form() {

        global $post;

        if ('Enable' === get_wcmp_vendor_settings('sold_by_catalog', 'general') && apply_filters('wcmp_sold_by_text_after_products_shop_page', true, $post->ID)) {

            $vendor = get_wcmp_product_vendors($post->ID);

            if ($vendor) {

                $sold_by_text = apply_filters('wcmp_sold_by_text', __('Sold By', 'dc-woocommerce-multi-vendor'), $post->ID);

                echo '<a class="by-vendor-name-link" style="display: block;" href="' . $vendor->permalink . '">' . $sold_by_text . ' ' . $vendor->user_data->display_name . '</a>';

                do_action('after_sold_by_text_shop_page', $vendor);

            }

        }

    }

    /**

     * Save sold by text in database

     *

     * @param item_id, cart_item

     * @return void 

     */`
Where I can add this code to import the vendor name to facebook products?

2) My products are all of appointable type, so I hided the product image in the single product page in my site and have put a custom placeholder image for all the products to be displayed in the shop page, but in facebook the placeholder isn't synchronized and the products look so ugly without any image, so I am thinking of two solutions, The first to have a default product image in facebook, and the second is to display the vendor image from his profile to be the product image.
Is that possible? can I get some hints?
Thanks.

**Comment by dmitridr** [comment]
Hello,

1) Sounds like you will want to append the vendor name to the title, or list it in the description. 
You can use the filter hook `facebook_for_woocommerce_integration_prepare_product` [here](https://github.com/facebookincubator/facebook-for-woocommerce/blob/v1.8.3/includes/fbproduct.php#L479) in order to modify the product data to add the vendor name. It will probably be similar to the code you posted but will need some modification.

2) This can be solved in the same way as 1). You can add one or two lines in the code to change the image_url field in `$product_data` to the default product image you want to use using the filter. If you have a programmatic way to get the vendor image url as the image, you can also display that as well.

If you need more code pointers let me know. There should be some closed issues that have code on how to use this hook. #176 and #241 I think? Hope that helps.

**Comment by RamiSadi** [comment]
Thank you @dmitridr for the directions, 
1. I tried the following:

```
add_filter( 'facebook_for_woocommerce_integration_prepare_product', 'product_vendor_name' );
function product_vendor_name($product_data){
  global $post;
     if ('Enable' === get_wcmp_vendor_settings('sold_by_catalog', 'general') && apply_filters('wcmp_sold_by_text_after_products_shop_page', true, $post->ID)) {

          $vendor = get_wcmp_product_vendors($post->ID);
          $vendor_name = $vendor->user_data->display_name;
		   if (!empty ($vendor_name)) {
			   $vendor_name= 'Katateeb';
		   }
		   return $vendor_name;
          $product_data['name'] = $vendor_name . $product_data['name'];
          return $product_data;
		  }
}
```
But, didn't work, Is there anything missing here?

2. For the image , I used this:
```
add_filter( 'facebook_for_woocommerce_integration_prepare_product', 'product_custom_image' );
function product_custom_image($product_data){
         $product_data['image_url'] = 'my default image url ';
  return $product_data;
}
```
And it worked perfectly, Now I will manipulate it to add a condition: If the product has no image then add this one.

Thanks.

**Comment by dmitridr** [comment]
Hello,

Sorry for the delay in getting back to you. To say we are swamped would be an understatement.
I'm glad (2) worked for you.

For (1), perhaps you have figured this out by now! But from what I can see the problem is the line `return $vendor_name;` which is likely causing the program to return before the `$product_data['name']` can be changed. Hope that helps!
