### ISSUE TITLE
v1.8.4 can not receive ViewCatagory Pixel 

### ISSUE THREAD

**Issue by nguyenanh17** [facebookincubator/facebook-for-woocommerce#381]
Dear All,
In the past, I used v1.6.5 and all facebook pixel was actived.
Now I update to  v1.8.4 although you fix "Fire AddToCart on Cart Viewed for shops which redirect to cart.
" already but "ViewCatagory Pixcel" can not be actived as v1.6.5.
Please review and fix it.
Thank you much

**Comment by dmitridr** [comment]
@nguyenanh17 It's working for us on our test servers. As @sammul said, can you give us a URL to check on your site? We may be able to figure out why it's not working for you by looking at your site.

**Comment by dmitridr** [comment]
Closing as it has been months since a reply and we'd need more info to address this. 
I would not worry about `ViewCategory`, facebook has deprecated it anyway (it's not a Standard Event anymore) and we may just remove it in the future versions of the plugin. It should not affect you unless you are specifically constructing custom audiences based on `ViewCategory`.
