### ISSUE TITLE
Out-dated Error message: products checkout URL different than shop checkout URL

### ISSUE THREAD

**Issue by artbyankitaraut** [facebookincubator/facebook-for-woocommerce#384]
I am getting this error message on my wordpress dashboard. 
"One or more of your products is using a checkout URL that may be different than your shop checkout URL. Re-sync your products to update checkout URLs on Facebook."

syncing is going fine. but i keep on getting this error message. why? what should i do?

**Comment by sammul** [comment]
@artbyankitaraut can you attach a screenshot of this warning? How do you make sure the warning comes from our extension?

**Comment by artbyankitaraut** [comment]
screenshot:  https://d.pr/i/K9pBQP

**Comment by sammul** [comment]
@artbyankitaraut Thanks, I just checked with our team. It's an out-dated warning message. We will remove it in next version. Please ignore it for now.

**Comment by dmitridr** [comment]
Yeah I just double checked, the warning is correct, you should re-sync after you see it, the problem is the warning doesn't go away, that's the bug. I fixed it in [my commit just now](https://github.com/facebookincubator/facebook-for-woocommerce/commit/e5019a29ab79d629251539285fe6aa0083ee818d) which should be live in v1.8.5 when that comes out.

**Comment by sammul** [comment]
FYI @artbyankitaraut 1.8.5 is live. Can you try it and tell how if it fixes your issue?

**Comment by artbyankitaraut** [comment]
I currently dont see any errors or messages right now.

**Comment by francescosche** [comment]
Hi!
I see the error right now.. How can I fix it? :(
