### ISSUE TITLE
Plugin generates descriptions on previewing, not publishing

### ISSUE THREAD

**Issue by aand01** [facebookincubator/facebook-for-woocommerce#386]
I've noticed descriptions that were only present during previewing being used as the official product descriptions. Please only parse descriptions once the product is published (this is when the content is ready to be presented to the world)

**Comment by sammul** [comment]
Thanks for the feedback. Is there a way we can reproduce the issue you described?

**Comment by aand01** [comment]
@sammul, I've yet to double check it here, but my guess would be the following approach:

1. Create a new product in Woocommerce
2. Enter some random data in the description field, say, 'preview text'
3. Press Preview in Woocommerce to see an example of the product
5. Change the description text to say 'final text' and publish the product
6. See what the description says in the Facebook store - it should say 'final text'. If not, it's using the text from the preview.

**Comment by dmitridr** [comment]
@aand01 I tried those repro steps, but after step 5, the text says 'final text' on FB. So if you can confirm that those steps cause a problem for you maybe it's because of some changes that are specific to your server?

I guess if you were running a `Force Resync` at the same time that you previewed a description, it is possible that one of the products would sync using the preview description, but I can't think of any other case of this happening, unless you are using a really old version of our plugin. Could you confirm you are on 1.8.x or above?

**Comment by aand01** [comment]
@dmitridr thanks, I can't reproduce this issue here either - will let you know if I come across it again.
