### ISSUE TITLE
Different products, same facebook ID

### ISSUE THREAD

**Issue by SandraHG** [facebookincubator/facebook-for-woocommerce#391]
I have a wordpress website with this plugin, version 1.6.0.
I have a lot of products, some of them are showing on Facebook, some aren't.
For example, the same shoe in four colours is only in one colour visible in tagging in Facebook. 
Now it seems, all colours (with different slugs, different product descriptions etc!) are having the same facebook ID. 
How do I solve this problem? Any suggestions? I would like to see all the available colours on tagging in Facebook..... 

Thanks for helping me out!

**Comment by dmitridr** [comment]
Hello, 

Sorry for the delay in getting to you. I do have a suggestion, please upgrade, version 1.6.0 is ancient I think it is from 2017? There are hundreds of bugs we have fixed since then, this seems like it could be one of them. 

After upgrading to our [latest version v1.8.4](https://github.com/facebookincubator/facebook-for-woocommerce/releases/latest), if the problem persists please do a full reset via `Reconfigure -> Advanced Options ->  Delete` on the plugin page, this should fix the problem!

**Comment by dmitridr** [comment]
Closing this out, if the problem persists please open a new issue on us and reference this one.
