### ISSUE TITLE
#200 Permissions error when syncing new product : Business Manager Issue

### ISSUE THREAD

**Issue by Chris-HHH** [facebookincubator/facebook-for-woocommerce#398]
When I am updating a  new product I get this message and it won't sync

![image](https://user-images.githubusercontent.com/28512934/38648450-1fb2a2de-3de9-11e8-9731-fda6a4a85a7f.png)

I have just updated FB for WC to Version 1.8.3  I have WC Version 3.3.5
website  https://cotswoldgoodies.com

**Comment by Chris-HHH** [comment]
Tried rolling back the update, still the same. I might have updated WC at the same time?

**Comment by patiohq** [comment]
I've had the same issue ever since I updated to WC 3.3.4 a few days ago. I won't update to version 3.3.5 for at least a few more weeks. I'm thinking about getting a different plugin for this.

**Comment by Chris-HHH** [comment]
Getting this as well:
![image](https://user-images.githubusercontent.com/28512934/38652449-f1959e5a-3dfd-11e8-8d97-ceb82b016530.png)

The only other thing I've changed is moving FB pages from Ads Manager to Business Manager???
Might this affect things?

**Comment by Chris-HHH** [comment]
The only other thing I've changed is moving FB Pages from Ads Manager to Business Manager.  Could this affect things?

Also get this:
![image](https://user-images.githubusercontent.com/28512934/38652640-c8bb51ae-3dfe-11e8-9505-9d36d5a63c30.png)

**Comment by patiohq** [comment]
Change it back. I had the same issue and I also just changed my admin roles to the existing page and now the 200 permission error is gone. The business manager is the most convoluted mess that I've even seen. Google Adwords is so much easier to use. I'm still learning this but will figure it out eventually.

**Comment by dmitridr** [comment]
Hi all,

@patiohq I think you nailed the problem here, it's partly due to business manager. The permission error usually means that your API token (which the plugin generates) no longer has access to the page. This can happen if you are removed as an Admin from the page and instead get a 'role' on the business. The role is not generally enough, you have to be an actual admin of the page. 

I think some others have gotten it to work with business manager, so it should be possible to configure it correctly, but I agree with the convoluted mess part, it's difficult to figure out how. 

There are some open and closed issues which are related to the business manager setup. I'll see if I can find them and list them here.

**Comment by Chris-HHH** [comment]
Changing admin roles fixed it on one page. The other page now creates this error when updating a product. 
![image](https://user-images.githubusercontent.com/28512934/38703198-76fca3bc-3e9a-11e8-9771-0eef13123498.png)

**Comment by Chris-HHH** [comment]
@dmitridr  No more error messages thanks
