### ISSUE TITLE
Allow multiple product purchase on Facebook Page or option to disable add to cart URL

### ISSUE THREAD

**Issue by dougaitken** [facebookincubator/facebook-for-woocommerce#4]
Customer is looking to sell products on their Facebook page but is wanting to not have the redirect to checkout

> Is there any way we can amend this to send the customer to the product page rather than straight to checkout please ?

Would this be possible in a future release to have settings to change the `Check Out on Website` button / link to either "Continue shopping" or "Browse more on our site" or similar?

**Comment by dmitridr** [comment]
@dougaitken Thanks for reporting this. We've added a feature within shops settings that allows the behavior in question.

If the user navigates to the shops menu and clicks on the gear icon in the top right, and then clicks 'Settings' in the dropdown they should land on a page where they can control the behavior of the "Check out on Website" button using a toggle. Setting the toggle to off will link the button to the page of the product instead of straight to the checkout.

Let us know if you need additional details, but this should fix your issue.

**Comment by helgatheviking** [comment]
@dmitridr I have the same issue with my Name Your Price plugin. Please see my proposed enhancement described here: https://github.com/facebookincubator/facebook-for-woocommerce/issues/145#issuecomment-562205067
