### ISSUE TITLE
Facebook for WooCommerce not displaying images on Facebook Shop

### ISSUE THREAD

**Issue by LouDivine** [facebookincubator/facebook-for-woocommerce#407]
I installed the plugin last week and after trying to use the Parent image after no images were being pulled through, this still isn't displaying any images at all.

I tried creating a new product with a different style of product image and that didn't work either. I know I am using ACF for some images, but I thought it would at least display the default Product Image?

FB Shop link: https://www.facebook.com/pg/ragingbullandcheekycow/shop/?ref=page_internal

**Comment by sammul** [comment]
Hi @LouDivine . I did verify the issue you are seeing on your website and your shop. Do you use any extension for the products?

**Comment by LouDivine** [comment]
Hello @sammul 
We aren't using any extensions for the products, just WooCommerce. What paths does the plugin use?

**Comment by dmitridr** [comment]
Hey, 

It may be helpful to search our existing issues, we have had issues like this in the past #182 and some others, I think. 

In your case, I checked a couple of products, and it seems `/site/` is duplicated in the url. I don't know why, but as @sammul said maybe due to some other extension.

For example the plugin thinks: `https://ragingbullandcheekycow.com.au/site/site/wp-content/uploads/2018/01/lets-wick-it-on-candle.png` is the url for one of your images, but the correct url is actually `https://ragingbullandcheekycow.com.au/site/wp-content/uploads/2018/01/lets-wick-it-on-candle.png`

Because most people do not have this issue (first time I've seen it), it's likely due to some customization you have on your side. You can hook in to our plugin's product filter and add some extra code using the filter to remove the extra `/site/` being added. Can give more details on that if you want.

**Comment by LouDivine** [comment]
Thanks for the quick reply. If you could please give us details on how to hook the plugins product filter to add the extra code to remove the extra /site/ that would be great.

**Comment by reddatos** [comment]
I'm using a plugin to get the product images from another of my websites which I'm using as a CDN "https://mycdn.mywebsite.com/CDN/image1.jpg". The plugin has changed the native url from ../upload/.. to the one above. I've tried to customize the code using the following one but it doesn't work:

`add_filter( 'facebook_for_woocommerce_integration_prepare_product', 'wc_fb_square_image_fix', 10, 2);
function wc_fb_square_image_fix($product, $id){
  $product['image_url'] = str_replace('https://mycdn.mywebsite.com/CDN/', 'https://mycdn.mywebsite.com/CDN/', $product['image_url']);
  return $product;
}`

What am I doing wrong? Any advise would be appreciated. Have a great day.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
