### ISSUE TITLE
I can not integrate Woocommerce with Facebook

### ISSUE THREAD

**Issue by cjmoyano** [facebookincubator/facebook-for-woocommerce#41]
I can not continue to the next step (see image)

![foxfacebookwoo](https://user-images.githubusercontent.com/32074699/30557845-f45c4266-9c85-11e7-99df-8d5db2cbbe0a.jpg)

I followed the instructions and created the Facebook Pixel (see next image) in the correct advertising account. I try again and continue showing the previous message. The message says "Once you create your pixel, you can restart this plugin and install it on your site in this step.", But this never happens. It happens again and again.
I deleted the cache, cookies, etc. Anyway, I can not make it work.

![pixelfacebookfox](https://user-images.githubusercontent.com/32074699/30558066-a28fe324-9c86-11e7-8f0e-fd699efcbac7.jpg)

TIA

**Comment by dmitridr** [comment]
Hello, 

We are investigating this issue, it appears to affect you because you are creating the pixel within a business but the pixel (348176415610999) has no associated ad account. When you create the pixel, you should assign it to an ad account, and it should be an ad account that you are an administrator of. Let us know if this fixes the problem.

**Comment by cjmoyano** [comment]
Thank you very much, Dmitri.
That was the solution!!! I assigned the pixel to an ad account and it worked correctly.
Thanks again.
