### ISSUE TITLE
How to set gender/brand etc. in woocommerce to fetch this in Facebook catalog?

### ISSUE THREAD

**Issue by aromefraise** [facebookincubator/facebook-for-woocommerce#412]
Hi!
We have a Woocommerce store with clothing-products and use the Facebook-integration to create our Facebook-catalog.
My problem is that, when I try to create product-sets with clothes for men only, or women only (gender) etc. It can't fetch the gender. It is blank. The same goes for category, brand, etc.. How can I fill in these blanks so the Facebook-catalog can fetch the data and I can create specific product-sets? 
Some data however gets fetched like; Name, description and price

Anyone who can help?  
Thank you

**Comment by sammul** [comment]
Please attach your catalog id, facebook page url and website url please

**Comment by aromefraise** [comment]
Catalog id: 118800905489197
Facebook page: https://www.facebook.com/grontskift
Website: https://www.grontskift.no

**Comment by sammul** [comment]
@aromefraise I saw you are using super old version(1.4.1). Do you have issues with latest version?

**Comment by sammul** [comment]
@aromefraise You can try to set gender here: https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/includes/fbproductfeed.php#L238 (the feed approach is relatively new)
Since you are using an very old version, this code should be more relevant: https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/includes/fbproduct.php#L438

**Comment by sammul** [comment]
@aromefraise if you are not familiar with coding, I suggest you to try the latest plug-in version. We have some code trying to set gender onto the products

**Comment by aromefraise** [comment]
We have now updated our plugin, but still fail to see gender or even brand in our catalogues.
Where in the Woocommerce-shop do I fill in gender? 
And brand is set on product level in WP, but the only brand Facebook is fetching is our store name "grønt skift"?

**Comment by sammul** [comment]
Hi @aromefraise w'd like to know how do you set up the categories(male/female) on woo commerce? We create the products based on the variants they have.

**Comment by sammul** [comment]
@ttjs82 We do try to set brand and category etc(https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/includes/fbproductfeed.php#L238). So it would be helpful if you show us how do you set those variants on woo commerce so that we can try the set up same as yours and develop based on that.

**Comment by sammul** [comment]
@ttjs82 Thanks for sharing the tips, and I forwarded this to the eng team. The incompatibility with brands plugin is an known issue. If want to try, you try replace this line https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/includes/fbproductfeed.php#L244

**Comment by mengyingdu** [comment]
Hi @aromefraise ,

Can you explain how you create product sets with gender? Did you use other plugins besides Woocommerce Brands?

Thanks.

**Comment by mengyingdu** [comment]
Hi @aromefraise ,

We will support brand extension in next release so it should fetch brand in catalog when you set it by that extension.

In terms of gender, you can add gender as attribute and create variable products with gender as one variation. This woo [doc](https://datafeedrapi.helpscoutdocs.com/article/155-add-gender-as-product-attribute) should help.

If you use other plugins to set up gender term, I need more information. 

Thanks.

**Comment by mengyingdu** [comment]
Hi @aromefraise ,

[v1.8.6](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.6) is alive now. To take advantage of the new version, you need to re-sync your products.

Thanks.

**Comment by deathinjune** [comment]
Hi there!

I seem to be experiencing the same issue, with my Facebook-for-WooCommerce running on the latest version. We do not use a separate plugin to assign brand names or gender to our products, however, I can see that Facebook-for-WooCommerce is recognising these categories and attributes in the UI under Product Filters and Improved Variable Product Attributes. So, I guess I'm half-way there, but I do not know how to properly activate them so that they become available as filters in Facebook Catalog Manager. 

Could someone please have a look at our catalog and see if this is possible? Our website runs on a custom theme which I cannot edit so if there's a way to do it through the UI that would be great!

Thanks in advance!

KR,
Daniel

**Comment by wulaaf** [comment]
I have the same issue as Daniel. Brand and color are not showing up in Product Catalog.
