### ISSUE TITLE
Deleted Product Catalog on Facebook

### ISSUE THREAD

**Issue by hamutalwz** [facebookincubator/facebook-for-woocommerce#413]
While trying to work through some issues I was having with this plugin, I have deleted the product catalog from my Facebook page and now I'm getting an error message from the plugin saying: "We've detected that your Facebook Product Catalog is no longer valid. This may happen if it was deleted." and I'm instructed to 'Delete Settings' and the  'Re-configure Facebook' it again.
I am trying to do just that but I keep getting an error message saying: "Your Access Token Has Expired", asking me to update the token and then refresh the page.
After doing so I get a message saying: "Your API key has been updated. Please refresh the page." and once I do I am getting the original error message again: "Your API key is no longer valid. Please click "Re-configure Facebook Settings > Advanced Options > Update Token"."

I cannot seem to get the plugin to work again.

**Comment by sammul** [comment]
@hamutalwz Have you tried to delete everything in advanced options and re-do a setup?

**Comment by hamutalwz** [comment]
I did.

**Comment by hamutalwz** [comment]
After many attempts to fix this issue, I finally solved it by manipulating the 'woocommerce_facebookcommerce_settings' entry in wp_options table, directly to the DB.
So this problem is now fixed but now I'm having a residual problem: I keep getting an error message in my Facebook business page: Your shop is currently disabled. Turn on selling on Facebook for your catalog to make your shop visible to people who visit your Page."
So far I am unable to fix this problem.
Any thoughts?
Thanks.

**Comment by sammul** [comment]
I'm asking my teammate about the cause for the error.

@hamutalwz how many catalogs there are if you go to www.facebook.com/products ? I can see a lot of catalogs created during your attempts. Did you try to delete them?

**Comment by hamutalwz** [comment]
I have only 1 catalog at the moment.
I don't know where you're seeing many others but if they were created during my many attempts, they were deleted automatically by the plugin. I did try to create a catalog manually and later I deleted it.

**Comment by hamutalwz** [comment]
It seems there was no other way but to create a new Facebook business page!
Luckily I did not have too much going on there so far, otherwise it would have been catastrophic.
Given all that has happened, I cannot recommend using this plugin. If you can avoid it, do!

**Comment by dmitridr** [comment]
Sorry to hear you have had this problem and apologies for not following up quickly. There was a lot of internal chaos, teams being disbanded, people falling ill, going into surgery, that caused lapses in support.

Deleting the catalog (from Catalog Manager) is generally not a good idea as it can cause significant issues in the plugin setup and the shop itself. The shop you mentioned I recognize from another issue,  so if you are still trying our plugin, I would recommend the resolution I proposed there, of downgrading while we figure out where the problem is. Hope that helps.

**Comment by LoloSolo** [comment]
We also had this problem. The plugin was so buggy and products were appearing in the shop as blank images, so we removed the plugin, but the Catalog was still in place and prevented us from adding / editing the Shop. I found by going into the Catalog, I had to delete all products first, then delete the feed, and remove the pixel from the Catalog in order to delete the Catalog itself. Once the Catalog was removed, it wiped out everything from the shop, but at least we had control of the shop again and could add/edit items as needed.

**Comment by sageg90** [comment]
for delete catalog its easy just enter to the catalog from business manager and after u have to enter to the catalog wich you wan to delet and after choose setting and delet it from menu

**Comment by nikolaymartinov** [comment]
Hello,
I have the following issue and I hope someone could help me:
As my facebook catalog wasn't been updating properly and some missing products were still being visible in the catalog - I decided to delete the current catalog and set a new one. The problem is that my previous catalog was doing great when advertising (CTR link-click was 5% for over 6 months) and my new one is not doing good at all. Absolutely the same parameters of the two ads, only the catalog is updated but I am still selling the same kind of things. I can't understand why it is happening.
My question is if anybody knows hot to recover my deleted catalog? I know that maybe it is not possible but I decided to ask just in case.
Thank you in advance!
Nick.

**Comment by wildatease** [comment]
Hi, i'm having a similar problem... i'm unable to delete a product set from facebook manager account... i guess i've deleted it once but i did something wrong and it's still there and now the old products are showing up on my instagram shop :(
thanks

**Comment by lourraines** [comment]
Hi, I have the same issue. Deleted the catalog and now there is an error whenever i try to get it back.

**Comment by adriannees** [comment]
I am also having the same issue. Someone PLEASE figure this out. My entire 10k product catalog is inaccessible now.

**Comment by adriannees** [comment]
@dmitridr please reopen this ticket. It is not solved
