### ISSUE TITLE
Lots of graph.facebook.com 500 Internal Server errors

### ISSUE THREAD

**Issue by aand01** [facebookincubator/facebook-for-woocommerce#416]
Out of the blue, I'm seeing numerous 500 Internal Server Errors in Query Monitor related to facebook-for-woocommerce, along the lines of:

"https://graph.facebook.com/v2.9/catalog:xx==/
?fields=id,product_group{id}
Redirected to:
https://graph.facebook.com/v2.9/catalog:xx==/
?fields=id,product_group%7Bid%7D"
(with xx being the IDs)

Site performance is extremely slow due to this - what's going on?

**Comment by aand01** [comment]
Additionally, I'm seeing the following error in the backend as well:

"Facebook extension error: Facebook for WooCommerce
There was an issue connecting to the Facebook API: cURL error 28: Operation timed out after 0 milliseconds with 0 out of 0 bytes received"

**Comment by sammul** [comment]
Thanks for reporting. Are you on latest version?

**Comment by aand01** [comment]
@sammul, I'm running 1.8.3 - should I disable the plugin until the issue is resolved, or is a fix imminent?

**Comment by sammul** [comment]
Can you inform me your page id or facebook page url, as well as your first name so I can check your role on the page and business?

**Comment by sammul** [comment]
@aand01 I did not receive your email. Did you send to ads_extension_woocommerce@fb.com? Or you can just put facebook page url here

**Comment by aand01** [comment]
Strange it didn't arrive - url is /asoundeffects (please note that I've currently disabled the plugin due to the slowdowns)

**Comment by aand01** [comment]
Hi @sammul , any luck pinpointing the issue?

**Comment by mengyingdu** [comment]
Hi @aand01 ,

We have a fix for unnecessary server call and will include in the next version soon.

Thanks for your patience.

**Comment by mengyingdu** [comment]
Hi @aand01,

We had a quality room first half of this week and just released [v1.8.6](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.6) We have 10 fixes plus 1 content enhancement. This has been fixed in v1.8.6, please try to upgrade. Feel free to open a new issue if you have other question.

If you like **Facebook-for-WooCommerce**  please leave us a [*****](https://woocommerce.com/products/facebook/) rating. A huge thanks in advance!
