### ISSUE TITLE
no longer activates the catalog on the fb page

### ISSUE THREAD

**Issue by pasog** [facebookincubator/facebook-for-woocommerce#424]
I do not activate the catalog I created and I see it well in the business facebook but in the page does not load you can help me thanks

https://business.facebook.com/products/catalogs/1806036729702799/products
![image](https://user-images.githubusercontent.com/20639992/39092153-080908e6-4607-11e8-8078-1eeef4bfeec4.png)
I had deleted the old one I saw and tried to reload it to eliminate errors as I can reactivate it?

**Comment by pasog** [comment]
I have not been answered? !! it is possible to know what depends on thanks

**Comment by mengyingdu** [comment]
Hi @pasog ,

I see you have 2 catalog now: 1(360172644369161) is created from the plugin, another one(1773658789367623) maybe from your business before.

To confirm I have understand your request and question correctly:

1. You want to activate the catalog associate with your page , eg 360172644369161 currently.
2. But you don't know how to delete the one you cancel in progress of installation.

Is that right?

Thanks.

**Comment by pasog** [comment]
yes it's right! thanks

**Comment by pasog** [comment]
help me ...

**Comment by pasog** [comment]
my facebook page "window" maybe wants the old catalog ..
how can I unblock this problem

**Comment by pasog** [comment]
I tried everything, but the window of the Fb page does not activate you can help me

**Comment by mengyingdu** [comment]
Hi @pasog ,

Can you disconnect your business manager with your page?

**Comment by dmitridr** [comment]
Hi @pasog, 

Seems your shop is fine now, the page is loading.

But if you have this problem again, I recommend a full reset of the plugin by going to the plugin configuration page and hitting `Reconfigure > Advanced Options > Delete`. When going through setup, please ensure that you have selected the `Shop` to be `On` in the final step, otherwise the catalog will not appear in your page. #281 describes this in more detail. Hope that helps!
