### ISSUE TITLE
Pixel Events Error in Business Manager But Plugin Fire Pixel Correctly

### ISSUE THREAD

**Issue by auludag** [facebookincubator/facebook-for-woocommerce#430]
Hi,

1- I examine the chrome pixel helper tool and seeing that wrong viewcontent data is sent. 

[https://shop.royalmond.com/urun/royalmond-badem-ezmesi-a-serisi/](url)

2- And no addtocart sent as well. it could be related to 1. (I don't use Google Enhanced E-Commerce )

**Comment by auludag** [comment]
1) I wasn't using latest one. I was synced to WooCommerce reprository. I downloaded from the link thanks, but nothing changed. Strangely it takes not main product in the page. It sends latest product in the "related products" row below.

2) You are right. I reinstalled again after your message. Active now.

3) Also when I check Business Manager to give dynamic ad I see this error.

Missing content_type parameter from "Purchase" in Pixel
Missing content_ids or contents parameter from "Purchase" in  Pixel
Missing "AddToCart, Purchase, ViewContent" events in Pixel.

But when I create a test sale, I saw all the pixels are triggered

4) and warning: google_product_category is missing for products as well. (facebook business support team said i need to fix this as well, since i want tor run dynamic ads on instagram.

**Comment by mengyingdu** [comment]
Hi @auludag ,

Thanks for adopting our suggestion to try 1.8.5.

I checked viewContent, addToCart and InitiateCheckOut and all events can be fired correctly.

However, there are 2 things werid:
1. It seems your plugin settings not associated with your BM (Also, we don't recommend you connect them because we observed many cases BM not works very well with external plugin settings)
2. I understand that pixel fire events very important to you as you run dynamic Ads, however, I think the cause is Pixel team or business manager side. I will file your issue to their team, but I can't guarantee the timeline to get back to you. If you can reach out them through helper center tool, it could be faster. I will flag this to them anyway.
3. google_product_category warning is fine, since we are using other category type. And it won't affect your Ads or pixel at all.

Thanks.

**Comment by mengyingdu** [comment]
Hi @auludag ,

Sorry for the delayed response, i'm looking into your issues now.

**Comment by mengyingdu** [comment]
Hi @auludag ,

For 1.
1. I can't repo this bug, however, i found some related discussion. For some theme, get_the_id doesn't work. What's your theme?
2. Is the wrong price displaying in pixel   helper always the last related product?
3. I didn't find the add to cart button on your site. Can you show me how to 'buy' on your site?

Thanks

**Comment by mengyingdu** [comment]
Thanks for your adoption to v1.9.1, however, i checked it pulled the related product id problem still exist. can you try another theme to confirm the cause?

**Comment by auludag** [comment]
@mengyingdu thanks for that suggestion. Indeed when I changed the theme, fb pixel captured viewcontent data correctly. I use themify  Shoppe.

**Comment by mengyingdu** [comment]
Glad to hear you fix it @auludag
