### ISSUE TITLE
Variation not showing if product bundle + Update

### ISSUE THREAD

**Issue by benedettogit** [facebookincubator/facebook-for-woocommerce#432]
Simple product variation show no problem, 
Bundled products show variation on website but not on faceshop
link to an example product, with variations
https://www.whykini.it/shop/tutti-i-prodotti/serie-etnochic/aida-fantasia/
link to same example product, with variations but not showing.
https://www.facebook.com/commerce/products/1753764941336253/

Let me know if it's clear and if you need more.

I've updated the plugin to ver. 1.8.6 and I see in the change log Support Product Bundles Extension and i've reset everything but variations are still not showing, now I've disabled the url checkout, but it would still be nice if it would work

**Comment by mengyingdu** [comment]
Hi @benedettogit ,

To clarify it, we add basic support for bundle extension which allow the products with type bundle synced. However, we won't sync the variant. The logic is here:
The bundle product is basically combined by different actual product. However, by design, we can't put the individual product associated with one parent under 'variation ' dropdown. They are different from the variable products.

Hope you understand we can extend the compatibility as perfect as you expect, and I think it still works in this way : if the user checkout, they can select the options on your site, that's why we use the product page link from your site as the bundle product checkout url.

Thanks.

**Comment by benedettogit** [comment]
It's ok thanks, with the url checkout disabled it works just fine, the user will select the variation from the site and not from facebook
