### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by abhi21x** [facebookincubator/facebook-for-woocommerce#434]
There seems to be a missing closing tag somewhere in the plugin. Inspect element shows this error

`Uncaught SyntaxError: Unexpected end of input`

**Comment by mengyingdu** [comment]
Hi @abhi21x ,

Can you follow the instruction of the support section of this repository? I do need more information from your site in order to help you. eg. your site url, fb page url, your plugin version, etc.

I'd appreciate if you can take a look at the instruction before opening an issue. In the future, we will consider not to support tickets without any info.

Thanks for undertanding.

**Comment by abhi21x** [comment]
1. **symptoms** - "Uncaught SyntaxError: Unexpected end of input" in console

2. **Facebook page url** - https://facebook.com/faadu.in

3. **website url** - https://faadu.in

4. **Screenshot**

![1](https://user-images.githubusercontent.com/19635345/39313873-b1c0542a-4990-11e8-8d8c-860d7ae5bc54.jpg)

**Comment by abhi21x** [comment]
Hi @mengyingdu 

Just updated to v1.8.6. The console error is still there. It goes away when I disable the Facebook for WooCommerce plugin.

**Comment by mengyingdu** [comment]
Have you clean your browser cache in order to reload the js code?

**Comment by abhi21x** [comment]
Yes the cache is clear

**Comment by abhi21x** [comment]
Deleting the plugin & settings and uploading the plugin again fixed the issue. Thanks. You can close this issue now.
