### ISSUE TITLE
Facebook pixel not firing Purchase event when redirecting to different thank you page.

### ISSUE THREAD

**Issue by madjedo** [facebookincubator/facebook-for-woocommerce#435]
Hi, we are redirecting our customers to a different thank-you page different from the standard woocommerce one.

The pixel does however not fire the purchase event when we do this...

Is there a way we can keep redirecting to the different thank-you page and still have the pixel firing normally?

Best Regards,

**Comment by mengyingdu** [comment]
Hi @madjedo ,

Unfortunately, we hook purchase fire event on thankyou page. So you customize it, you will have this problem. (Because it's not a hook for woocommerce)

I would recommend you to use the standard page since purchase event is every important if you want to create ads on FB AND if you want to manage your business in catalog manager.

Thanks.

**Comment by madjedo** [comment]
Hi @mengyingdu  ,

Ok thanks. I removed the redirect and I am using a slightly edited standard thankyou page now. However, the purchase event is still not firing...

I am selling woocommerce subscriptions.

Thanks.

**Comment by madjedo** [comment]
Can I pm/mail you URL?

**Comment by dmitridr** [comment]
Hello,

You can mail us at `ads_extension_woocommerce@fb.com`, but it's easier for us if you post it here. If you are not comfortable sharing your URL: the name of your FB page, or catalog ID, or pixel ID would be enough for us.

I would double check to make sure your custom thank you page is firing the action `woocommerce_thankyou` , because this action is what we use to inject the pixel purchase fire.
Here's the [code](https://github.com/facebookincubator/facebook-for-woocommerce/blob/v1.8.7/facebook-commerce-events-tracker.php#L45).

If your thank you page calls a different action, then you will want to change the code linked above (using the Wordpress plugin editor) to whatever the name of the action is that your custom thank you page is calling, this should enable the purchase event to fire. 

I would also make sure you are using the latest version v1.8.7, we fixed a purchase event firing bug caused by another plugin in that version.

**Comment by madjedo** [comment]
@dmitridr No worrys! It's now firing. Maybe after I updated or did something I don't know… But it's working now. Thanks for the help.
