### ISSUE TITLE
facebook for woocommerce bug

### ISSUE THREAD

**Issue by hidrokoxilas** [facebookincubator/facebook-for-woocommerce#452]
Hi,
When i go to update any of my products i get a HTTP ERROR 500 with this url (/wp-admin/post.php)
When i refresh the page it gets me to all posts (/wp-admin/edit.php)
With the note:
Facebook for WooCommerce
Updated product group ....................... on Facebook.
I found out that when i deactivate the plugin  (facebook for woocommerce) problem is solved.
Thanks a lot ,
Angelo

**Comment by spradooooo** [comment]
Hello hidrokoxilas,

I had the same issue as well as other people here reported the issue, it seems that the issue happens because of the latest update 1.8.6 which supports WPML and I see now it is been removed from the releases page.

Try to install the previous version 1.8.5 and this issue will disappear.

I hope the developers work on a fix for it because I was waiting so long for WPML support.

Kind regards

**Comment by mouseacookie** [comment]
reverting back to the previous version alleviates this problem, but it doesn't solve the issue of the page taking forever to load if at all.

**Comment by hidrokoxilas** [comment]
@mengyingdu 
hi,
I dont know any programming but i found those on my plesk logs section 
![facebook for woocommerce error log](https://user-images.githubusercontent.com/38912603/39546352-ca48f6de-4e5c-11e8-93ac-48ef298c4a5f.JPG)

Maybe you can figure something out.

Thanks for the fast response.

**Comment by mengyingdu** [comment]
Hi @hidrokoxilas ,

It looks related to the current fix. However, it's very weird since http 403 error is forbidden error, eg. you dont have the access to sth. I suggest you try the new version once I update it. 

Thanks.

**Comment by mengyingdu** [comment]
Hi @hidrokoxilas @mouseacookie @findyongjin ,

[v1.8.7](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.7) is alive now and fix this issue. 

Thanks!
