### ISSUE TITLE
Force Resync of the products

### ISSUE THREAD

**Issue by ShopVeraVeraCollection** [facebookincubator/facebook-for-woocommerce#457]
Hi!

I'm coming back with my issue (#74). Just 50 items out of 167 has been aploaded.

You said:

 Click 'Force Resync' and click OK

 Don't understand How I can do that? where is Force Resync to click on?

Should I deactivate plugin and then activate it again?

Also when I renew the collection, adding new products or deleting the old, which are out of stock. Don't really understand how I can control that. Can I do that at least manually? add or delete products from this "Shop All" Section?
I know that I can create collections manually, but it will be a different subdivision. I want to know how I can control this "shop all" section ( which is syncrinised with my website).

Thank you.

Thank you

**Comment by sammul** [comment]
@ShopVeraVeraCollection You should manage the products on woo commerce side. 
The force resync is here WooCommerce -> settings -> integration:
<img width="703" alt="screen shot 2018-05-03 at 11 06 23 pm" src="https://user-images.githubusercontent.com/4251631/39614702-a7dff474-4f26-11e8-9498-e0f2bdc6a067.png">

**Comment by sammul** [comment]
Please also try https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.8.7 if you haven't used latest version. We have fixed a lot of issues since then

**Comment by dmitridr** [comment]
Hello,

We are working on Instagram support before the end of this half (June). Unfortunately it's not supported right now, as mentioned. The process will be something like as follows : an option will appear in the `Reconfigure` section where you can request an Instagram shop. If approved, your shop should become visible on instagram, though I am not sure if this will enable tagging (probably, yes).

Thanks for your patience! I'm going to close this out since the original problem appears to have been solved, but feel free to open a new issue (feature request) for the Instagram functionality through the plugin, though as I said we do have a team working on that right now.
