### ISSUE TITLE
[Request] Support woocommerce REST API 

### ISSUE THREAD

**Issue by lucasgbriell** [facebookincubator/facebook-for-woocommerce#459]
When I add a product by using REST Api, my product status keep "Not synced". 

Isn't there a way to fix that?

To refresh on facebook page by a product is added..

**Comment by sammul** [comment]
We had same asks before but we don't support REST api yet #244

**Comment by dmitridr** [comment]
After adding products via REST API, I would recommend editing the added products through bulk-edit (adding and removing a space, etc.) which should trigger an update to FB. If this doesn't work, try doing a `Force Resync`, this should be reasonably fast in versions 1.8.2 and above, even for hundreds of products. 

(If it's not fast, try a `Reconfigure > Advanced Options > Delete` and set up from scratch, for legacy reasons this may be necessary in order to use the new fast sync)

**Comment by mengyingdu** [comment]
We'll consider to build support for REST API based on user demand and Engineer capacity, if anyone like this feature please vote here to help us understand priority. Unfortunately, we don't have the ETA now.

If anyone is interested, we'd be happy to review any pull request to add this functionality!

**Comment by aaman** [comment]
Adding products via REST API would be a great service.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
