### ISSUE TITLE
Sync with multiple variations problem

### ISSUE THREAD

**Issue by CreativeMaja** [facebookincubator/facebook-for-woocommerce#469]
We have  3 types variations of tea 
50g, 100g, 200g.
Sometimes is showing the price for 50g and sometimes is showing the price for 200g. all is mix how I can setup price 50g for all product??
Thank You

**Comment by CreativeMaja** [comment]
That's what I see is Not Synced but on Facebook, Shop working not correctly.
https://www.itstea.co.uk
https://www.facebook.com/pg/itstealtd/shop/?ref=page_internal

**Comment by dmitridr** [comment]
Hello,

I checked your site but it seems the shop is not there right now, perhaps you removed the plugin?
Let me double check to see if I understood you correctly.

(1) All your products have 3 variants, 50g, 100g, 200g. 
(2) The price is showing incorrectly. Could you elaborate on where the price is showing incorrectly? Is it the main shop page or when you click on a product? A screenshot would be great.
(3) Do you have default variants selected on WooCommerce? If you select a default variant (50g), the price in the main shop screen will show the price of the default variant.

Hope that helps!

**Comment by mengyingdu** [comment]
Hi @CreativeMaja ,

I checked out logging which shows that you delete your settings on 1st May. Also, you probably delete the plugin since there is no pixel fire event on your site.
I checked your catalog, actually, you have many products synced successfully. 

If you want to get the benefits of fb shop to display your products, you just need to re-setup.
If you have further questions about the synced products' information, you can ask here.

Thanks.

**Comment by dmitridr** [comment]
Closing as there hasn't been a reply in a month. If you have further concerns, feel free to open a new issue on us.
