### ISSUE TITLE
Supporting the Case : Two Sites, One Page.

### ISSUE THREAD

**Issue by fcroel** [facebookincubator/facebook-for-woocommerce#472]
I'm trying to setup the integration on a two sites but experiencing an issue with selecting the right Pixel.

Here's the breakdown of the setup:

- One FB page
- Two websites (domains)
- Two ad accounts
- Two different Pixels

Issue:

When selecting the right Pixel for the respective domain in the FB for WooCommerce plugin, I can see both Pixels. However, when selecting the right Pixel, it also changes the choice on the other domain and vice versa. How can we select different pixels on different domains?

**Comment by dmitridr** [comment]
Hello,

That's an interesting setup. 
When you say you have two websites, do you mean just two domains or two servers as well?

If it's just one server, I can see why you are having this problem, we don't support this case. If it's two different servers, this is a weird problem and we'd need some more info. But most likely it's because you only have one FB page. 

The setup of the plugin is tied closely with the page in a 1-1 mapping. For each setup that you do, you would need to use a different page. Hope that helps.

**Comment by fcroel** [comment]
Thanks for your reply! The two websites are hosted on different servers. 

I can understand that it's closely tied to the page. When I installed the plugin on the second (new) domain/server, it immediately recognized the page as well during the setup (does it fetch this info from logged in FB user in the browser?). However, according to our FB account manager you should be able to use different pixels through different ad accounts, which we did by having one pixel per account but to no avail unfortunately.

Would love to hear if there's a work around for this. We'd like to avoid having to start a new page just for this purpose. Thanks!

**Comment by dmitridr** [comment]
Hello again,

Apologies for the delay in getting back to you, we are dealing with a high volume of issues.

This is a difficult case, I can think of some things to try if you really want to get this to work, but there's no guarantees it will work and you may run into problems.

You will need to use version v1.7.11 of the extension for this, it will not work on more recent versions! Though you may be able to upgrade after getting it to work. Let's say the servers are Server A and Server B. 

I would do the setup on Server A, then enable `WP_DEBUG` on both servers.
On the plugin Config page, a bunch of entries should appear on Server A. Copy all the entries into Server B's config page and hit Save. On Server B, make some small modifications to each product (add a period or space) to sync each one manually onto FB. 

Another way instead of using `WP_DEBUG` is to copy the DB row in `wp_options` corresponding to the extension (search for `facebook` in the DB) from Server A to Server B. This will accomplish the same thing.

It's quite a complicated workaround, but you're welcome to try. Hope it helps.

**Comment by dmitridr** [comment]
And yes to answer your question in the setup flow we use whichever cookie is active/logged in to fetch the list of pages.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
