### ISSUE TITLE
Error during install & site stops working.

### ISSUE THREAD

**Issue by brusinger** [facebookincubator/facebook-for-woocommerce#474]
Hopefully someone can point me in the right direction. 
My site is www.mannisijewelers.com/shop
Running wordpress version 4.9.5, I've updated all my plugins.
When I install the Facebook for Woocommerce plugin, I get two errors:
Unpacking the package…

Installing the plugin…

Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'TransferOutBeforeUpgrade' not found or invalid function name in /home/content/77/2025877/html/mannisijewelers/shop/wp-includes/class-wp-hook.php on line 286

Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'TransferInAfterUpgrade' not found or invalid function name in /home/content/77/2025877/html/mannisijewelers/shop/wp-includes/class-wp-hook.php on line 288
Plugin installed successfully.

As soon as I activate the plugin, my site goes down ( just a  blank page) 
Anyone have any idea how to fix this?

**Comment by dmitridr** [comment]
Hello,

That's a pretty bizarre issue. We don't have the functions 'TransferInAfterUpgrade' 
I googled and found a similar problem for a WPML user installing WPML, 
https://wpml.org/forums/topic/installation-and-management/

This makes me think there's two separate problems (1) these warning messages that you pasted (2) the blank screen. Reading the above thread, seems like (1) is unrelated to our plugin so the problem is (2)? Couple of questions:

What's your plugin version for Facebook for WooCommerce? (If it's not 1.8.7, please try that. If it is 1.8.7, please try 1.7.11, it will help us understand if this is a problem caused by a recent change) 
What's your version for WooCommerce?

Thanks

**Comment by dmitridr** [comment]
The problem in (1) seems to be related to PHP version. Could you also give us that if you have it? We only support PHP 5.6 and greater, so using a lower version could definitely cause a blank screen.

**Comment by brusinger** [comment]
Woocommerce version 3.3.5
PHP 5.6
Facebook for Woocomerce version is 1.8.3
I downloaded from Woocommerce store, where can I download other versions?

**Comment by dmitridr** [comment]
Sorry for the delay in getting back to you. 
I searched for your error message online, it seems it's caused by another catalog plugin:
https://wordpress.org/support/topic/wrong-function-names-causing-warnings-when-updating-plugins-and-themes/
https://wordpress.org/support/topic/transferoutbeforeupgrade-error-messages-during-installation/

Do you have any other catalog plugins in your setup? If so I recommend deactivating those before activating ours. Does it help? Judging from the above links it does not appear to be a bug in our plugin...

Our releases can always be found here. 
https://github.com/facebookincubator/facebook-for-woocommerce/releases

If you can't fix it by disabling the conflicting plugin, I recommend trying 1.7.11 and 1.8.7 to see if the problem persists. Hope that helps.

**Comment by brusinger** [comment]
Thanks I installed the latest relesase 1.9 and that fixed the problem
