### ISSUE TITLE
'Your pixel activated two times which can cause errors in your tracking'. I received this message using the Facebook Pixel helper tool for Chrome

### ISSUE THREAD

**Issue by brice-measure** [facebookincubator/facebook-for-woocommerce#479]
I have updated my plugin to the latest version and still got this. Any ideas on why this is happening? I've noticed it for the Add to Cart event.

Website: borahteamwear.com

**Comment by sammul** [comment]
Tested on your website but didn't see the issue. How do I reproduce?

<img width="1206" alt="screen shot 2018-05-14 at 9 11 48 am" src="https://user-images.githubusercontent.com/4251631/40009451-e2cad7d8-5756-11e8-8fbc-8cb89f73557e.png">

**Comment by sammul** [comment]
Please re-open if you still encounter this and let us know how to reproduce.

**Comment by annyta91** [comment]
Hy, my "Add to cart event" fires two times. I saw that the problem is caused because I installed the event two times. I checked and I didn't find something wrong. Could you please tell me how can I check if it's installed two times, and how can I delete one of it? Or maybe another solution? Please.
Website: https://apostrophe.ro

Thank you.
