### ISSUE TITLE
Facebook for WooCommerce issues, slowing down and cant add new products

### ISSUE THREAD

**Issue by zolpo1** [facebookincubator/facebook-for-woocommerce#482]
We have thousands of products in the store, we installed the Facebook for WooCommerce and the synchronization process created bugs at the admin management system, so we had to stop using the plugin.
Is there a solution? We look forward for any support.

**Comment by Maxxxos** [comment]
Hi -  I help to Zolpo1 with development
such errors we see when try look products in admin
http://joxi.ru/xAeKRjZsYWLVbm

**Comment by sammul** [comment]
@zolpo1 @Maxxxos can you guys share your facebook page url?

**Comment by Maxxxos** [comment]
https://www.facebook.com/www.zolpo.online

**Comment by joni-teamit** [comment]
I think I'm encountering similar issue. Enabling plugin basically creates a DDOS-attack to our page that is originating from facebook. Main culprit seems to be the sync operation. As soon as I activate the plugin and wait couple of minutes I have hundreds of connection active to several IPs all owned by facebook. Haven't studied this at all because it immidiately makes my dedicated double core server hang. Disabling this will make things normal again.

It worked fine for couple of weeks but then out of nowhere this happened. I get a info in admin panel that the system is updating approx. 3k products.

**Comment by Maxxxos** [comment]
reinstalled. removing all setting and reconfigure.
BTW I not find how delete all products in facebook
https://www.facebook.com/pg/www.zolpo.online/shop/ - I not see such possibility or buttons like described here

I started forсу resync . Already 1 hours this doing some but I not see new product on facebook
When I try look products in admin it is very slow and errors  
71 sec for loading
http://joxi.ru/eAO9nK8U4yWZam

https://graph.facebook.com/v2.9/catalog:168217373854549:em9sMTkzNzZfMTkzNzY=/
?fields=id,product_group{id}
Redirected to:
https://graph.facebook.com/v2.9/catalog:168217373854549:em9sMTkzNzZfMTkzNzY=/
?fields=id,product_group%7Bid%7D

we have 1049 products and looks that all in facebook
Maybe this problem from trash or draft products?

**Comment by dmitridr** [comment]
It should not take 1 hour, but thanks for the detailed info. I checked your shop, indeed you are uploading using the slow method despite using the new version, this is strange.

There is one case where we fall-back to the slow upload method. This is when `curl` is not available on the server via php, we use `curl` to upload a CSV file with all the products to FB (fast), otherwise we fall back to uploading one by one (very slow). Could you comment on whether or not `curl` is available for you or not? 

If it is not available... that is the cause. If it is... the problem is something else.

@mengyingdu you're the expert on the curl functionality here, do you know how can it be enabled on the server in general? or does it depend on server settings?

**Comment by dmitridr** [comment]
To delete all products in facebook, you must either (1) mark the delete button on the WooCommerce side or (2) delete the catalog on Facebook at `www.facebook.com/products`. Hope that helps.

**Comment by mengyingdu** [comment]
Did you install cURL on your server? @Maxxxos 
https://www.digitalocean.com/community/questions/enabling-curl-for-wordpress-add-on-to-work-correclty

**Comment by mengyingdu** [comment]
close issues since no update in 2 months
