### ISSUE TITLE
Add To Cart Not Firing

### ISSUE THREAD

**Issue by telaviv1983** [facebookincubator/facebook-for-woocommerce#508]
hi
im using "Facebook for WooCommerce" plugin, it fire everything but the ATC
how can i fix it?
thanks

**Comment by telaviv1983** [comment]
?

**Comment by mengyingdu** [comment]
@telaviv1983 
If you are not on the latest version, i recommend upgrade. If your problem still exists, please follow the above instruction to give us enough info to help your investigate

**Comment by mengyingdu** [comment]
## Automated Support Message - Issue Closed

Hello,

Because it has been 30 days since this issue was updated and you have not included `Debug Ready` in your reply, our automated system will now close your issue.
If you are still having this problem, please open a new issue and reference this one.

For more information on our response times and support policy, visit [Facebook Support on GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Facebook-Support-on-GitHub).

Thank you,
The Facebook Dev Team
