### ISSUE TITLE
Your API key is no longer valid. Please click "Re-configure Facebook Settings > Advanced Options > Update Token".

### ISSUE THREAD

**Issue by elian0072** [facebookincubator/facebook-for-woocommerce#510]
Hi,

I've been using FB for Woo for a couple of weeks and was working perfectly. Had my store on fb nd it was great.

Now it appears that my API key is no longer valid, I go throught he setup and I can update my API token, which I do. Tells me it's updated. I then refresh the integration page where the plugin settings are and goes back to the same issue.

Since that, my store is not on FB and I don't know what to do

**Comment by mengyingdu** [comment]
## Automated Support Message - Issue Closed

Hello,

Because it has been 30 days since this issue was updated and you have not included `Debug Ready` in your reply, our automated system will now close your issue.
If you are still having this problem, please open a new issue and reference this one.

For more information on our response times and support policy, visit [Facebook Support on GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Facebook-Support-on-GitHub).

Thank you,
The Facebook Dev Team
