### ISSUE TITLE
Instagram shop "view on website" leads to "webpage not available" 

### ISSUE THREAD

**Issue by oneofme66** [facebookincubator/facebook-for-woocommerce#537]
Hi,

When I click through the shop/product on my instagram (catalog and items come up correctly), I am lead to click on a link which will take me to the facebook shop/product. This page does not exist. The facebook product pages exist however. I am not sure what source Instagram is pulling the link from, but it is incorrect, and I cannot find where the break is. 

Has anyone experienced this? Should I migrate the facebook shop to shopify? I really don't want to, I would rather just find the inconsistency and fix it. 

Thanks.

**Comment by mengyingdu** [comment]
@oneofme66 
Catch up here, can you provide more details? Will close it if no response in one month.

**Comment by oneofme66** [comment]
What details would you like?

**Comment by mengyingdu** [comment]
The details we asked in the first reply. That's also a summary of our FAQ.

**Comment by mengyingdu** [comment]
## Automated Support Message - Issue Closed

Hello,

Because it has been 30 days since this issue was updated and you have not included `Debug Ready` in your reply, our automated system will now close your issue.
If you are still having this problem, please open a new issue and reference this one.

For more information on our response times and support policy, visit [Facebook Support on GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Facebook-Support-on-GitHub).

Thank you,
The Facebook Dev Team
