### ISSUE TITLE
Facebook shop shows price with tax initially, but incorrectly without tax after updating a product card

### ISSUE THREAD

**Issue by miikapk** [facebookincubator/facebook-for-woocommerce#543]
My shop is set up filling prices on the product cards without tax, and then on the front-end prices including tax are shown. This is done with basic WooCommerce configuration (not by plugins).

So, when initially syncing the Facebook for Woocommerce plugin shop, the prices are correctly shown with taxes on the FB shop. But, when updating any product card on WC, the product is synced to FB showing price without tax.

For example, many of our products are 10,48€ without tax, and 13,00€ with tax (VAT24). Initially all these show properly 13,00€ on FB shop, but after simply opening a product card on WC and click "update" (and not even do any changes), the product on FB shop is updated to show 10,48€.

This leaves users feeling we show low price on FB, and once they check out to our store, higher price is shown.

Need any further help to investigate?

**Comment by mengyingdu** [comment]
## Automated Support Message

Hello,

Thanks for your interest in our plugin!

If your issue is a feature request or feedback for the developers, reply with `Feature Request` or `Feedback`.
Your comment will be categorized accordingly, and we will read it and reply when we can.

If you have encountered a bug or a problem with the plugin, the steps below contain information to help you resolve the issue yourself and provide us information we need to help you with your problem.

## Search Existing Issues

**First, please [search our issues](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=) to see if your problem has been reported before.**
There may already be a workaround or a solution to your problem. You can search our issues using [the search bar near the top of our issues page](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=); be sure to search both _open_ and _closed_ issues.
If you do find a similar issue, leave a comment on that issue and close this one. Your comment helps us prioritize which existing issues are important and urgent.

## Common Resolution Methods

**If you are experiencing a problem or bug and have not found any similar issue, please try the following:**

* Upgrade to the latest version of the plugin.
* Try to `Resync` products using the button on the plugin config page
* Reset the plugin by selecting `Reconfigure > Advanced Options > Delete`, and setting up this plugin again.
* Try to deactivate other plugins that you think may be interfering, then reset and set up again.

## Necessary Information

**If the above steps did not help, please provide the following information in your next comment in order for us to debug your problem:**

* WooCommerce version
* WordPress version
* Plugin version (please note: we only support up-to-date versions of the plugin)
* A screenshot of where you see the problem (for example: if it is on Facebook, a screenshot of Facebook, if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.)
* The URL of your website
* The URL of your page
* The URL(s) of where you took your screenshot(s)
* (If applicable) Detailed steps you took in order to see the problem

Please include `Debug Ready` in your reply so our automated system can flag your issue for manual review. Please note that due to a high volume of issues, we may not be able to respond immediately.

Thanks for your patience,
The Facebook Dev Team (@mengyingdu, @dmitridr, @sammul, @jieminz22)

**Comment by mengyingdu** [comment]
Can you upload your product card screen shot (with a product which has this problem)?
What's your page url and site url?  @miikapk

**Comment by miikapk** [comment]
This affects all the products that I have already created and new ones I'm creating.

On WooCommerce, I have set the following: WooCommerce -> Settings -> Tax -> Tax Options -> Prices entered with tax:  No, I will enter prices exclusive of tax

So, on the product cards I will enter the price under General -> Regular price (€): 10,48. This is without tax. On the front-end WooCommerce will calculate and show price with tax, that is 13.00€.

So, after syncing products to Facebook, all the product prices on Facebook Page Shop are shown correctly with tax (13.00€).

Now, when I open any product card on WooCommerce and update the product card, the sync is initialized to Facebook Page Shop, and suddenly the price shown is without tax (10.48€).

Also, when creating a new product on WooCommerce and saving it, the price is immediately shown without tax (10.48€) on Facebook Page Shop.

The URL to website is www.klipsutin.fi/en.

Would you still need a screenshot of a single product card?

I have also tried to disable all the plugins I can imagine and launching fresh product sync, but I've seen no effect.

I'm more than happy to help sorting this out!

**Comment by Antonio-Laguna** [comment]
I do have the same issue

**Comment by mengyingdu** [comment]
@Antonio-Laguna  @miikapk 
Did you set up tax config as described in this instruction?

**Comment by mengyingdu** [comment]
Sorry, didn't post the link correctly. The instruction is here: https://docs.woocommerce.com/document/setting-up-taxes-in-woocommerce/
@Antonio-Laguna  @miikapk

**Comment by Antonio-Laguna** [comment]
Yeah. Prices excluding taxes is what I have but good according to that link

**Comment by Antonio-Laguna** [comment]
Why did this get closed?

**Comment by rafyc** [comment]
salme issue

**Comment by miikapk** [comment]
Unfortunately even after verifying the above mentioned tax settings, it was not possible to have this plugin function properly. I ended up changing the price visibility to include tax as there was no other way to make this work.

For some unknown reason the developers were not interested to investigate or take part on finding out the root cause more in depth, but instead simply closed the ticket.

**Comment by Michaelgimm** [comment]
Hi Miikapk
The funny thing is, that my prices are displaying price including tax (25%). So if a product cost 100 incl. tax, then it is 100 that I am displaying at my site. 

But Facebook is displaying the price excluding tax, which is 80.

Are you saying that you have this setting in WooCommerce as well, and that you made it work?

**Comment by miikapk** [comment]
Hi Michaelgimm and sorry for the late reply. Yes, when I set shown price to include tax, it'll also show them properly on FB shop. So therefore I am not able to help with that, other than to refer to the tax options. Hope you get it to work.
