### ISSUE TITLE
Business Owned Page : Product Upload Fails after Reset

### ISSUE THREAD

**Issue by caag06** [facebookincubator/facebook-for-woocommerce#546]
Hi. Have a good day. 
We are trying to use your plugin woocommerce for facebook but now we can´t upload products to facebook. 
Using Facebook Pixel Helper we have this message: 
InitiateCheckout and ViewContent WARNINGS Can't match products. 
And this other into facebook calatog diagnostics: 
Missing "AddToCart, Purchase" events in Baccio Couture
Our site: 
https://bacciocouture.com

Take a look to this images: 
https://bacciocouture.com/wp-content/uploads/2018/06/1FBBaccio.jpg 
https://bacciocouture.com/wp-content/uploads/2018/06/2FBBaccio.jpg

Thanks for your support.

**Comment by dmitridr** [comment]
## Automated Support Message

Hello,

Thanks for your interest in our plugin!

If your issue is a feature request or feedback for the developers, reply with `Feature Request` or `Feedback`.
If you are a developer or have a question for the developers related to code, reply with `Developer Question`.
Your comment will be categorized accordingly, and we will read it and reply when we can.

If you have encountered a bug or a problem with the plugin, the steps below contain information to help you resolve the issue yourself and provide us information we need to help you with your problem.

## Search Existing Issues

**First, please [search our issues](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=) to see if your problem has been reported before.**
There may already be a workaround or a solution to your problem. You can search our issues using [the search bar near the top of our issues page](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=); be sure to search both _open_ and _closed_ issues.
If you do find a similar issue, leave a comment on that issue and close this one. Your comment helps us prioritize which existing issues are important and urgent.

## Common Resolution Methods

**If you are experiencing a problem or bug and have not found any similar issue, please try the following:**

* Upgrade to the latest version of the plugin.
* Try to `Resync` products using the button on the plugin config page
* Reset the plugin by selecting `Reconfigure > Advanced Options > Delete`, and setting up this plugin again.
* Try to deactivate other plugins that you think may be interfering, then reset and set up again.

## Necessary Information

**If the above steps did not help, please provide the following information in your next comment in order for us to debug your problem:**

* WooCommerce version
* WordPress version
* Plugin version (please note: we only support up-to-date versions of the plugin)
* A screenshot of where you see the problem (for example: if it is on Facebook, a screenshot of Facebook, if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.)
* The URL of your website
* The URL of your page
* The URL(s) of where you took your screenshot(s)
* (If applicable) Detailed steps you took in order to see the problem

Please include `Debug Ready` in your reply so our automated system can flag your issue for manual review. Please note that due to a high volume of issues, we may not be able to respond immediately.

Thanks for your patience,
The Facebook Dev Team (@mengyingdu, @dmitridr, @sammul, @jieminz22)

**Comment by caag06** [comment]
HI. Thanks for your response. 
Most articles about this issue are open with no response.
Products are not loading to FB catalog

Woocommerce, Wordpress, plugins are updated.
https://bacciocouture.com

You can see: 
https://bacciocouture.com/checkout/
https://bacciocouture.com/shop/milly-painted-short/
https://bacciocouture.com/product-category/short-dresses/page/20/
https://facebook.com/products/catalogs/1963008073769486/diagnostics

And this images:
![1](https://user-images.githubusercontent.com/40444905/41756485-7636c130-75a2-11e8-8829-326dd53405b6.jpg)
![2](https://user-images.githubusercontent.com/40444905/41756486-76577f92-75a2-11e8-9243-9e2354dad1cd.jpg)
![3](https://user-images.githubusercontent.com/40444905/41756487-7678913c-75a2-11e8-9d31-0c0a5a1a6dae.jpg)
![4](https://user-images.githubusercontent.com/40444905/41756488-769c4104-75a2-11e8-8dcd-73b1b0162255.jpg)
![5](https://user-images.githubusercontent.com/40444905/41756489-76c7759a-75a2-11e8-9450-3f48a2832720.jpg)
![6](https://user-images.githubusercontent.com/40444905/41756491-771755f6-75a2-11e8-886d-8c722f72f135.jpg)


Down the debug
Notice: WC_Product::get_categories is deprecated since version 3.0! Use wc_get_product_category_list instead. in /home/baccioco/public_html/wp-includes/functions.php on line 3840

Notice: WC_Product::get_tags is deprecated since version 3.0! Use wc_get_product_tag_list instead. in /home/baccioco/public_html/wp-includes/functions.php on line 3840
  
Notice: WC_Product::get_upsells is deprecated since version 3.0! Use WC_Product::get_upsell_ids instead. in /home/baccioco/public_html/wp-includes/functions.php on line 3840

Notice: WC_Product::get_related is deprecated since version 3.0! Use wc_get_related_products instead. in /home/baccioco/public_html/wp-includes/functions.php on line 3840

Notice: id was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/bigpoint/woocommerce/single-product.php'), wc_get_template_part, load_template, require('/themes/bigpoint/woocommerce/content-single-product.php'), do_action('woocommerce_after_single_product_summary'), WP_Hook->do_action, WP_Hook->apply_filters, woocommerce_output_related_products, woocommerce_related_products, wc_get_template, include('/themes/bigpoint/woocommerce/single-product/related.php'), WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong Please see Debugging in WordPress for more information. (This message was added in version 3.0.) in /home/baccioco/public_html/wp-includes/functions.php on line 4148

Thanks for your support

**Comment by caag06** [comment]
Some idea or guideness?

**Comment by dmitridr** [comment]
Hi, 

As you say, your products have not been uploaded to Facebook... this is the reason for all the problems you describe. I have in our logs that you succeeded in uploading products on May 22nd, but somehow after this time, the upload failed every time.

Is there anything that you changed on your server between May 22nd and June 10? It seems the product sync started failing during this time.

This seems similar to #449. Your best bet is to try the advice in that thread, I would try resetting and trying version 1.7.11 to see if the problem is the new method of product sync. Versions are available [here](https://github.com/facebookincubator/facebook-for-woocommerce/releases). 

I will continue looking into this, if I find something new I will update here.

**Comment by dmitridr** [comment]
It looks like a permissions problem to me. It seems that the token we generate for you does not have permission to edit the page. This is indicative of a permissions problem, likely to do with the permissions you have set up on the page in Business Manager. I would recommend decoupling this page from business manager in order to get our plugin to work, in the short term. 

In the meantime I'm looking into what the specific cause is to see if we can fix it.

**Comment by caag06** [comment]
Thank you.
I do what you say: Decoupling page from business manager. Solved
