### ISSUE TITLE
Can I use 2 variations of product on Facebook shop?

### ISSUE THREAD

**Issue by gerenok** [facebookincubator/facebook-for-woocommerce#563]
Hi, I've made test shop for Facebook so far to make sure everything works.
Web: https://bohocoats.com/shop/
Test FB store https://www.facebook.com/Woo-test-658119637913180/

I have two kinds of variations in some products - size and linings. Example: https://bohocoats.com/product/falcon-festival-fur-vest/

On FB store there is only one variation - lining - https://www.facebook.com/commerce/products/2305009859512715/

Can I use two of variations on this product or it's better to show the only size and give a user an option to choose the lining on the web page of the product?

Thank you in advance.

**Comment by mengyingdu** [comment]
## Automated Support Message

Hello,

Thanks for your interest in our plugin!

If your issue is a feature request or feedback for the developers, reply with `Feature Request` or `Feedback`.
If you are a developer or have a question for the developers related to code, reply with `Developer Question`.
Your comment will be categorized accordingly, and we will read it and reply when we can.

If you have encountered a bug or a problem with the plugin, the steps below contain information to help you resolve the issue yourself and provide us information we need to help you with your problem.

## Search Existing Issues

**First, please [search our issues](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=) to see if your problem has been reported before.**
There may already be a workaround or a solution to your problem. You can search our issues using [the search bar near the top of our issues page](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=); be sure to search both _open_ and _closed_ issues.
If you do find a similar issue, leave a comment on that issue and close this one. Your comment helps us prioritize which existing issues are important and urgent.

## Common Resolution Methods

**If you are experiencing a problem or bug and have not found any similar issue, please try the following:**

* Upgrade to the latest version of the plugin.
* Try to `Resync` products using the button on the plugin config page
* Reset the plugin by selecting `Reconfigure > Advanced Options > Delete`, and setting up this plugin again.
* Try to deactivate other plugins that you think may be interfering, then reset and set up again.

## Necessary Information

**If the above steps did not help, please provide the following information in your next comment in order for us to debug your problem:**

* WooCommerce version
* WordPress version
* Plugin version (please note: we only support up-to-date versions of the plugin)
* A screenshot of where you see the problem (for example: if it is on Facebook, a screenshot of Facebook, if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.)
* The URL of your website
* The URL of your page
* The URL(s) of where you took your screenshot(s)
* (If applicable) Detailed steps you took in order to see the problem

Please include `Debug Ready` in your reply so our automated system can flag your issue for manual review. Please note that due to a high volume of issues, we may not be able to respond immediately.

Thanks for your patience,
The Facebook Dev Team (@mengyingdu, @dmitridr, @sammul, @jieminz22)

**Comment by gerenok** [comment]
Feature Request

**Comment by mengyingdu** [comment]
Hi @gerenok ,

This is currently supported. If you add size and lining, 2 attributes and create variations from attributions. It will show 2 drop down boxes on FB. Unless you use other special way to create / set up your product config on your store

**Comment by mengyingdu** [comment]
![screen shot 2018-07-05 at 11 15 24 pm](https://user-images.githubusercontent.com/24535640/42362697-56d3bc6e-80a9-11e8-87b5-b5718f4ee70c.png)

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
