### ISSUE TITLE
Not able to delete product catalogs in Facebook..

### ISSUE THREAD

**Issue by metuza** [facebookincubator/facebook-for-woocommerce#570]
Hello.. I decided to delete all settings in my WC install so i could setup new catalog and facebook shop. I have now deleted everything also my old FB shop but still there is 2 catalogs i can not delete, it says they are linked to my FB shop and need to be handled from there. But my FB shop is fully deleted.

Just want to clean up everything before i re-install again.

My FB site is: https://www.facebook.com/ArcticFritid/ and id: 819338601437272
If anyone can delete these extra catalogs..

Thanks
Brgds
Rune

**Comment by jieminz22** [comment]
## Automated Support Message

Hello,

Thanks for your interest in our plugin!

If your issue is a feature request or feedback for the developers, reply with `Feature Request` or `Feedback`.
If you are a developer or have a question for the developers related to code, reply with `Developer Question`.
Your comment will be categorized accordingly, and we will read it and reply when we can.

If you have encountered a bug or a problem with the plugin, the steps below contain information to help you resolve the issue yourself and provide us information we need to help you with your problem.

## Search Existing Issues

**First, please [search our issues](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=) to see if your problem has been reported before.**
There may already be a workaround or a solution to your problem. You can search our issues using [the search bar near the top of our issues page](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=); be sure to search both _open_ and _closed_ issues.
If you do find a similar issue, leave a comment on that issue and close this one. Your comment helps us prioritize which existing issues are important and urgent.

## Common Resolution Methods

**If you are experiencing a problem or bug and have not found any similar issue, please try the following:**

* Upgrade to the latest version of the plugin.
* Try to `Resync` products using the button on the plugin config page
* Reset the plugin by selecting `Reconfigure > Advanced Options > Delete`, and setting up this plugin again.
* Try to deactivate other plugins that you think may be interfering, then reset and set up again.

## Necessary Information

**If the above steps did not help, please provide the following information in your next comment in order for us to debug your problem:**

* WooCommerce version
* WordPress version
* Plugin version (please note: we only support up-to-date versions of the plugin)
* A screenshot of where you see the problem (for example: if it is on Facebook, a screenshot of Facebook, if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.)
* The URL of your website
* The URL of your page
* The URL(s) of where you took your screenshot(s)
* (If applicable) Detailed steps you took in order to see the problem

Please include `Debug Ready` in your reply so our automated system can flag your issue for manual review. Please note that due to a high volume of issues, we may not be able to respond immediately.

Thanks for your patience,
The Facebook Dev Team (@mengyingdu, @dmitridr, @sammul, @jieminz22)

**Comment by jieminz22** [comment]
Hi @metuza,

As it mentioned above, you can reset the plugin by selecting `Reconfigure > Advanced Options > Delete`, and setting up this plugin again.

Let us know if it doesn't work.

**Comment by metuza** [comment]
Hello,

Yes, thats no problem... The problem is that for some reason i have got a lot of product catalogs in facebook, most of them i could delete but there is still 2 left, one with 52 products and one with 0 products. These can not be deleted as they belong to a shop. So i once again reconfigured everything, deleted the shop and re-uploaded all products again. But still there is 2 catalogs to much.

So question was if you could just delete these 2 catalogs from your end.

Brgds
Rune

**Comment by yourbeautygadgets** [comment]
Hi! I'm facing the same issue, I can't delete product catalogue from my facebook page. Also I don't want to synchronise my products to facebook, but I can not undo it. Plus, when I'm adding products in my Wordpress dashboard it's all shifted and interrupting my actions. Example is in the image below.
Thanks
<img width="1192" alt="Screenshot 2019-04-16 at 2 54 41 AM" src="https://user-images.githubusercontent.com/49656769/56157966-605e5f80-5ff3-11e9-81cb-e1a2bc4ff0c6.png">
