### ISSUE TITLE
Simple Products display shortcodes in FB Shop, while Variable Products do not display all colors

### ISSUE THREAD

**Issue by Fomoria** [facebookincubator/facebook-for-woocommerce#574]
WP Version: 4.9.7
WC Version: 3.4.3
FB Plugin Version:
Products: 97

**Simple Products:**

Once you click on the product picture in the FB Shop, on the right side where you have the description, FB shows the shortcodes:

ie1.

Product Details
[vc_row css='.vc_custom_1528042266476{margin-bottom: 40px !important;}'][vc_column css_animation='fadeInDownBig' width='1/2' css='.vc_custom_1528042347602{margin-bottom: 25px !important;}'][vc_custom_heading text='DESCRIPTION' font_container='tag:h4|text_align:left' google_fonts='font_family:Enriqueta%3Aregular%2C700|font_style:400%20regular%3A400%3Anormal']

ie2.

[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row][vc_column][vc_column_text]Notes: 

**Variable Products**

This is less easy to explain. Let's say there's a product with various variations, from 3 up to 17. When you click on it, on the top left appear only 2 or 3 thumbnails out of many other variations. 

If you select a new variation from the drop down menu, it will display nothing, just a white square. The situation seems to normalize only if you start to play with it continuing to selecting other variations, at some point FB will actually load the pictures.

**Comment by jieminz22** [comment]
## Automated Support Message

Hello,

Thanks for your interest in our plugin!

If your issue is a feature request or feedback for the developers, reply with `Feature Request` or `Feedback`.
If you are a developer or have a question for the developers related to code, reply with `Developer Question`.
Your comment will be categorized accordingly, and we will read it and reply when we can.

If you have encountered a bug or a problem with the plugin, the steps below contain information to help you resolve the issue yourself and provide us information we need to help you with your problem.

## Search Existing Issues

**First, please [search our issues](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=) to see if your problem has been reported before.**
There may already be a workaround or a solution to your problem. You can search our issues using [the search bar near the top of our issues page](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=); be sure to search both _open_ and _closed_ issues.
If you do find a similar issue, leave a comment on that issue and close this one. Your comment helps us prioritize which existing issues are important and urgent.

## Common Resolution Methods

**If you are experiencing a problem or bug and have not found any similar issue, please try the following:**

* Upgrade to the latest version of the plugin.
* Try to `Resync` products using the button on the plugin config page
* Reset the plugin by selecting `Reconfigure > Advanced Options > Delete`, and setting up this plugin again.
* Try to deactivate other plugins that you think may be interfering, then reset and set up again.

## Necessary Information

**If the above steps did not help, please provide the following information in your next comment in order for us to debug your problem:**

* WooCommerce version
* WordPress version
* Plugin version (please note: we only support up-to-date versions of the plugin)
* A screenshot of where you see the problem (for example: if it is on Facebook, a screenshot of Facebook, if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.)
* The URL of your website
* The URL of your page
* The URL(s) of where you took your screenshot(s)
* (If applicable) Detailed steps you took in order to see the problem

Please include `Debug Ready` in your reply so our automated system can flag your issue for manual review. Please note that due to a high volume of issues, we may not be able to respond immediately.

Thanks for your patience,
The Facebook Dev Team (@mengyingdu, @dmitridr, @sammul, @jieminz22)

**Comment by Fomoria** [comment]
It's the same problem reported here https://github.com/facebookincubator/facebook-for-woocommerce/issues/547 and various time on GitHub plus on WooCommerce, I do not understand why you do not simply release an update to fix it

**Comment by dmitridr** [comment]
Hey thanks for flagging the similar issue. We're struggling with limited engineering power and time, and in this case it appears there's a workaround (unlike other bugs where there isn't). We would love it if you send us a pull request for this though! Happy to review that and include it in the next version, please consider contributing.

**Comment by diegokeepfit** [comment]
Hello! I hope you're all doing great.

Is there any solution for this? Thanks!

**Comment by mengyingdu** [comment]
## Automated Support Message - Issue Closed

Hello,

Because it has been 30 days since this issue was updated and you have not included `Debug Ready` in your reply, our automated system will now close your issue.
If you are still having this problem, please open a new issue and reference this one.

For more information on our response times and support policy, visit [Facebook Support on GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Facebook-Support-on-GitHub).

Thank you,
The Facebook Dev Team
