### ISSUE TITLE
Facebook products not syncing with woocommerce for facebook plug in

### ISSUE THREAD

**Issue by spiritualirishdancer** [facebookincubator/facebook-for-woocommerce#587]
![facebookforwoocommerceerror](https://user-images.githubusercontent.com/41486469/43017355-4dc3e5c0-8c45-11e8-84d8-93884e220719.png)
I have deactivated and deleted the plug in, cleared the firefox cache and reinstalled the plug in, but all the values from the previous install were still there. Also, I attempted to create a facebook icon, or whatever you call it, but I think something is not right with it.  I want to use the icon that comes with the plug in, but it didn't give me the option to use it.  Products are not syncing...I only have 3 products.

**Comment by mengyingdu** [comment]
## Automated Support Message

Hello,

Thanks for your interest in our plugin!

If your issue is a feature request or feedback for the developers, reply with `Feature Request` or `Feedback`.
If you are a developer or have a question for the developers related to code, reply with `Developer Question`.
If you are running ads with us, include `Advertiser` in your reply.

If you have encountered a bug or a problem with the plugin, the steps below contain information to help you resolve the issue yourself and provide us information we need to help you with your problem.

## Search Existing Issues

**First, please [search our issues](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=) to see if your problem has been reported before.**
There may already be a workaround or a solution to your problem. You can search our issues using [the search bar near the top of our issues page](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=); be sure to search both _open_ and _closed_ issues.
If you do find a similar issue, leave a comment on that issue and close this one. Your comment helps us prioritize which existing issues are important and urgent.

## Common Resolution Methods

**If you are experiencing a problem or bug and have not found any similar issue, please try the following:**

* Upgrade to the latest version of the plugin.
* Try to `Resync` products using the button on the plugin config page
* Reset the plugin by selecting `Reconfigure > Advanced Options > Delete`, and setting up this plugin again.
* Try to deactivate other plugins that you think may be interfering, then reset and set up again.

## Necessary Information

**If the above steps did not help, please provide the following information in your next comment in order for us to debug your problem:**

* WooCommerce version
* WordPress version
* Plugin version (please note: we only support up-to-date versions of the plugin)
* A screenshot of where you see the problem (for example: if it is on Facebook, a screenshot of Facebook, if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.)
* The URL of your website
* The URL of your page
* The URL(s) of where you took your screenshot(s)
* (If applicable) Detailed steps you took in order to see the problem

Please include `Debug Ready` in your reply so our automated system can flag your issue for manual review. Please note that due to a high volume of issues, we may not be able to respond immediately.

Thanks for your patience,
The Facebook Dev Team (@mengyingdu, @dmitridr, @sammul, @jieminz22)

**Comment by gervet** [comment]
In the last Update, the products syncing and the purchase event are not working. :(

**Comment by spiritualirishdancer** [comment]
When is it going to get fixed?


 
Spiritual Irish Dancer
Kathleen Desmond
SpiritualIrishDancer Headbands and Assessories for the Irish Dancer
www.spiritualirishdancer.com

**Comment by mengyingdu** [comment]
@spiritualirishdancer 
Even though your site is based on woocommerce, however, when i clicked on 'shop now', it redirects me a Etsy site.

I'm not sure how this going to work since this is a plugin for woocommerce.

**Comment by 93prabhat93** [comment]
I am facing the same issue. I can see the products in the plugin but not on my facebook shop.
Help if someone has found the solution

**Comment by dmitridr** [comment]
@93prabhat93 that's a different issue. Most likely you had an existing self-serve shop on the page, and so we didn't overwrite it, see #281 for how to enable it.

**Comment by spiritualirishdancer** [comment]
I didn’t have a shop before


 
Spiritual Irish Dancer
Kathleen Desmond
SpiritualIrishDancer Headbands and Assessories for the Irish Dancer
www.spiritualirishdancer.com

**Comment by dmitridr** [comment]
@spiritualirishdancer checking your page (I assume it's SpiritualIrishDancer... we're lacking in the `Necessary Information` requested by the auto-reply so we can't be sure... )  I see that your products are synced with FB. If so, it seems your issue has been resolved.

Please consider sharing what you did here to resolve the issue, it may help others who are searching. Closing this out.
