### ISSUE TITLE
Products not publishing on FB

### ISSUE THREAD

**Issue by wushantcm** [facebookincubator/facebook-for-woocommerce#589]
My products are not being published on FB.
I proceeded all these steps but still my products wont publish on FB. It shows that they are in processing status but wont publish. The plugin In formation shows all products are synced
![wstcm](https://user-images.githubusercontent.com/41537944/43044662-c1f37990-8daa-11e8-850d-6e69e5c2563b.PNG)

I checked all below settings:
    - Upgrade to the latest version of the plugin.
-     Try to Resync products using the button on the plugin config page
-     Reset the plugin by selecting Reconfigure > Advanced Options > Delete, and setting up this plugin again.
-     Try to deactivate other plugins that you think may be interfering, then reset and set up again.
but still no product is published on Facebook.
------------------------

    WooCommerce version: Version 3.4.3
    WordPress version:  Version 4.9.7
    Plugin version: Version 1.9.2
    A screenshot: 
![fb](https://user-images.githubusercontent.com/41537944/43044654-688efab4-8daa-11e8-8396-83cba376a8b1.PNG)

    The URL of your website: https://wushantcm.com/
    The URL of your page: https://www.facebook.com/wushantcm/
    The URL(s) of where you took your screenshot(s)
   https://www.facebook.com/pg/wushantcm/shop/?ref=page_internal

**Comment by mengyingdu** [comment]
## Automated Support Message

Hello,

Thanks for your interest in our plugin!

If your issue is a feature request or feedback for the developers, reply with `Feature Request` or `Feedback`.
If you are a developer or have a question for the developers related to code, reply with `Developer Question`.
If you are running ads with us, include `Advertiser` in your reply.

If you have encountered a bug or a problem with the plugin, the steps below contain information to help you resolve the issue yourself and provide us information we need to help you with your problem.

## Search Existing Issues

**First, please [search our issues](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=) to see if your problem has been reported before.**
There may already be a workaround or a solution to your problem. You can search our issues using [the search bar near the top of our issues page](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=); be sure to search both _open_ and _closed_ issues.
If you do find a similar issue, leave a comment on that issue and close this one. Your comment helps us prioritize which existing issues are important and urgent.

## Common Resolution Methods

**If you are experiencing a problem or bug and have not found any similar issue, please try the following:**

* Upgrade to the latest version of the plugin.
* Try to `Resync` products using the button on the plugin config page
* Reset the plugin by selecting `Reconfigure > Advanced Options > Delete`, and setting up this plugin again.
* Try to deactivate other plugins that you think may be interfering, then reset and set up again.

## Necessary Information

**If the above steps did not help, please provide the following information in your next comment in order for us to debug your problem:**

* WooCommerce version
* WordPress version
* Plugin version (please note: we only support up-to-date versions of the plugin)
* A screenshot of where you see the problem (for example: if it is on Facebook, a screenshot of Facebook, if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.)
* The URL of your website
* The URL of your page
* The URL(s) of where you took your screenshot(s)
* (If applicable) Detailed steps you took in order to see the problem

Please include `Debug Ready` in your reply so our automated system can flag your issue for manual review. Please note that due to a high volume of issues, we may not be able to respond immediately.

Thanks for your patience,
The Facebook Dev Team (@mengyingdu, @dmitridr, @sammul, @jieminz22)

**Comment by wushantcm** [comment]
Debug Ready

**Comment by wushantcm** [comment]
Debug Ready
Feature Request
by wushantcm

**Comment by wushantcm** [comment]
All neccessary Information have been sent before, thank you. Please take a look above

**Comment by mengyingdu** [comment]
Thanks for providing all the infomation @wushantcm 

I checked your site and catalog

1. All of your products have been synced, no worries:
![screen shot 2018-07-24 at 6 12 36 pm](https://user-images.githubusercontent.com/24535640/43174126-48992b5c-8f6d-11e8-8eab-0d94c90e561d.png)

2. However, they are set to invisible. 
![screen shot 2018-07-24 at 6 13 56 pm](https://user-images.githubusercontent.com/24535640/43174143-5d395e74-8f6d-11e8-87a8-4bb1e87c9e69.png)

Questions / next steps to check yourself:
1. Did you use WPML and set another language as default? (look around similar discussion about WPML)
2. Did you use other plugins which potentially incompatible with ours?

**Comment by wushantcm** [comment]
Thank you, I will go on do further investigation.

Important Warning: This message is intended for the use of the person or entity to which it is addressed and may contain information that is privileged and confidential, the disclosure of which is governed by applicable law. If the reader of this message is not the intended recipient, or the employee or agent responsible for delivering it to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this information is strictly prohibited.

Wushan TCM - Chinese Medical Network 
https://wushantcm.com/

**Comment by schreyers** [comment]
[SOLUTION]

To publish your synced products, do it from the catalog dashboard in your Facebook Ads Manager.

1. Select all products
2. Deactivate them all
3. Activate them all

This should set them all to published and available in your catalog.

**Comment by mrsroadrunner** [comment]
Gosh I am sorry i had not gotten back here -
I found my issue!! The issue was with facebook and my old personal page. As soon as I deleted my old personal page from the business page WHAM .... everything worked ! 
Thank you , and sorry i did not get back here when i fixed this!!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
