### ISSUE TITLE
How to delete pixel id from website

### ISSUE THREAD

**Issue by gauravango** [facebookincubator/facebook-for-woocommerce#598]
symptoms of your problem: wrong pixel id got updated on website during integration. Need to replace with new one. Want instructions how to un install the software so that the script in the backend software with pixel id gets deleted
   
    your Facebook page url: www.facebook.com/vangovagon
    your website url - www.vangovagon.com
    current version of Facebook-for-WooCommerce , WooCommerce, Wordpress, PHP - latest available

**Comment by dmitridr** [comment]
## Automated Support Message - Issue Closed

Hello,

Because it has been 30 days since this issue was updated and you have not included `Debug Ready` in your reply, our automated system will now close your issue.
If you are still having this problem, please open a new issue and reference this one.

For more information on our response times and support policy, visit [Facebook Support on GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Facebook-Support-on-GitHub).

Thank you,
The Facebook Dev Team
