### ISSUE TITLE
Filter products to be sync to Facebook

### ISSUE THREAD

**Issue by MrNghia123** [facebookincubator/facebook-for-woocommerce#605]
Hi,
I have a shop with thousands of products and I want to sync only selected products to Facebook shop. I cannot seem to find how to do it in the extension configuration.
Kind regards,
Nghia Huynh.

**Comment by jieminz22** [comment]
## Automated Support Message

Hello,

Thanks for your interest in our plugin!

If your issue is a feature request or feedback for the developers, reply with `Feature Request` or `Feedback`.
If you are a developer or have a question for the developers related to code, reply with `Developer Question`.
If you are running ads with us, include `Advertiser` in your reply.

If you have encountered a bug or a problem with the plugin, the steps below contain information to help you resolve the issue yourself and provide us information we need to help you with your problem.

## Search Existing Issues

**First, please [search our issues](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=) to see if your problem has been reported before.**
There may already be a workaround or a solution to your problem. You can search our issues using [the search bar near the top of our issues page](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=); be sure to search both _open_ and _closed_ issues.
If you do find a similar issue, leave a comment on that issue and close this one. Your comment helps us prioritize which existing issues are important and urgent.

## Common Resolution Methods

**If you are experiencing a problem or bug and have not found any similar issue, please try the following:**

* Upgrade to the latest version of the plugin.
* Try to `Resync` products using the button on the plugin config page
* Reset the plugin by selecting `Reconfigure > Advanced Options > Delete`, and setting up this plugin again.
* Try to deactivate other plugins that you think may be interfering, then reset and set up again.

## Necessary Information

**If the above steps did not help, please provide the following information in your next comment in order for us to debug your problem:**

* WooCommerce version
* WordPress version
* Plugin version (please note: we only support up-to-date versions of the plugin)
* A screenshot of where you see the problem (for example: if it is on Facebook, a screenshot of Facebook, if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.)
* The URL of your website
* The URL of your page
* The URL(s) of where you took your screenshot(s)
* (If applicable) Detailed steps you took in order to see the problem

Please include `Debug Ready` in your reply so our automated system can flag your issue for manual review. Please note that due to a high volume of issues, we may not be able to respond immediately.

Thanks for your patience,
The Facebook Dev Team (@mengyingdu, @dmitridr, @sammul, @jieminz22)

**Comment by scerbj** [comment]
I also am trying to do this same thing.

**Comment by g-gullstrand** [comment]
> Hi all,
> 
> If you are asking for a way to do this in the UI, you can hide all the products you do not want to upload using the `Hide` button or FB Visibility setting in the edit product page. Products hidden in this way will not appear to users who see your shop.
> 
> Alternatively, if you are a developer we provide a programmatic filter on the product upload that you may be able to use for this purpose.
> [The filter is here](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/includes/fbproduct.php#L506) it's called `facebook_for_woocommerce_integration_prepare_product`. If you write a function to hook into this filter you can check if you should upload the product or not and return a blank array if you decide not to upload it.
> 
> Hope that helps.
> I'm marking this as a feature request, because we do have a filter but it's not great for this use case, also I am not sure if you are asking about a UI option or not.

Is it possible to use the filter "facebook_for_woocommerce_integration_prepare_product" to fliter out product variations? In our shop we have products with variations only visible to wholesale customers (by custom meta key logic). I tried the following:

    function om_hide_restricted_products_from_facebook_store($product, $id){
	
	    if(get_post_meta( $id, '_wholesale_variation_checkbox', true) === "yes" ){
		    return array();
	    } 
	
	    return $product;
    }
    add_filter( 'facebook_for_woocommerce_integration_prepare_product', 'om_hide_restricted_products_from_facebook_store', 10, 2);`

But im not sure if the filters runs for variations so that the $id parameter is a variation id?

**Comment by btrfabrications** [comment]
+1 Need to have persistent control over which products sync. It's frustrating to delete products from FB every time they're updated in WooCommerce.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
