### ISSUE TITLE
Duplicate pixels on 

### ISSUE THREAD

**Issue by FoldAccessories** [facebookincubator/facebook-for-woocommerce#606]
Hi I have installed the Facebook for WooCommerce plugin and set up everything correctly, however, I seem to have two Pixels on my site: They are 'Fold Accessories pixel' and 'Fold Accessories's pixel'

When I go to Business settings it only shows: 'Fold Accessories's pixel' which says it is not set up yet.
And I cannot see or add: 'Fold Accessories pixel' which is the one gathering the data.

It seems I cannot have my Instagram shop/product tagging setup unless I resolve this issue.
Is there a way I can delete all and restart? 

See the attached image of the duplicate pixel 
![screenshot 2018-08-02 17 11 26](https://user-images.githubusercontent.com/41855956/43568153-3835a89c-9677-11e8-8b17-c1aaf57e3d95.png)

**Comment by FoldAccessories** [comment]
Debug Ready

WooCommerce version:
Version 3.4.4

WordPress version:
Version 4.9.7

Plugin version:
Version 1.9.2

The URL of your website:
https://foldaccessories.com/

The URL of your page:
https://www.facebook.com/foldaccessoriescom/

The URL(s) of where you took your screenshot(s): https://www.dropbox.com/s/nwh0a5jnf5jj225/Screenshot%202018-08-02%2017.25.10.png?dl=0
https://www.facebook.com/analytics/?nav_source=mega_menu

![screenshot 2018-08-02 17 25 10](https://user-images.githubusercontent.com/41855956/43568955-6ccdd690-9679-11e8-9d0e-914aee7dfac0.png)
![screenshot 2018-08-02 17 27 31](https://user-images.githubusercontent.com/41855956/43568956-6d08f540-9679-11e8-86ec-e25faa327e9b.png)

**Comment by jieminz22** [comment]
## Automated Support Message

Hello,

Thanks for your interest in our plugin!

If your issue is a feature request or feedback for the developers, reply with `Feature Request` or `Feedback`.
If you are a developer or have a question for the developers related to code, reply with `Developer Question`.
If you are running ads with us, include `Advertiser` in your reply.

If you have encountered a bug or a problem with the plugin, the steps below contain information to help you resolve the issue yourself and provide us information we need to help you with your problem.

## Search Existing Issues

**First, please [search our issues](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=) to see if your problem has been reported before.**
There may already be a workaround or a solution to your problem. You can search our issues using [the search bar near the top of our issues page](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=); be sure to search both _open_ and _closed_ issues.
If you do find a similar issue, leave a comment on that issue and close this one. Your comment helps us prioritize which existing issues are important and urgent.

## Common Resolution Methods

**If you are experiencing a problem or bug and have not found any similar issue, please try the following:**

* Upgrade to the latest version of the plugin.
* Try to `Resync` products using the button on the plugin config page
* Reset the plugin by selecting `Reconfigure > Advanced Options > Delete`, and setting up this plugin again.
* Try to deactivate other plugins that you think may be interfering, then reset and set up again.

## Necessary Information

**If the above steps did not help, please provide the following information in your next comment in order for us to debug your problem:**

* WooCommerce version
* WordPress version
* Plugin version (please note: we only support up-to-date versions of the plugin)
* A screenshot of where you see the problem (for example: if it is on Facebook, a screenshot of Facebook, if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.)
* The URL of your website
* The URL of your page
* The URL(s) of where you took your screenshot(s)
* (If applicable) Detailed steps you took in order to see the problem

Please include `Debug Ready` in your reply so our automated system can flag your issue for manual review. Please note that due to a high volume of issues, we may not be able to respond immediately.

Thanks for your patience,
The Facebook Dev Team (@mengyingdu, @dmitridr, @sammul, @jieminz22)

**Comment by jieminz22** [comment]
Hi @FoldAccessories,

'Fold Accessories pixel' is the one installed by the extension and is live. I'm not sure where 'Fold Accessories's pixel' came from. Did you create it manually before? In any case it shouldn't matter though. What problem do you have when you try to use 'Fold Accessories pixel'?

**Comment by FoldAccessories** [comment]
Hi There,

Thanks for your response!

In Business settings I can only see the new pixel 'Fold Accessories's pixel’ and not the actual live pixel 'Fold Accessories pixel’. (image attached)
I try to add it but it cannot find it under name or ID - the only way i can see the live pixel is under the ‘Analytics’ Tab (image attached)

I am concerned it is not correctly linked to my account and this is why I am unable to setup Shopping or Product tagging on my Instagram.
It mentions it will take about 3 days to be reviewed then it will come live, however mine is still not providing any options.

The plugin didn’t set up my catalogs, an also said i Had no pixels setup hence why there is a duplicate.

IS there anything you could do to please check that i have everything running correctly? and that i can setup my Instagram Shop / tagging?

Please let me know if you need any further details from me.

Regards,
Simon

**Comment by FoldAccessories** [comment]
Can I re-install facebook for woocommerce to see if I can choose the active pixel to use?
I cannot select the pixel that is active anywhere in settings. Please let me know.

**Comment by dmitridr** [comment]
Hi @FoldAccessories , if you go to the plugin's config page and go to `Settings` > `Pixel` you should be able to see the pixels you can select.

If you don't see the pixel you want... Try attaching the pixel you want to use to an ad account, See #164 for the discussion about how to do that. Once you make this attachment it should show up in the selector. 

Hope that helps.

**Comment by FoldAccessories** [comment]
Hi @dmitridr

Thanks for your reply, I have reset the settings and attached the pixel 'Fold Accessories's pixel’
which seems to be set up ok now. I still though do not get the option to set up my shopping or product tagging on my Instagram. Do you have any thoughts on why it is not being activated? Really keen to get this function going!

**Comment by dmitridr** [comment]
Hi @FoldAccessories 

Great, glad it helped. We are working on adding IG Shopping as an official part of the plugin soon (eta few months) but it's not ready yet. There are some other merchants who have reported success setting up IG Shopping/Tagging with our plugin (search our issues for `Instagram`) using Business Manager already. I'm honestly not quite sure how they managed that, but if you search around and comment in those issues, maybe you can find out. 

I did hear there was a regional restriction for this feature for now, so that could be one reason why you don't see the option yet.
