### ISSUE TITLE
Undefined index: fb_pixel_id, Undefined index: fb_api_key

### ISSUE THREAD

**Issue by slgithubacc** [facebookincubator/facebook-for-woocommerce#608]
Hi,
I'm trying to install version 1.9.2 on WP 4.9.7 with WC 3.4.4 for https://www.stylelyrical.com/shop to have products sync to https://www.facebook.com/pg/stylelyrical/shop/ and then use shoppable Instagram tags.

I've tried with the version from the WooCommerce shop, the version from Facebook Events Manager > Partner Integrations and the current GitHub version, but I am unable to set up any of them. After installing I get:

Notice: Undefined index: fb_pixel_id in ../wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php on line 48 (line 50 in the current GitHub version):

```
  public function init_pixel() {
    WC_Facebookcommerce_Pixel::initialize();

    // Migrate WC customer pixel_id from WC settings to WP options.
    // This is part of a larger effort to consolidate all the FB-specific
    // settings for all plugin integrations.
    if (is_admin()) {
      $pixel_id = WC_Facebookcommerce_Pixel::get_pixel_id();
      $settings_pixel_id = (string)$this->settings['fb_pixel_id'];
      if (
        WC_Facebookcommerce_Utils::is_valid_id($settings_pixel_id) &&
        (!WC_Facebookcommerce_Utils::is_valid_id($pixel_id) ||
          $pixel_id != $settings_pixel_id
        )
      ) {
        WC_Facebookcommerce_Pixel::set_pixel_id($settings_pixel_id);
      }
    }

```

If I go to Integration settings in WC I get one more error:

Notice: Undefined index: fb_api_key in ../wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php on line 1905

In wp_options I have:

![wp_options](https://user-images.githubusercontent.com/42044935/43605180-25ba64a4-9687-11e8-9dd5-1e5a963f1b1c.png)

I've tried uninstalling/reinstalling, deleting the records in wp_options, trying to figure out how to manually add the values to the record, but without luck.

Hitting Get Started does nothing, just throws a JavaScript error:
![setup](https://user-images.githubusercontent.com/42044935/43605363-9b342724-9687-11e8-977a-25c9959e8888.png)

![jserror](https://user-images.githubusercontent.com/42044935/43605400-bace0ece-9687-11e8-90e2-cbcca0efd8e7.png)

Do you have any suggestions as to what is wrong and how I correct it?

Thanks.

**Comment by jieminz22** [comment]
## Automated Support Message

Hello,

Thanks for your interest in our plugin!

If your issue is a feature request or feedback for the developers, reply with `Feature Request` or `Feedback`.
If you are a developer or have a question for the developers related to code, reply with `Developer Question`.
If you are running ads with us, include `Advertiser` in your reply.

If you have encountered a bug or a problem with the plugin, the steps below contain information to help you resolve the issue yourself and provide us information we need to help you with your problem.

## Search Existing Issues

**First, please [search our issues](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=) to see if your problem has been reported before.**
There may already be a workaround or a solution to your problem. You can search our issues using [the search bar near the top of our issues page](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=); be sure to search both _open_ and _closed_ issues.
If you do find a similar issue, leave a comment on that issue and close this one. Your comment helps us prioritize which existing issues are important and urgent.

## Common Resolution Methods

**If you are experiencing a problem or bug and have not found any similar issue, please try the following:**

* Upgrade to the latest version of the plugin.
* Try to `Resync` products using the button on the plugin config page
* Reset the plugin by selecting `Reconfigure > Advanced Options > Delete`, and setting up this plugin again.
* Try to deactivate other plugins that you think may be interfering, then reset and set up again.

## Necessary Information

**If the above steps did not help, please provide the following information in your next comment in order for us to debug your problem:**

* WooCommerce version
* WordPress version
* Plugin version (please note: we only support up-to-date versions of the plugin)
* A screenshot of where you see the problem (for example: if it is on Facebook, a screenshot of Facebook, if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.)
* The URL of your website
* The URL of your page
* The URL(s) of where you took your screenshot(s)
* (If applicable) Detailed steps you took in order to see the problem

Please include `Debug Ready` in your reply so our automated system can flag your issue for manual review. Please note that due to a high volume of issues, we may not be able to respond immediately.

Thanks for your patience,
The Facebook Dev Team (@mengyingdu, @dmitridr, @sammul, @jieminz22)

**Comment by slgithubacc** [comment]
Debug Ready
WooCommerce version: 3.4.4
WordPress version: 4.9.7
Plugin version: 1.9.2
A screenshot of where you see the problem
![setup](https://user-images.githubusercontent.com/42044935/43607850-0210e728-968f-11e8-8760-636af8191c0b.png)

The URL of your website: https://www.stylelyrical.com/shop
The URL of your page: https://www.facebook.com/stylelyrical
The URL(s) of where you took your screenshot(s): https://stylelyrical.com/wp-admin//admin.php?page=wc-settings&tab=integration&section=facebookcommerce
Detailed steps you took in order to see the problem: Upload and activate plugin, click banner to complete the setup steps.
No other pixel/facebook plugins are installed.

**Comment by dmitridr** [comment]
Hey. Thanks for reporting this, it looks like this is because you have strict settings for PHP enabled these warnings are halting PHP execution, normally warnings wouldn't do that.

We will fix them for the next version, as a workaround you can try removing the lines causing the problem using the WP Plugin editor. Line 1905 can be changed to `$api_key_invalid = false;`, line 48 can be changed to `$settings_pixel_id = null;`.

**Comment by dmitridr** [comment]
Hey @slgithubacc can you try our new release [v1.9.4](https://github.com/facebookincubator/facebook-for-woocommerce/releases) it should fix the warnings, but I'm not sure if you still have the other problem?

**Comment by dmitridr** [comment]
Closing as there has been no reply.
