### ISSUE TITLE
Plugin Compatibility Issue : AvaTax plugin causes error - unable to see products.

### ISSUE THREAD

**Issue by MadIcarusMedia** [facebookincubator/facebook-for-woocommerce#61]
Catchable fatal error: Object of class WP_Post could not be converted to string 
Might be an issue with a same named variable or a global variable?

**Comment by dmitridr** [comment]
Hi,

This is troubling. Can you give us any more info, like a stack trace? Otherwise we don't know where the problem could be.

**Comment by dmitridr** [comment]
I'm marking this as a feature request to support compatibility with AvaTax. In general, if there is a compatibility issue, the workaround would be to disable the other plugin, set up with Facebook, then enable the plugin again.

**Comment by mengyingdu** [comment]
Hi @MadIcarusMedia,

There's an workable solution for this error: https://stackoverflow.com/questions/15009005/getting-object-of-class-wp-post-could-not-be-converted-to-string-when-it-is

In order to find which line raise this error and change it, you need to look into your local log. If you can  paste here, we can help take a look. Thanks.

**Comment by lgfogle** [comment]
Hey all,

I'm going to close this issue since it's been several years and many updates for both WooCommerce AvaTax and Facebook for WooCommerce since this was initially reported. If this problem is still occurring on the latest versions of both plugins, could you please open a new issue with steps to replicate?

Thank you!
Lindsey
