### ISSUE TITLE
fbq('consent', 'revoke')

### ISSUE THREAD

**Issue by addedlovely** [facebookincubator/facebook-for-woocommerce#610]
Hello.

We'd like to use the revoke consent feature listed here:
https://developers.facebook.com/docs/facebook-pixel/events-advanced-use-cases/v3.0

But you haven't provided any hooks or filters to be able to inject that after the tracking script is initially loaded. Adding a filter here: https://github.com/facebookincubator/facebook-for-woocommerce/blob/3c858c9ba535a1c9cf7603ee418e3adc80117c26/facebook-commerce-pixel-event.php#L21 would solve the issue.

Thanks.

Ian.

**Comment by jieminz22** [comment]
## Automated Support Message

Hello,

Thanks for your interest in our plugin!

If your issue is a feature request or feedback for the developers, reply with `Feature Request` or `Feedback`.
If you are a developer or have a question for the developers related to code, reply with `Developer Question`.
If you are running ads with us, include `Advertiser` in your reply.

If you have encountered a bug or a problem with the plugin, the steps below contain information to help you resolve the issue yourself and provide us information we need to help you with your problem.

## Search Existing Issues

**First, please [search our issues](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=) to see if your problem has been reported before.**
There may already be a workaround or a solution to your problem. You can search our issues using [the search bar near the top of our issues page](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=); be sure to search both _open_ and _closed_ issues.
If you do find a similar issue, leave a comment on that issue and close this one. Your comment helps us prioritize which existing issues are important and urgent.

## Common Resolution Methods

**If you are experiencing a problem or bug and have not found any similar issue, please try the following:**

* Upgrade to the latest version of the plugin.
* Try to `Resync` products using the button on the plugin config page
* Reset the plugin by selecting `Reconfigure > Advanced Options > Delete`, and setting up this plugin again.
* Try to deactivate other plugins that you think may be interfering, then reset and set up again.

## Necessary Information

**If the above steps did not help, please provide the following information in your next comment in order for us to debug your problem:**

* WooCommerce version
* WordPress version
* Plugin version (please note: we only support up-to-date versions of the plugin)
* A screenshot of where you see the problem (for example: if it is on Facebook, a screenshot of Facebook, if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.)
* The URL of your website
* The URL of your page
* The URL(s) of where you took your screenshot(s)
* (If applicable) Detailed steps you took in order to see the problem

Please include `Debug Ready` in your reply so our automated system can flag your issue for manual review. Please note that due to a high volume of issues, we may not be able to respond immediately.

Thanks for your patience,
The Facebook Dev Team (@mengyingdu, @dmitridr, @sammul, @jieminz22)

**Comment by addedlovely** [comment]
Feature Request 
Developer 
Advertiser

**Comment by dmitridr** [comment]
Hi @addedlovely 

Thanks for your interest. We can add a filter where you say but it seems like it won't help you call revoke/consent without some string manipulation.

I think the filter would work better here, https://github.com/facebookincubator/facebook-for-woocommerce/blob/3c858c9ba535a1c9cf7603ee418e3adc80117c26/facebook-commerce-pixel-event.php#L253 since according to the docs you sent revoke must be called before `fbq('init', ...)`. Please confirm if you agree that's what you need, and we can add it. 

You're also welcome to send us a pull request, that way there's no possibility we add something you can't use.

**Comment by addedlovely** [comment]
@dmitridr thanks for the reply. Ah yes - your suggested line is a better place for it - saves mucking around with injecting it in between the <script> tags.

Not sure what your naming convention is for filters, 'facebook_woocommmerce_init' maybe?

**Comment by mengyingdu** [comment]
wow Thank you! @addedlovely

**Comment by dmitridr** [comment]
Thanks @addedlovely. We'll release 1.9.4 shortly with the filter you added, closing this out.

@mengyingdu we should start documenting our filters. I think we have at least 4 now. What do you think?
