### ISSUE TITLE
Business Integrity : Products in 'Processing' State Forever

### ISSUE THREAD

**Issue by Radioguy1** [facebookincubator/facebook-for-woocommerce#611]
Hi 

Hi For some reason mine has been processing for over 4 days
Some products (About 1/3) have processed and others say Processing
I redid the settings 2 times but same result.
Sure hope you can help
Thank you in advance

My FB page: https://www.facebook.com/navallstoreonline
Shop Page: https://www.facebook.com/pg/navallstoreonline
Website: www.navallstore.com.com

**Comment by jieminz22** [comment]
## Automated Support Message

Hello,

Thanks for your interest in our plugin!

If your issue is a feature request or feedback for the developers, reply with `Feature Request` or `Feedback`.
If you are a developer or have a question for the developers related to code, reply with `Developer Question`.
If you are running ads with us, include `Advertiser` in your reply.

If you have encountered a bug or a problem with the plugin, the steps below contain information to help you resolve the issue yourself and provide us information we need to help you with your problem.

## Search Existing Issues

**First, please [search our issues](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=) to see if your problem has been reported before.**
There may already be a workaround or a solution to your problem. You can search our issues using [the search bar near the top of our issues page](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=); be sure to search both _open_ and _closed_ issues.
If you do find a similar issue, leave a comment on that issue and close this one. Your comment helps us prioritize which existing issues are important and urgent.

## Common Resolution Methods

**If you are experiencing a problem or bug and have not found any similar issue, please try the following:**

* Upgrade to the latest version of the plugin.
* Try to `Resync` products using the button on the plugin config page
* Reset the plugin by selecting `Reconfigure > Advanced Options > Delete`, and setting up this plugin again.
* Try to deactivate other plugins that you think may be interfering, then reset and set up again.

## Necessary Information

**If the above steps did not help, please provide the following information in your next comment in order for us to debug your problem:**

* WooCommerce version
* WordPress version
* Plugin version (please note: we only support up-to-date versions of the plugin)
* A screenshot of where you see the problem (for example: if it is on Facebook, a screenshot of Facebook, if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.)
* The URL of your website
* The URL of your page
* The URL(s) of where you took your screenshot(s)
* (If applicable) Detailed steps you took in order to see the problem

Please include `Debug Ready` in your reply so our automated system can flag your issue for manual review. Please note that due to a high volume of issues, we may not be able to respond immediately.

Thanks for your patience,
The Facebook Dev Team (@mengyingdu, @dmitridr, @sammul, @jieminz22)

**Comment by Radioguy1** [comment]
DEBUG READY

Woocommerce Version 4.9.8
WordPress 4.9.8
Facebook for WooCommerce Version 1.9.2
![screenshot navallstoreonline](https://user-images.githubusercontent.com/42013801/43676180-e3e7c3ee-97b9-11e8-8879-0403dead407e.png)

My FB page: https://www.facebook.com/navallstoreonline
Shop Page: https://www.facebook.com/pg/navallstoreonline
Website: www.navallstore.com.com
Screenshot URL https://www.facebook.com/pg/navallstoreonline/shop/?ref=page_internal
I Uninstalled and reinstalled the Plug in 2 times

**Comment by scerbj** [comment]
I also have this same issue.  Hoping to find a fix.

**Comment by mengyingdu** [comment]
@Radioguy1 
It completed processing now. 
<img width="933" alt="screen shot 2018-08-06 at 7 42 54 am" src="https://user-images.githubusercontent.com/24535640/43723399-67358fea-994c-11e8-8282-bd110806ff94.png">

**Comment by Radioguy1** [comment]
@mengyingdu 

Sorry, but those are done thatg you screen shot but theer are still about 100 Items Not Processed and Showing as Processing . Thank you for looking 
![image](https://user-images.githubusercontent.com/42013801/43724258-856b73ce-9967-11e8-909e-df72025f7442.png)

**Comment by Radioguy1** [comment]
Well we tried as you outlined but the result is exactly the same

**Comment by dmitridr** [comment]
Hey, thanks for trying that. I've passed this task over to the Business Integrity team which is responsible for reviewing products that come into Facebook. Hopefully they will be able to resolve this issue for you, I'd ask that you please refrain from deleting your products in the short term so that it's easier for them to debug.

**Comment by Radioguy1** [comment]
Thank you Dimitri

We have another Facebook Shop and I tried and got the same result 
basically
Some Okay and SOme perpetually processing



------ Original Message ------

**Comment by vn1ta** [comment]
I have been adding products to my Facebook store today and I noticed that, while some products that I added later are processed and approved, there are 13 other products that are stuck on processing entire day.

Additionally, I am unable to create a collection with specific category of products because Facebook list doesn't display all of the products (it shows 6 out of 20+ products that should be added to the collection Women's T-shirts & Tops).

Please help.
Thank you for your time!
Anita

**Comment by jakestpeter** [comment]
I'm experiencing this issue as well. 
![PastedGraphic-2](https://user-images.githubusercontent.com/7673228/66141816-598fcd00-e5d2-11e9-94dd-ee4c728cb72b.png)
![PastedGraphic-4](https://user-images.githubusercontent.com/7673228/66141823-5d235400-e5d2-11e9-86a3-05000bc74c82.png)

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
