### ISSUE TITLE
Automatic catalog update

### ISSUE THREAD

**Issue by Yizi** [facebookincubator/facebook-for-woocommerce#614]
Is this possible? are there any plans for this, at this point only manual submission is available.

**Comment by Yizi** [comment]
Ignore this, it's a issue with Pixel setup and it does automatically update

**Comment by mengyingdu** [comment]
## Automated Support Message - Issue Closed

Hello,

Because it has been 30 days since this issue was updated and you have not included `Debug Ready` in your reply, our automated system will now close your issue.
If you are still having this problem, please open a new issue and reference this one.

For more information on our response times and support policy, visit [Facebook Support on GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Facebook-Support-on-GitHub).

Thank you,
The Facebook Dev Team
