### ISSUE TITLE
Pixel already added using Business Manager

### ISSUE THREAD

**Issue by minimallinux** [facebookincubator/facebook-for-woocommerce#623]
Hi, I already added the pixel prviously using business manager, plugin says that there is more than one account and says to install a pixel. I already did so its a bit confusing. What is best way to use pixel I have already added? Thanks

**Comment by LouDivine** [comment]
I found out what part of my problem was - and it was related to Facebook Business Manager. I wasn't added as a Person/Role under the Ad Account and Pixel source, so I literally had to add my own name to those in Business Manager for it to associate what I was trying to do in the plugin setup. That's probably not part of your problem as I was doing it on behalf of someone else. So then what I ended up doing is removing the existing pixel from the site header, and linking to it from the Facebook for WooCommerce plugin. Set the Shop up and the source code is confirming that the pixel and the shop is all linked to the WooCommerce store. Fingers crossed the shopping tagging appears in the next few days.

**Comment by mengyingdu** [comment]
## Automated Support Message - Issue Closed

Hello,

Because it has been 30 days since this issue was updated and you have not included `Debug Ready` in your reply, our automated system will now close your issue.
If you are still having this problem, please open a new issue and reference this one.

For more information on our response times and support policy, visit [Facebook Support on GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Facebook-Support-on-GitHub).

Thank you,
The Facebook Dev Team
