### ISSUE TITLE
PHP Notices on checkout

### ISSUE THREAD

**Issue by glagonikas** [facebookincubator/facebook-for-woocommerce#625]
The most recent version of the plugin (1.9.3) is throwing some PHP notices on the checkout page.

> WC_Subscription::get_date was called with an argument that is deprecated since version 2.2.0. The "start" date type parameter has been deprecated to align date types with improvements to date APIs in WooCommerce 3.0, specifically the introduction of a new "date_created" API. Use "date_created"
> WC_Subscription::get_date was called with an argument that is deprecated since version 2.2.0. The "last_payment" date type parameter has been deprecated due to ambiguity (it actually returns the date created for the last order) and to align date types with improvements to date APIs in WooCommerce 3.0, specifically the introduction of a new "date_paid" API. Use "last_order_date_created" or "last_order_date_paid"

Those are caused by https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/facebook-commerce-events-tracker.php#L343 and https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/facebook-commerce-events-tracker.php#L346 and should be updated to date_created and last_order_date_created or last_order_date_paid.

**Comment by jieminz22** [comment]
## Automated Support Message

Hello,

Thanks for your interest in our plugin!

If your issue is a feature request or feedback for the developers, reply with `Feature Request` or `Feedback`.
If you are a developer or have a question for the developers related to code, reply with `Developer Question`.
If you are running ads with us, include `Advertiser` in your reply.

If you have encountered a bug or a problem with the plugin, the steps below contain information to help you resolve the issue yourself and provide us information we need to help you with your problem.

## Search Existing Issues

**First, please [search our issues](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=) to see if your problem has been reported before.**
There may already be a workaround or a solution to your problem. You can search our issues using [the search bar near the top of our issues page](https://github.com/facebookincubator/facebook-for-woocommerce/issues?q=); be sure to search both _open_ and _closed_ issues.
If you do find a similar issue, leave a comment on that issue and close this one. Your comment helps us prioritize which existing issues are important and urgent.

## Common Resolution Methods

**If you are experiencing a problem or bug and have not found any similar issue, please try the following:**

* Upgrade to the latest version of the plugin.
* Try to `Resync` products using the button on the plugin config page
* Reset the plugin by selecting `Reconfigure > Advanced Options > Delete`, and setting up this plugin again.
* Try to deactivate other plugins that you think may be interfering, then reset and set up again.

## Necessary Information

**If the above steps did not help, please provide the following information in your next comment in order for us to debug your problem:**

* WooCommerce version
* WordPress version
* Plugin version (please note: we only support up-to-date versions of the plugin)
* A screenshot of where you see the problem (for example: if it is on Facebook, a screenshot of Facebook, if it is on WooCommerce, a screenshot of WooCommerce. If it is in multiple places, multiple screenshots.)
* The URL of your website
* The URL of your page
* The URL(s) of where you took your screenshot(s)
* (If applicable) Detailed steps you took in order to see the problem

Please include `Debug Ready` in your reply so our automated system can flag your issue for manual review. Please note that due to a high volume of issues, we may not be able to respond immediately.

Thanks for your patience,
The Facebook Dev Team (@mengyingdu, @dmitridr, @sammul, @jieminz22)

**Comment by glagonikas** [comment]
Debug Ready

All details are explained on the initial post

WooCommerce version 3.4.4
WordPress version 4.9.8
Plugin version (please note: we only support up-to-date versions of the plugin) 1.9.3

**Comment by mengyingdu** [comment]
please fix it since  it's introduced by your commit @longcfb

**Comment by mengyingdu** [comment]
It's been fix by @longcfb and we will include it in next version. Thanks for the report!
