### ISSUE TITLE
throwing Warning at checkout

### ISSUE THREAD

**Issue by auludag** [facebookincubator/facebook-for-woocommerce#633]
hi:
Environment:
Wordpress v. 4.9.8
WooCommerce v 3.4.4
Facebook for WooCommere v 1.9.3

facebook for WooCommerce throwing warning at order received page like this:

 

> "Use of undefined constant wcs_get_subscriptions_for_order - assumed 'wcs_get_subscriptions_for_order' (this will throw an Error in a future version of PHP) in /srv/users/royalmondshop/apps/royalmondshop/public/wp-content/plugins/facebook-for-woocommerce/facebook-commerce-events-tracker.php on line 329"

**Comment by mengyingdu** [comment]
@auludag 
This was fixed by @longcfb in [commit](https://github.com/facebookincubator/facebook-for-woocommerce/commit/8f047d47e9710aac83242bcffeb6f16102f70fb5). Please upgrade to [v1.9.5](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.9.5) 

Let me know if you still have this issue.
