### ISSUE TITLE
v 1.9.5 how set event  Injection?

### ISSUE THREAD

**Issue by vucumbra** [facebookincubator/facebook-for-woocommerce#635]
Hi
I not have understand how can i find the setting for consent or revoke event to pixel in new relase
Can you help?
Thank's  a lot

**Comment by mengyingdu** [comment]
## Automated Support Message - Issue Closed

Hello,

Because it has been 30 days since this issue was updated and you have not included `Debug Ready` in your reply, our automated system will now close your issue.
If you are still having this problem, please open a new issue and reference this one.

For more information on our response times and support policy, visit [Facebook Support on GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Facebook-Support-on-GitHub).

Thank you,
The Facebook Dev Team
