### ISSUE TITLE
Making products hidden consistently caused connect lost message in Wordpress

### ISSUE THREAD

**Issue by jimmyjinkz** [facebookincubator/facebook-for-woocommerce#64]
When trying to hide products on the Facebook shop a connection lost message is shown in Wordpress.

The steps take:

1. edit product in Wordpress
2. deselect the visible check box in the facebook settings for the product
3. click Update for that product

![screen shot 2017-09-30 at 14 29 49](https://user-images.githubusercontent.com/32415240/31046298-09665cde-a5ee-11e7-90d6-39b5adb0d9c4.png)

The product is then marked in facebook as not published when logged in as page editor. 

![screen shot 2017-09-30 at 14 35 23](https://user-images.githubusercontent.com/32415240/31046300-16c4f7dc-a5ee-11e7-83ea-a5238a1d134b.png)

But is visible when not logged in.

![screen shot 2017-09-30 at 14 35 13](https://user-images.githubusercontent.com/32415240/31046303-1f20549e-a5ee-11e7-9ede-0e0444b34aee.png)

**Comment by dmitridr** [comment]
Hello,

I checked the product in question, weirdly enough the status says published, so I'm not sure why you're getting the message. 

- Could you tell us your plugin version #? We recommend installing the latest one.
- Could you try using the 'Hide' button in the bulk editor to hide the product? Does it have the same problem?

**Comment by jimmyjinkz** [comment]
Hello

The plugin is 1.6.1 (the latest version WooCommerce are providing at the moment).

The button on the bulk product editor page changes between Hide and Show without throwing an error, the results of hiding the product are:

1. when logged in on the Facebook shop page, the product is visible just like all the others - there is no 'not published' label for the product

2. when the product is clicked whilst logged in on the Facebook shop page, the product opens and does display the label that the product is not published

3. when the facebook shop is viewed logged out, the product is visible

This is strange as the plugin has marked Partner Fitted Wheel Protectors as 'not published' and doesn't show them when viewed logged out.

I've updated to 1.6.2 from github and have retested hiding and showing the product from the bulk editor. The functionality remains the same as for v1.6.1. I'm also getting the same 'Connection Lost' error when toggling visibility from the edit product screen for that specific product.

Not sure if this is related, but since activating the plugin, it's made the load time for opening and updating products increase.

**Comment by dmitridr** [comment]
Thanks for the detailed reply.

Hmm. Given that we aren't seeing others report this issue, I suspect the 'Connection Lost' may be a compatibility issue with another plugin. 

I tried an update on our test servers with a similar product to this one, and I was not able to reproduce this problem : the product has the non-published warning, but it is hidden in incognito mode and not visible, unlike in your screenshot.

Do you have any ideas about any extensions you have that could be causing a conflict with the saving behavior?

**Comment by jimmyjinkz** [comment]
Hi

I deactivated all plugins on my site apart from WooCommerce and Facebook for WooCommerce, but the problem persists even then:

- on product page clicked visible and update - confirmed product on facebook updated but no change to price or visibility
- on product page clicked to make not visible and update - got a 502 timeout error, which I got with all plugins enabled too (either the 502 or connection lost or connection lost then 502)

I'm left scratching my head now as not sure what else to try :-)

**Comment by dmitridr** [comment]
Seems like a very strange issue, I'm not exactly sure what it could be either... a very unique server configuration? Could it be you have a very strict timeout set for the DB connection and it is timing out with our plugin because of the extra DB calls?

I tried a basic search for other versions of this problem, are you using a shared hosting provider? If so it may be a problem with the [heartbeat API](http://blogician.com/wordpress-connection-lost-heartbeat-plugin/). There's [a lot of other online posts](https://www.google.com/search?q=connection+lost+wordpress) about others with this issue, perhaps one of those solutions will be helpful, but it's not clear to me which one could be applicable to you.

Thanks for trying to disable the other extensions even though it didn't work.

One more thing I recommend trying is checking your server's PHP logs to see if there are any exceptions during the time you see the 'connection lost' message, particularly any exceptions mentioning 'facebook'? Please paste them here or email them to us at ads_extension_woocommerce@fb.com if you find any, those could be helpful.

**Comment by jimmyjinkz** [comment]
Hi

I upgraded to v1.6.6 today and resynced.

After that, I was able to change product visibility from the product pages in Woo. I still saw connection lost, but then the page reloaded and confirmed facebook had been updated.

Thanks for your help!
