### ISSUE TITLE
Facebook Products still processing / Therefore Instagram Tagging not being approved

### ISSUE THREAD

**Issue by samburger96** [facebookincubator/facebook-for-woocommerce#703]
Hi there,

I am having an issue with setting up my Facebook shop for Instagram Product tagging approval. I've synced my shop (http://www.karmaclothing.co.za/product-categories/) with the Facebook for Woocommerce plugin. It's populated the shop on Facebook, however the products state that they are still processing after 4 days: https://www.facebook.com/karmacorporatewearclothing/shop/

Why is this? I am needing to troubleshoot urgently as I need to make sure everything is in line for Instagram product tagging to be approved as I have also had issues with the tagging on Instagram not being accessible after setting up the shop.

Please advise. Thank you so much.

**Comment by Martystl** [comment]
I am having the same issues.  Some of my products have processed, but  most of them have not.  I have gone into advance and removed the settings and then recreated everything. After 7 days, still have products that hasn't processed yet.  
Web site:  Martyknightphotography.com
Shop:  http://www.martyknightphotography.com/shop/
Facebook shop:  https://www.facebook.com/pg/martyknightphotography/shop/
Facebook:  https://www.facebook.com/martyknightphotography/
Version 1.9.6

**Comment by Luther2010** [comment]
## Automated Support Message - Issue Closed

Hello,

Because it has been 30 days since this issue was updated and you have not included `Debug Ready` in your reply, our automated system will now close your issue.
If you are still having this problem, please open a new issue and reference this one.

For more information on our response times and support policy, visit [Facebook Support on GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Facebook-Support-on-GitHub).

Thank you,
The Facebook Dev Team

**Comment by madisonbess** [comment]
My shop products have bene processing for over a week now! I need help.
No website just a facebook shop.

Shop : https://www.facebook.com/foreverslime.bella/

Thank you
<img width="982" alt="Screen Shot 2019-04-29 at 4 57 20 PM" src="https://user-images.githubusercontent.com/50120724/56926606-259f0180-6aa0-11e9-8bd2-907a2cc3f46f.png">
