### ISSUE TITLE
Incorrect sync of products in shop Fb page

### ISSUE THREAD

**Issue by pietroanello** [facebookincubator/facebook-for-woocommerce#734]
Hi, my shop Fb page does not contain all products. In business manager -> catalog everything is fine, and I've 100 products, but in shop settings there are only 52 products. 25 of this products have a double variation, and every product is in double language.

![cattura](https://user-images.githubusercontent.com/43348480/47563508-513f0480-d922-11e8-90a5-152bfccbdfe8.PNG)
![cattura2](https://user-images.githubusercontent.com/43348480/47563509-51d79b00-d922-11e8-9054-f20e11d5c91f.PNG)

**Comment by antareius** [comment]
## Automated Support Message - Issue Closed

Hello,

Because it has been 30 days since this issue was updated and you have not included `Debug Ready` in your reply, our automated system will now close your issue.
If you are still having this problem, please open a new issue and reference this one.

For more information on our response times and support policy, visit [Facebook Support on GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Facebook-Support-on-GitHub).

Thank you,
The Facebook Dev Team
