### ISSUE TITLE
@jieminz22 FYI, we disabled Page Editing for Woo. Because the Shop migration had too many edgecases. It's disabled for almost all platforms now.

### ISSUE THREAD

**Issue by rarytas** [facebookincubator/facebook-for-woocommerce#735]
Ambrish, as Jiemin said, you can still change the page by resetting entirely. That should work.

_Originally posted by @dmitridr in https://github.com/facebookincubator/facebook-for-woocommerce/issues/197#issuecomment-356459521_

Hi,

I tried this also but in my case after clicking DELETE there is an error "Something went wrong. Perhaps this is a temporary problem and we are working on solving it. Please try again later." - and its like that whole day (I've tried multiple times...) Please help!

**Comment by antareius** [comment]
## Automated Support Message - Issue Closed

Hello,

Because it has been 30 days since this issue was updated and you have not included `Debug Ready` in your reply, our automated system will now close your issue.
If you are still having this problem, please open a new issue and reference this one.

For more information on our response times and support policy, visit [Facebook Support on GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Facebook-Support-on-GitHub).

Thank you,
The Facebook Dev Team
