### ISSUE TITLE
My WooCommerce to Facebook tab appears on desktop but not on mobile

### ISSUE THREAD

**Issue by absaqib** [facebookincubator/facebook-for-woocommerce#736]
hi..
i recently install woocommerce to facebook on my wordpress website..it works perfect on a desktop pc.
but the tab does not appear on mobile devices..
do you have any solution for that?

**Comment by Luther2010** [comment]
Hey @absaqib, thanks for reporting! I was actually able to see the Facebook for WooCommerce plugin on mobile with the following steps
1. Go to your Wordpress dashboard page
2. Click the top left icon (shown in the screenshot)
![45585599_939377759589286_5018101769872343040_n](https://user-images.githubusercontent.com/5531870/48085634-ab0bbe00-e1af-11e8-8136-34e66089d402.jpg)
3. Click the WooCommerce tab
4. Click "Settings"
5. Click "Integration"

**Comment by absaqib** [comment]
Thanks luther for ur response..in wordpress admin menu..yes it is visible ..what i meant was it doesnot appear on real facebook page if sombody want to see it in mobile device on my facebook page its not visible..although its visible if somebody visit it on laptop,pc

**Comment by Luther2010** [comment]
hmm, I'm a little confused. What exactly are you trying to view on your Facebook page?

**Comment by absaqib** [comment]
Fb to wc tab

Sent from my iPhone

On 7 Nov 2018, at 20:42, Luther2010 <notifications@github.com<mailto:notifications@github.com>> wrote:


hmm, I'm a little confused. What exactly are you trying to view on your Facebook page?

**Comment by absaqib** [comment]
So that i can see products in my woocommerce web page on facebook

Sent from my iPhone

On 7 Nov 2018, at 20:42, Luther2010 <notifications@github.com<mailto:notifications@github.com>> wrote:


hmm, I'm a little confused. What exactly are you trying to view on your Facebook page?

**Comment by jameskim0903** [comment]
## Automated Support Message - Issue Closed

Hello,

Because it has been 30 days since this issue was updated and you have not included `Debug Ready` in your reply, our automated system will now close your issue.
If you are still having this problem, please open a new issue and reference this one.

For more information on our response times and support policy, visit [Facebook Support on GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Facebook-Support-on-GitHub).

Thank you,
The Facebook Dev Team
