### ISSUE TITLE
Wordpress multilingual site

### ISSUE THREAD

**Issue by poulsolbjerg** [facebookincubator/facebook-for-woocommerce#737]
Hi 
I have a multilingual Wordpress site EN, DE, DK, translated with WPLM. It is also a multi currency site, UK and DE currency is EURO and DK currency is DKK.

When I sync my products to Facebook with EN and DE set to hidden, they are imported anyway and the EN currency is DKK instead of EURO.

Is multi language and multi currency supported in this plugin..?? or will it be..?

Best regards
Poul

**Comment by mengyingdu** [comment]
## Automated Support Message - Issue Closed

Hello,

Because it has been 30 days since this issue was updated and you have not included `Debug Ready` in your reply, our automated system will now close your issue.
If you are still having this problem, please open a new issue and reference this one.

For more information on our response times and support policy, visit [Facebook Support on GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Facebook-Support-on-GitHub).

Thank you,
The Facebook Dev Team
