### ISSUE TITLE
Variable products

### ISSUE THREAD

**Issue by trev127** [facebookincubator/facebook-for-woocommerce#739]
Hi,
I've looked through and can't find the answer. Our shop is all variable products due to clothing size. Some products seem to sync with all variable options showing in the shop and others show one of the higher prices even thought the default is for the cheapest option.

**Comment by mengyingdu** [comment]
## Automated Support Message - Issue Closed

Hello,

Because it has been 30 days since this issue was updated and you have not included `Debug Ready` in your reply, our automated system will now close your issue.
If you are still having this problem, please open a new issue and reference this one.

For more information on our response times and support policy, visit [Facebook Support on GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Facebook-Support-on-GitHub).

Thank you,
The Facebook Dev Team
