### ISSUE TITLE
Sort by price og variation

### ISSUE THREAD

**Issue by bogtrykkeren** [facebookincubator/facebook-for-woocommerce#78]
I need to sort the products by price (all high to low) perhaps an option for sort by in variations.

**Comment by dmitridr** [comment]
Hello,

What is the context, is this within the shop? On the main screen? Or somewhere else?

**Comment by dmitridr** [comment]
In the current version v1.6.5, we list the default variation first per product, if you have one set. Though the rest are not sorted. So a workaround would be to set the highest price variation as default.

It's not clear to me whether your request is about sorting all products within the shop by price, or sorting all variations within each individual product by price. We would need clarification in order to consider implementing this.

**Comment by mengyingdu** [comment]
Hi @bogtrykkeren,

Given there's no more follow-up from your side, close this issue for now. If you have further questions, feel free to open a new one.
