### ISSUE TITLE
Facebook did not syncing the product over 72 hours later

### ISSUE THREAD

**Issue by bulbuljessore** [facebookincubator/facebook-for-woocommerce#782]
I read the #422 and follow everything but nothing working on my end. My shop products are still in process after 72 hours later. I have read the Facebook policy for shop and products but my shop does not have any issue on that. 

Would you guys please let me know what can I do not because it's very important to me. I was planning for Black Friday salse ads on Facebook.  Here is a screenshot of my shop http://prntscr.com/lm4q9s

However, I just noticed that one of my product is rejected I do not know why. http://prntscr.com/lm4qlj

Please help me to move forward with my business. I am stuck with it last 72 hours.

**Comment by mengyingdu** [comment]
## Automated Support Message - Issue Closed

Hello,

Because it has been 30 days since this issue was updated and you have not included `Debug Ready` in your reply, our automated system will now close your issue.
If you are still having this problem, please open a new issue and reference this one.

For more information on our response times and support policy, visit [Facebook Support on GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Facebook-Support-on-GitHub).

Thank you,
The Facebook Dev Team
