### ISSUE TITLE
New products with variations displayed separately

### ISSUE THREAD

**Issue by spradooooo** [facebookincubator/facebook-for-woocommerce#813]
Hello,

The plugin was working fine until every time I add a new product with variations is displayed separately.
for example, if a product has 3 colors variation it is synced to the shop 3 times with each color and sharing the parent name.

The old variations products are still working fine, when you visit a product on the shop page it display one time and inside is a dropdown to choose different color or storage size depends on the type of the variation.

Right now the shop is a mess and a lot of clutter.

Can you please let me know how to fix this and why it is happening?

url: https://www.cabreet.com/product-category/phones/
fb page: https://www.facebook.com/cabreet

Kind regards

**Comment by spradooooo** [comment]
Hi,

Debug Ready

Please find all the requested information below:

Woocommerce version: 3.5.1
Wordpress version: 4.9.9
Facebook for Woocommerce:  1.9.8 "latest"
A screenshot of where you see the problem: http://take.ms/s0HJp6
The URL of your website: https://www.cabreet.com
The URL of your Facebook Page: https://www.facebook.com/cabreet/
The URL(s) of where you took your screenshot(s): https://www.facebook.com/pg/cabreet/shop/?ref=page_internal&search_text=s9+%D8%A8%D9%84%D8%B3

Steps to see the problem:
1- visit https://www.facebook.com/pg/cabreet/shop/?ref=page_internal
2- go to all products
3- old products are fine and variations are displayed good.
4- the further you scroll down the newer products start to show its variation as individual products.
5- to be specific, search for "بلس s9" https://www.facebook.com/pg/cabreet/shop/?ref=page_internal&search_text=s9+%D8%A8%D9%84%D8%B3
and you will see the one product is displayed 13 times each color option and each storage option has it is own space.
6- click on any of the variation and you will see there is no drop down to select variations.

Note all the products with variations displayed sharing the same name for their parent product.

Hope you can assist me in getting the default behavior back because I want to start marketing using catalogs and individual products.

Kind regards

**Comment by andreiscerri** [comment]
Hi Am facing the same problem with my tracking as well. 

Pixel at checkout is tracking variations independently resulting in a chaotic tracking system right now. 

How is it possible to keep the main product/content ID to be tracked at all stages irrelevant of the variation?

Thank you very much

WooCommerce version: Version 3.5.3
WordPress version: 5.0.3
Plugin version: Version 1.9.8
A screenshot of where you see the problem- Problem has to do with tracking efficiency. YOu may see a description of this in the below screen shots:
Main product:
![image](https://user-images.githubusercontent.com/25829134/51425239-9b5e1c00-1bd9-11e9-8e2b-ad1bb4348c99.png)
Variation product:
![image](https://user-images.githubusercontent.com/25829134/51425230-81243e00-1bd9-11e9-9ee4-4e9d2abeba65.png)

The URL of your website https://artclassesmalta.com/
The URL of your Facebook Page https://www.facebook.com/ArtClassesMalta
The URL(s) of where you took your screenshot(s) https://artclassesmalta.com/courses/winter-art-course/
AND Cart: https://artclassesmalta.com/cart/

If applicable, detailed steps you took in order to see the problem:

As described earlier I prefer to maintain my main product/content ID to be tracked at all the different transcation stages (cart, checkout and purchase) rather than having the variations being tracked independently. to avoid chaotic data and for more efficient tracking optimization of the same product. 

Thanks and I look forward to hear from you! 

Regards, 
Andrei

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!
