### ISSUE TITLE
Memory Usage Maxed Out : Memory Leak?

### ISSUE THREAD

**Issue by creativeapparelstore** [facebookincubator/facebook-for-woocommerce#83]
Hi there, using Version 1.6.0. (updating as I type this to 1.6.3 and doing a force sync)

ISSUE: All variations show, not just 1 product. Example when showing products from a category - it will show the same product with different variations. I would like it to only show 1 variation per product.

I have a number of variable products (T-Shirts with Sizes: S,M,L,XL and various colours). 

Is it normal to have all the variables of the same product show (with the same image?)

I would like to use this plugin in facebook ad manager and show T-Shirts from a category. However, at the moment it will show plenty of the same t-shirts with different variations.

When I go into the Facebook product catalogue it shows all the variations with the same name, price and image. The only way to differentiate is to click to see the URL.

**Comment by dmitridr** [comment]
Hello,

Could you send us a screenshot of what you are seeing?

It sounds like a bug, if what you're seeing is in the shops interface. However if you are using catalog manager, then this is not a bug, it will display all variants of all products, so you can verify how they look. 

In ads, we will only show one of the variants (For Dynamic Ads, if set up correctly, only the variant the user was interested in) per product per ad. However, all of the variants are uploaded into our system since different users can be interested in different variants and our system optimizes on which one is best to show.

For shops, we should be displaying one variant the default variant, by default, and changing the value of the variant selector (e.g. color, size, etc) should display the other variants. If you're seeing multiple variants in the shops display that sounds like a bug.

**Comment by creativeapparelstore** [comment]
Catalogue manager displays all variants BUT I can’t tell which one is which. They all have the same colour image and there is no sizing details.

The only way I can tell is by clicking through and looking at the URL

Thanks,
Cruz Folmli

**Comment by dmitridr** [comment]
Hello Cruz,

The issue you describe is actually something we fixed very very recently, just yesterday. Could you try our new version [v1.6.4](https://github.com/facebookincubator/facebook-for-woocommerce/releases) and doing a 'Force Resync' ? If you have variant-specific images with different colors they should appear in catalog manager now instead of the same color image being shown everywhere.

The sizing details are there but we may not be showing it in catalog manager. If you send us a screenshot, I can pass that feedback to the catalog manager team.
These details should show up in the shop, however, if you have created one during setup.

**Comment by creativeapparelstore** [comment]
Hi Dmitiri,

 

What is the best way to manually update to the new version?

 

Screenshot here:



 

Thanks,

Cruz Folmli

Founder

 



 

7107 Riverview Crescent Hope Island 4212, QLD

(US) www.creativeapparelstore.com <http://www.creativeapparelstore.com> 

(AU) Coming Soon

__________________________________________

 

 <https://www.facebook.com/Basic-Tees-324352914671963/>   <https://www.instagram.com/CreativeApparelStore>

**Comment by dmitridr** [comment]
Unfortunately I didn't get your screenshot. You may have to go to our GitHub to upload it here 
https://github.com/facebookincubator/facebook-for-woocommerce/issues/83

To manually update the new version you can do as follows
1. Deactivate then Delete the old version within the `Plugins` tab.
2. Take the zip file from the [latest releases section](https://github.com/facebookincubator/facebook-for-woocommerce/releases/tag/v1.6.4) of our GitHub.
3. Upload the zip file using the 'Add' button on the Wordpress `Plugins` page.

You can also wait for WooCommerce to push a new version to their site, in order to update from there. It should take about a week for them to list the new version.

**Comment by creativeapparelstore** [comment]
Hi Dmitri,

 

I’ve just done that and clicked force resync and it says:

 

Progress: 50 items remaining.

 

My store has about 150+ items is this normal? I also noticed once I’ve clicked that that my Memory Usage and I/O Usage on the server has maxed out completely. 512MB and 1024KBps.

 

Thanks,

Cruz Folmli

Founder

 



 

7107 Riverview Crescent Hope Island 4212, QLD

(US) www.creativeapparelstore.com <http://www.creativeapparelstore.com> 

(AU) Coming Soon

__________________________________________

 

 <https://www.facebook.com/Basic-Tees-324352914671963/>   <https://www.instagram.com/CreativeApparelStore>

**Comment by creativeapparelstore** [comment]
Hi Dmitri,

 

I have since disable your plugin and the server is no longer maxed out in terms of Ram and I/O usage. I am with Go Daddy.

 

Memory: 150/512 (not installed), 512/512 (when installed)

                : 0-10/1024KBps (not installed) 1024/1024 (when installed)

 

Is this a bug with your plugin?

 

Thanks,

Cruz Folmli

Founder

 



 

7107 Riverview Crescent Hope Island 4212, QLD

(US) www.creativeapparelstore.com <http://www.creativeapparelstore.com> 

(AU) Coming Soon

__________________________________________

 

 <https://www.facebook.com/Basic-Tees-324352914671963/>   <https://www.instagram.com/CreativeApparelStore>

**Comment by dmitridr** [comment]
Hi Cruz,

Yes it does seem like a memory problem during sync. I'm not sure why it would be using that much memory, we don't see this on our own test servers. 

If you have the ability to raise your memory limits, I would try doing so. Memory issues are unfortunately extremely difficult to debug. Since not everyone is experiencing this problem, my guess is that our plugin combined with another plugin that you have is causing the memory issue. 

One thing to try, if you are interested in debugging this further with us, is to try and deactivate all other plugins except Woo and ours and force resync to see if the problem persists.

**Comment by dmitridr** [comment]
Discussion continued in #98
