### ISSUE TITLE
Facebook Price does not Woocommerce

### ISSUE THREAD

**Issue by Federicost** [facebookincubator/facebook-for-woocommerce#837]
Hi!
I have the Facebook WooCommerce plugin installed. Everything is working exept one thing.
For maintenance purposes, we need to enter the prices in WooCommerce in USD, but we show them in ARS (Peso Argentino) in our shop, product page, checkoutpage, etc.
We use a plugin called WooCommerce Booster that includes a Module to use a Formula to calculate the price to show.
Now when we sync our products, Facebook is showing the price we entered in the product in USD and not the one calculated by the formula. Is there a way to tell the Facebook plugin to take the calculated price instead of the one we entered?

**Comment by antareius** [comment]
## Automated Support Message - Issue Closed

Hello,

Because it has been 30 days since this issue was updated and you have not included `Debug Ready` in your reply, our automated system will now close your issue.
If you are still having this problem, please open a new issue and reference this one.

For more information on our response times and support policy, visit [Facebook Support on GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Facebook-Support-on-GitHub).

Thank you,
The Facebook Dev Team
