### ISSUE TITLE
Product not resync from Woo to Facebook shop

### ISSUE THREAD

**Issue by Novelfashionth** [facebookincubator/facebook-for-woocommerce#838]
Hi,
I used to be able to sync products from Woo to facebook shop. Later I deactivated Facebook for Woocommerce plugin, then re-activated the plugin. But now I can't fetch the products to Facebook shop. After I clicked Fetch now button on Your Product tab, the wheel kept spinning non-stop for more then 10 hours. I stopped it and re-clicked the button more than 3 times and the results were the same. 

My website is https://www.loveincocoth.com
My facebook page is https://www.facebook.com/incocothailand
Facebook for WooCommerce version is 1.9.8 
Woocommerce version is 3.5.3

**Comment by antareius** [comment]
## Automated Support Message - Issue Closed

Hello,

Because it has been 30 days since this issue was updated and you have not included `Debug Ready` in your reply, our automated system will now close your issue.
If you are still having this problem, please open a new issue and reference this one.

For more information on our response times and support policy, visit [Facebook Support on GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Facebook-Support-on-GitHub).

Thank you,
The Facebook Dev Team
