### ISSUE TITLE
Partial Product Sync Problem

### ISSUE THREAD

**Issue by AnywhereEverywhere** [facebookincubator/facebook-for-woocommerce#84]
I installed Facebook for WooCommerce last week, however, only a few of my variable products have synced and for the ones that have they haven't synced successfully (no all variants are available). Do you know why this is?
 
I have tried resyncing and updating WooCommerce, WordPress, etc but it has not helped. 
 
Please help.

**Comment by dmitridr** [comment]
Hello, 

Could you tell us the version you are using? If it's below 1.6.1, we advise upgrading as there was lots of problems with syncing in earlier versions.

**Comment by AnywhereEverywhere** [comment]
It was version 1.6.1.

Thanks :-)

**Comment by AnywhereEverywhere** [comment]
Any other ideas?

**Comment by javismiles** [comment]
folks, I have the latest  version of "facebook for woocommerce" and the latest version of the DIVI elegantthemes theme, and the latest version of Wordpress, and the latest version of everything, and the sync functionality of this plugin between woocommerce and facebook is a disaster to say the least, all sorts of weird things happen, it would be a long list, really somebody needs to do some serious quality testing on that syncing... then the plugin would be really useful finally, great idea for sure, best ;)

**Comment by AnywhereEverywhere** [comment]
I couldn't agree more with you javismiles. I think I am going to have to get rid of it until it is working consistently.

**Comment by dmitridr** [comment]
Hi Again,

If you tell us your page url we can check our own logs to see if your sync completed. 
Generally, if you have many products you will have to keep the FB for WooCommerce settings page open until the product sync completes, which can take a long time.

It could also be related to the memory issue seen in #83 or the issue at the bottom of #74 with partial sync.

I would also recommend checking your PHP error logs and looking for the string `facebook` around the time of the sync. If you see an exception which could be from the plugin breaking during sync, please paste it here.

**Comment by dmitridr** [comment]
Hi,

I see what you describe in our logs, looks like the sync started but never finished, most likely the PHP background process was killed somehow during sync. Unfortunately we don't know any more about the cause, we would need to see your PHP error logs in order to try to determine that.

Here are some more things you can try:
- Upgrade to our new version v1.6.5, try a full reset of the integration to see if it will work.
- On the `all products` page in WooCommerce, look at the status of each product. Is it synced to FB? If it is not, try doing a small update to this product (add whitespace to the description, for example, or set the FB description) and hit update to see if it syncs to FB.
- Try searching your PHP error logs for the string `facebook` and let us know if anything comes up.

**Comment by dmitridr** [comment]
@huebschie Was this a compatibility issue with `OvRcode` ?

**Comment by dmitridr** [comment]
Please try the new product sync unique to version v1.8.x which can be found here:

https://github.com/facebookincubator/facebook-for-woocommerce/releases

It is 60x faster and will most likely fix the sync problem. After upgrading, please reset your existing installation via `Reconfigure > Advanced Options > Delete` and set up again for maximal performance improvement.
