### ISSUE TITLE
Shop Button should say 'Buy' instead of 'Share'?

### ISSUE THREAD

**Issue by assanfulp** [facebookincubator/facebook-for-woocommerce#85]
After successfully integrating my woocommerce shop with Facebook, i rather see a share button on the product image instead of buy button. All the tutorials i saw pointed to the fact that there is a buy button. Clicking on the image though will lead to the page that connects you to the checkout page on my site.

Moreover, i couldn't edit the shop now button. Can't change to rather have buy now. 

Is it normal or there is something wrong somewhere?

Thanks so much.

**Comment by dmitridr** [comment]
Hello,

Could you share with us a screenshot to see where you see the share instead of the buy button?

We can pass your feedback over to the shops team, my guess would be they changed it because they found users engaged more with the 'Share' button than the 'Buy' button, in which case, we will likely keep that behavior. Though it's possible they can add an option to change the button text.

**Comment by assanfulp** [comment]
Thanks for responding dmitridr,

![20170612_155330 1](https://user-images.githubusercontent.com/23247502/31731506-d1e89fca-b424-11e7-9562-749e03bae0b3.jpg)

**Comment by assanfulp** [comment]
Thanks for responding dmitridr,

![20171016_213212 1](https://user-images.githubusercontent.com/23247502/31731776-9c06df06-b425-11e7-8b5f-2691ce2be03a.jpg)

**Comment by dmitridr** [comment]
Hello,

Thanks for your patience. We followed up with our shops team on this issue, this screen is only shown to the administrators of the page, and not the users. I believe the purpose is for you to share the products as an admin of the page.

Please feel free to open a new issue and reference this one if you have any follow up. Thanks!
