### ISSUE TITLE
Facebook pixel firing only PageView event on all pages

### ISSUE THREAD

**Issue by akashprakash93** [facebookincubator/facebook-for-woocommerce#857]
I'm facing this problem on my woocommerce store. I've installed the pixel ID using the official Facebook pixel plugin but the pixel is only firing the PageView event. Even if I add to cart or go to the checkout page or complete the purchase, it's only firing the PageView event. Can you please help?

Pixel ID: 1332706736829932

![image](https://user-images.githubusercontent.com/47221197/52070178-41306400-25a6-11e9-8cc5-c339238a956c.png)

As you can see, I'm on the checkout page and only the PageView event is fired. The standard events (Add to cart, Initiate checkout, Purchase etc.) are set up by default right? Is there something I need to do?

**Comment by condor304** [comment]
I have the same problem. I'm using facebook for woocommerce plugin and all I can see are pageview events. Nothing else.

**Comment by akashprakash93** [comment]
Please find the required details below: 

WooCommerce version: Version 3.5.4
WordPress version: Version 5.0.3
Plugin version (please note: we only support up-to-date versions of the plugin): Official Facebook Pixel Version 1.7.23
The URL of your website: https://boringstoreonline.com
The URL of your Facebook Page: https://facebook.com/boringstoreonline 
The URL(s) of where you took your screenshot(s): https://boringstoreonline.com/checkout/

Debug Ready

**Comment by condor304** [comment]
For me the problem was the jquery loading after the pixel code - I had moved the scripts in the footer for performance. but you must load jquery on the header because both fb pixel and google analytics use it.
Check the console of the browser if you see a jquery missing error that is your fix.

and you should also upgrade the plugin to the latest version.

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by lgfogle** [comment]
Hey there! 👋

Lindsey here, from the SkyVerge product team! We recently took over development and support for the Facebook for WooCommerce extension.

In our recent 1.10 releases, we've fixed many issues impacting the store connection, pixel tracking, and product sync. Could you please update to the latest version of Facebook for WooCommerce and see if that resolves this issue?

If not, could you please [contact our support team](https://woocommerce.com/my-account/create-a-ticket/) or open a new issue here? We'd be happy to help troubleshoot further with you.

Thank you!

**Comment by fabiograsso** [comment]
Hello there,
I'm facing the same issue: Facebook pixel is loaded but no events are sent. Not only the pageView events but also other events like checkout, addToCart, initiatedCheckout and so on

After investing I've found out that this is due to my Cookie blocking solution. I'm using [iubenda – Cookie and Consent Solution for the GDPR & ePrivacy](https://it.wordpress.org/plugins/iubenda-cookie-law-solution/). They deactivate the script by changing the HTML code with:
`<script  type="text/plain" class="_iub_cs_activate-inline">`
Then, after user accept the cookie banner, all the scripts are loaded by their Javascript.

This works fine for almost all plugins and themes but there is something in Facebook for Woocommerce that's mading this not working as expected.
I will ask to Iubenda support.

Maybe other people that are facing this issue are using some kind of script blocking plugin, like mine for manage Cookie law.
