### ISSUE TITLE
No product appear when I I try to add but they are posted on facebook timeline

### ISSUE THREAD

**Issue by crackunia** [facebookincubator/facebook-for-woocommerce#864]
Hi all! its my first post here. got big problem with adding products on my facebook page.
once I try to add product it does not show in shop section but it is posted on timeline. 
Everything worked fine until 2 month ago.
I dont have woocommerce web site. I just want to add products on facebook shop.
somebody please check it and let me know whet the issue.

https://www.facebook.com/Fratellosmoto/

Posting from Tbilisi, Georgia

**Comment by jieminz22** [comment]
## Automated Support Message - Issue Closed

Hello,

Because it has been 30 days since this issue was updated and you have not included `Debug Ready` in your reply, our automated system will now close your issue.
If you are still having this problem, please open a new issue and reference this one.

For more information on our response times and support policy, visit [Facebook Support on GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Facebook-Support-on-GitHub).

Thank you,
The Facebook Dev Team
