### ISSUE TITLE
Pixel passing 'lead' events

### ISSUE THREAD

**Issue by GitStl** [facebookincubator/facebook-for-woocommerce#882]
My plugin is passing 'lead' events for every page view. I can't seem to find where to eliminate that.

**Comment by jameskim0903** [comment]
## Automated Support Message - Issue Closed

Hello,

Because it has been 30 days since this issue was updated and you have not included `Debug Ready` in your reply, our automated system will now close your issue.
If you are still having this problem, please open a new issue and reference this one.

For more information on our response times and support policy, visit [Facebook Support on GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Facebook-Support-on-GitHub).

Thank you,
The Facebook Dev Team
