### ISSUE TITLE
I want to reset facebook for woocommerce plugin settings

### ISSUE THREAD

**Issue by teamyachezz** [facebookincubator/facebook-for-woocommerce#883]
I want to reset facebook for woocommerce plugin settings, As I switch to new domain but my plugin have the old facebook page settings. Kindly help me out here.

**Comment by jameskim0903** [comment]
## Automated Support Message - Issue Closed

Hello,

Because it has been 30 days since this issue was updated and you have not included `Debug Ready` in your reply, our automated system will now close your issue.
If you are still having this problem, please open a new issue and reference this one.

For more information on our response times and support policy, visit [Facebook Support on GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Facebook-Support-on-GitHub).

Thank you,
The Facebook Dev Team
