### ISSUE TITLE
Facebook for Woocommerce product upload error

### ISSUE THREAD

**Issue by ncpmt** [facebookincubator/facebook-for-woocommerce#885]
I'm trying to sync products from my woocommerce shop to fb and the plugin upload is always completed, but on fb product data source the upload always fails. 

It says: Your Data Feed File Can't Be Empty - Add products to your data feed file and then upload it again. Uploading an empty file will delete all products in your feed. If you want to do this, please delete the feed they were uploaded from.

Before installing plugin Facebook for Woocommerce I already used plugin Facebook Pixel. I disabled and removed it and then installed the plugin for woocommerce, now I thing already 5 times and it always has this error.

Any ideas?

Thanks!

**Comment by zdytch** [comment]
Same issue

**Comment by ncpmt** [comment]
Did you maybe find a solution?

**Comment by chrisschwartze** [comment]
I'm running into the same issue.

```
Your Data Feed File Can't Be Empty                                           (1 product rejected)
Add products to your data feed file and then upload it again. Uploading an empty file will delete all products in your feed. If you want to do this, please delete the feed they were uploaded from.
```

**Comment by alepycom** [comment]
same issue here!!

**Comment by KobbyMmo** [comment]
Same issue here too

**Comment by KobbyMmo** [comment]
Mine worked when i added prices to products
I realized it syncs only product with prices

**Comment by Luther2010** [comment]
## Automated Support Message - Issue Closed

Hello,

Because it has been 30 days since this issue was updated and you have not included `Debug Ready` in your reply, our automated system will now close your issue.
If you are still having this problem, please open a new issue and reference this one.

For more information on our response times and support policy, visit [Facebook Support on GitHub](https://github.com/facebookincubator/facebook-for-woocommerce/wiki/Facebook-Support-on-GitHub).

Thank you,
The Facebook Dev Team

**Comment by goldishbird** [comment]
Any solutions so far?

**Comment by francescosche** [comment]
Any solutions?

**Comment by nictricot** [comment]
Any solutions?

**Comment by vipsouq** [comment]
Any solutions to this?
