### ISSUE TITLE
Allow users to choose what ID to show

### ISSUE THREAD

**Issue by pukander** [facebookincubator/facebook-for-woocommerce#93]
Hi,

I'm having a problem with this plugin - for some reason, there are three Ids displayed in the content_ids array. The first ID is correct, but the two other IDs are not welcome.

The first ID is the SKU and this is meant to be since we use this for the ID in the product catalog to match the products and its also used in Enhanced E-commerce payloads to identify the products. (to keep a unified ID across platforms).  

Looking at the problem using the Event debugger found in the product catalogs I can see the additional two IDs also being sent to Facebook. Looks like this (for the purchase event).

1 Purchased products that are in this catalog
2 Purchased products that are not in any catalog

These IDs are being sent, using the Purchase event example above: (altered for the example).
["12345","wc_post_id_6789","12345_6789"]

12345 matched.
wc_post_id_6789 not found
12345_6789 not found

We have not done any configurations to the plugin. 
Can someone explain how we only include the first value as content ID?
Do we need to make changes in the php files for the plugin? 

At the same time, I have a feature request:
- Allow users to choose what ID to show, (sku as id, post id etc).

**Comment by dmitridr** [comment]
Hello,

The three IDs are there for backwards compatibility with older versions of the extension. So if you had installed the extension v1.1, you would match the first or second ID. If you installed the extension for the first time starting from v1.6.0 you should match only the last ID. In all cases only 1 of the IDs will match, the other 2 are ignored by our system and should be harmless.

To be brief, the reason we moved away from using SKU was because of a bug that occurred when using just the SKU as ID. If I remember correctly it was a huge problem caused by duplicated and null SKUs and product uploads would fail for hundreds of stores. Of course, if you have no duplicate SKUs you wouldn't be affected.

If you're willing to edit the plugin using the Wordpress default plugin editor, you can try to remove the other two IDs [here](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/includes/fbutils.php#L114)

Then change [this line](https://github.com/facebookincubator/facebook-for-woocommerce/blob/master/includes/fbutils.php#L73) to just `return $woo_product->get_sku();`

If you have created new products recently, those will probably use the 3rd ID and you would have to update those or Force Resync. 

We'll consider your feature request! Thanks.

**Comment by dmitridr** [comment]
Happy to say we fixed this recently, in v[1.7.0](https://github.com/facebookincubator/facebook-for-woocommerce/releases/)! There's only one ID shown now. Please upgrade for the fix!

**Comment by pukander** [comment]
This is awesome dmitridr! Only one small problem. Looks like this version adds "wc_post_id_" before the ID and normally other plugins in Enhanced Ecommerce used in GA and for creating catalog XML would also use the ID. What I mean is that using 1234 as the id instead of wc_post_id_1234. 
Would be nice to be able to change the ID via the plugin. 

Do you think my issue could be solved by removing "wc_post_id_" from the const FB_RETAILER_ID_PREFIX = 'wc_post_id_';
