### ISSUE TITLE
Product still shows up on Facebook.

### ISSUE THREAD

**Issue by Tommielarsson** [facebookincubator/facebook-for-woocommerce#94]
I have delete, forced reset and deleted cache but one t-shirt with the prize of 0 still shows up (see images).

I only have 3 products currently but the shop shows 4 from one I delete 1 week ago. I have the latest version of Facebook for Woocommerce, Woocommerce and Wordpress installed.

![tshirt](https://user-images.githubusercontent.com/3650624/31618089-43b44acc-b291-11e7-9b0a-a493f5c92d28.jpg)
![tshirt-fb](https://user-images.githubusercontent.com/3650624/31618090-43d3e076-b291-11e7-8023-b110f0304538.jpg)

**Comment by dmitridr** [comment]
Hello,

Could you link to the specific product on your shop? This will help us debug.

If you have v1.6.4 of the plugin and you do a Force Resync, all products with price 0 in the shop should become invisible to customers. Is that not occurring? 

If the product is in the trash or not permanently deleted, this may be fixed by untrashing it and clicking 'delete on facebook'.

**Comment by dmitridr** [comment]
Related to #75

**Comment by Tommielarsson** [comment]
I don't have the product currently. I permanently deleted in and I have Force Resync many times to see if it would fix it. It's strange.

**Comment by dmitridr** [comment]
Ok, seems like you managed to resolve it then. I agree it's strange, and it's probably related to #75 maybe the product was trashed at one point. I will close this, but please re-open if it happens again.

**Comment by Tommielarsson** [comment]
Yes, the product has been trashed at one point in time, but still shows up as "free" on Facebook. 

The problem is not resolved, it's still current.
